// Textos del editor en inglés (EE. UU.), con el vocabulario de consultoría de procesos
// del shell (shell/textos/en.ts): process sheet, pain points, revision, standalone
// editor, lane, gateway. Mismas claves y variables {x} que es.js.
export const en = {
  // ---------------------------------------------------------------- index.html (textos/html.js)
  'html.titulo': 'ProcessIQ — BPMN process diagramming · MBC Peru',
  'html.movil.titulo': 'ProcessIQ is designed for desktop',
  'html.movil.texto': 'It is a process diagramming tool with editing panels and a wide canvas: it works best on a large screen (laptop or monitor).',
  'html.movil.continuar': 'Continue anyway',
  'html.movil.pie': 'MBC · Business Consulting · Peru',
  'html.marca.sub': 'Business Consulting · Peru',
  'html.cab.nombre': 'Process name (e.g. Claims Management)',
  'html.cab.meta': 'Industry and macroprocess',
  'html.cab.industria': 'Industry',
  'html.cab.industriaVacia': '— Industry —',
  'html.cab.macro': 'Macroprocess',
  'html.cab.macroVacio': '— Macroprocess —',
  'html.cab.vistas': 'Switch between the As-Is and To-Be views',
  'html.cab.clonar': 'Clone As-Is → To-Be (to start the redesign)',
  'html.cab.clonarAria': 'Clone As-Is to To-Be',
  'html.cab.transformar': 'Generates the To-Be by applying redesign levers by level (Operational/Tactical/Strategic)',
  'html.cab.transformarBoton': 'AI To-Be',
  'html.cab.nuevoTitulo': 'New process',
  'html.cab.nuevo': 'New',
  'html.cab.ingestarTitulo': 'Ingest from audio, notes or an event log',
  'html.cab.ingestar': 'Ingest',
  'html.cab.importar': 'Import JSON project',
  'html.cab.ajustesIa': 'AI settings (Claude)',
  'html.cab.presentarTitulo': 'Presentation mode: hides the toolbars and maximizes the diagram (Esc to exit)',
  'presentar.boton': '⛶ Present',
  'html.cab.exportar': 'Export',
  'html.exp.json': 'JSON · project',
  'html.exp.svg': 'SVG · vector',
  'html.exp.png': 'PNG · image',
  'html.exp.grupoPptx': 'PPTX by design',
  'html.exp.mbcPista': 'blue, Montserrat',
  'html.exp.bbva': 'PPTX · BBVA client',
  'html.exp.bbvaPista': 'Flow Value template',
  'html.exp.grupoOtros': 'Other formats',
  'html.exp.word': 'Word · process report',
  'html.exp.ficha': 'Process Sheet · corporate format',
  'html.riel.aria': 'Drawing tools',
  'html.riel.formasTitulo': 'Add a shape to the canvas',
  'html.riel.formas': 'Add',
  'html.riel.arrastra': 'Drag onto the canvas',
  'html.forma.inicio': 'Start',
  'html.forma.actividad': 'Activity',
  'html.forma.decisionTitulo': 'Decision / gateway',
  'html.forma.decision': 'Decision',
  'html.forma.documento': 'Document',
  'html.forma.sistema': 'System',
  'html.forma.fin': 'End',
  'html.riel.conectarTitulo': 'Connect mode (C)',
  'html.riel.conectar': 'Connect',
  'html.riel.eliminarTitulo': 'Delete selection (Del)',
  'html.riel.eliminar': 'Delete',
  'html.riel.ordenarTitulo': 'Auto-layout: rearranges the diagram',
  'html.riel.ordenar': 'Arrange',
  'html.inicio.titulo': 'Start your process mapping',
  'html.inicio.sub': 'Three ways to create the process flowchart',
  'html.inicio.ingestar': 'Ingest a source',
  'html.inicio.ingestarDesc': 'Interview audio, notes, a document or a CSV event log',
  'html.inicio.ejemplo': 'Load an example',
  'html.inicio.ejemploDesc': 'A complete demo process (pain points, KPIs, simulation) to explore',
  'html.inicio.dibujar': 'Draw it yourself',
  'html.inicio.dibujarDesc': 'Press ＋ on the left toolbar or use the AI copilot',
  'html.hist.deshacerTitulo': 'Undo (Ctrl/⌘ Z)',
  'html.hist.deshacerAria': 'Undo the last change',
  'html.hist.rehacerTitulo': 'Redo (Ctrl/⌘ Y · Ctrl/⌘ Shift Z)',
  'html.hist.rehacerAria': 'Redo the undone change',
  'html.hist.autoajustarTitulo': 'Auto-fit: rearranges the diagram and checks that no arrows cross',
  'html.hist.autoajustarAria': 'Auto-fit the diagram',
  'html.hist.atajosTitulo': 'Keyboard shortcuts (? key)',
  'html.hist.atajosAria': 'Show keyboard shortcuts',
  'html.atajos.titulo': 'Keyboard shortcuts',
  'comun.cerrar': 'Close',
  'html.atajos.cerrar': 'Close shortcuts',
  'html.atajos.deshacer': 'Undo',
  'html.atajos.rehacer': 'Redo',
  'html.atajos.acercar': 'Zoom in',
  'html.atajos.alejar': 'Zoom out',
  'html.atajos.rueda': 'wheel',
  'html.atajos.zoomCursor': 'Zoom toward the cursor',
  'html.atajos.ajustar': 'Fit to screen',
  'html.atajos.conectar': 'Connect mode',
  'html.atajos.supr': 'Backspace',
  'html.atajos.eliminar': 'Delete selection',
  'html.atajos.esc': 'Deselect / exit mode',
  'html.atajos.mostrar': 'Show/hide these shortcuts',
  'html.atajos.nota': 'Double-click a node to edit its label · ＋ opens the shapes to drag',
  'html.leyenda.titulo': 'BPMN 2.0 notation',
  'html.leyenda.cerrar': 'Close legend',
  'html.leyenda.formas': 'Shapes and flows',
  'html.leyenda.actividad': 'Activity / task',
  'html.leyenda.tareaSistema': 'System task',
  'html.leyenda.datos': 'Data / record',
  'html.leyenda.secuencia': 'Sequence flow',
  'html.leyenda.mensaje': 'Message flow (between lanes)',
  'html.leyenda.eventos': 'Events (circles)',
  'html.leyenda.inicioMensaje': 'Start (message)',
  'html.leyenda.intermedio': 'Intermediate · double ring (timer)',
  'html.leyenda.finError': 'End (error)',
  'html.leyenda.senal': 'Signal (broadcast 1→N)',
  'html.leyenda.terminacion': 'Terminate (ends the instance)',
  'html.leyenda.borde': 'Boundary (SLA/exception on a task)',
  'html.leyenda.notaEventos': 'Outline = catch (receives) · Filled = throw (sends) · Dashed = non-interrupting',
  'html.leyenda.gateways': 'Gateways and markers',
  'html.leyenda.xor': 'Exclusive XOR (one path)',
  'html.leyenda.and': 'Parallel AND (fork/join)',
  'html.leyenda.or': 'Inclusive OR (one or more)',
  'html.leyenda.subproceso': 'Marker: subprocess',
  'html.leyenda.loop': 'Marker: loop (repeating)',
  'html.leyenda.multi': 'Marker: multi-instance',
  'html.leyenda.notaTareas': 'Tasks carry a color chip + code [USR-01].',
  'html.estado.modo': 'Edit mode',
  'estado.guardado': 'Saved',
  'html.nivel.titulo': 'Flow level of detail',
  'html.nivel.ejecutivoTitulo': 'Executive: the process in 5-10 stages, without lanes',
  'nivel.ejecutivo': 'Executive',
  'html.nivel.actividadTitulo': 'Activity: groups consecutive tasks of the same actor',
  'nivel.actividad': 'Activity',
  'html.nivel.detalleTitulo': 'Detail: every task, as it was mapped',
  'nivel.detalle': 'Detail',
  'html.zoom.titulo': 'Zoom · Ctrl/⌘ + mouse wheel to zoom in at the cursor · F key to fit',
  'html.zoom.alejarTitulo': 'Zoom out (Ctrl/⌘ −)',
  'html.zoom.nivelTitulo': 'Reset to 100% (Ctrl/⌘ 0)',
  'html.zoom.nivelAria': 'Zoom level; click to reset to 100%',
  'html.zoom.acercarTitulo': 'Zoom in (Ctrl/⌘ +)',
  'html.zoom.ajustarTitulo': 'Fit the whole process to the screen (F key)',
  'html.zoom.ajustarAria': 'Fit the whole process to the screen',
  'html.zoom.ajustar': '⤢ Fit',
  'html.pest.aria': 'Analysis panels',
  'html.pest.props': 'Properties of the selected node',
  'html.pest.kpis': 'KPI library',
  'html.pest.sim': 'FTE and lead time simulator',
  'html.pest.lint': 'MBB validations · linter',
  'html.pest.ficha': 'Corporate process sheet',
  'html.pest.fichaCorta': 'Sheet',
  'html.pest.copiloto': 'AI copilot',
  'html.pest.copilotoCorta': 'AI',
  'html.pest.leyendaTitulo': 'BPMN notation legend',
  'html.pest.leyenda': 'Legend',
  'html.cajon.titulo': 'Properties',
  'html.cajon.cerrarTitulo': 'Close panel (Esc)',
  'html.cajon.cerrarAria': 'Close panel',
  'html.props.vacio': 'Select a node to see its properties.',
  'html.props.tipo': 'BPMN block type',
  'html.props.tipoInicio': '● Start',
  'html.props.tipoIntermedio': '◎ Intermediate event',
  'html.props.tipoActividad': '▭ Activity',
  'html.props.tipoSistema': '▭ System',
  'html.props.tipoDecision': '◇ Decision / Gateway',
  'html.props.tipoDocumento': '▤ Document',
  'html.props.tipoFin': '◉ End',
  'html.props.codigo': 'Activity code',
  'html.props.gateway': 'BPMN gateway type',
  'html.props.gwExclusivo': '✕ Exclusive (XOR — a single path)',
  'html.props.gwParalelo': '＋ Parallel (AND — every path)',
  'html.props.gwInclusivo': '○ Inclusive (OR — one or more)',
  'html.props.evento': 'BPMN event type',
  'html.props.evNinguno': '— Plain (none)',
  'html.props.evMensaje': '✉ Message',
  'html.props.evTimer': '⏱ Timer (wait)',
  'html.props.evSenal': '▲ Signal',
  'html.props.terminacion': 'Terminate event ⬤ <span style="text-transform:none;color:var(--gray-500);font-weight:400">— ends the whole instance</span>',
  'html.props.etiqueta': 'Label ·',
  'html.props.etiquetaPista': 'verb + object',
  'html.props.etiquetaEjemplo': 'E.g. Validar identidad del cliente',
  'html.props.tipoTarea': 'Task type (BPMN marker)',
  'html.props.selecciona': '— Select —',
  'html.props.marcador': 'BPMN activity marker',
  'html.props.mkSimple': '— Plain task',
  'html.props.mkSubproceso': '⊞ Subprocess (collapsed)',
  'html.props.mkLoop': '↻ Loop (repeating)',
  'html.props.mkMulti': '‖ Multi-instance (parallel)',
  'html.props.mkMultiSeq': '≡ Multi-instance (sequential)',
  'html.props.borde': 'BPMN boundary event',
  'html.props.bordePista': '— exception/SLA on the task',
  'html.props.bdNinguno': '— None',
  'html.props.bdTimerInt': '⏱ Timer — interrupting',
  'html.props.bdTimerNoInt': '⏱ Timer — non-interrupting (dashed)',
  'html.props.bdErrorInt': '⚡ Error — interrupting',
  'html.props.bdMensajeNoInt': '✉ Message — non-interrupting (dashed)',
  'html.props.responsable': 'Owner / Role',
  'html.props.responsableEjemplo': 'E.g. Back office analyst',
  'html.props.sistema': 'Supporting system',
  'html.props.sistemaEjemplo': 'E.g. SAP, Salesforce',
  'html.props.tiempo': 'Time (min)',
  'html.props.volumen': 'Volume / month',
  'html.props.valor': 'Value added',
  'html.props.va': 'VA — Value Added',
  'html.props.slaEjemplo': 'E.g. ≤ 2h',
  'html.props.docsEntrada': 'Input documents',
  'html.props.docsEntradaEjemplo': 'E.g. ID, proof of income',
  'html.props.docsSalida': 'Output documents',
  'html.props.docsSalidaEjemplo': 'E.g. Signed contract, receipt',
  'html.props.reglas': 'Decision rules / criteria',
  'html.props.reglasEjemplo': 'Conditional logic, approval criteria, thresholds…',
  'html.props.notas': 'Notes / additional comments',
  'html.pains.pista': 'Select a node and capture its pain points.',
  'html.pains.describe': 'Describe the pain point...',
  'html.pains.severidad': 'Severity',
  'html.pains.sev1': '1 — low',
  'html.pains.sev3': '3 — medium',
  'html.pains.sev5': '5 — critical',
  'html.pains.frecuencia': 'Frequency',
  'html.pains.frec1': '1 — rare',
  'html.pains.frec5': '5 — constant',
  'html.pains.agregar': '+ Add pain point',
  'html.kpis.buscar': 'Search KPIs...',
  'html.kpis.todas': 'All industries',
  'html.sim.titulo': 'Workload simulator',
  'html.sim.pista': 'Calculates FTE, lead time and cost from the <strong>times</strong> and <strong>volumes</strong> captured for each activity. Fill in "Time (min)" and "Volume / month" in the Props tab to feed the simulation.',
  'html.sim.costo': 'Monthly FTE cost (PEN)',
  'html.sim.horas': 'Working hours/month',
  'html.sim.reduccion': '% expected to-be reduction',
  'html.sim.wizard': '⚡ Quick time capture (wizard)',
  'html.sim.ejecutar': '▶ Run simulation',
  'html.lint.titulo': 'Validations · MBB Playbook',
  'html.lint.pista': 'Automatic linter that checks naming, layout, gateways, metadata and anti-patterns. Severity: <span class="sev-tag sev-critical">critical</span> (best resolved before exporting) · <span class="sev-tag sev-high">high</span> · <span class="sev-tag sev-medium">medium</span> · <span class="sev-tag sev-low">low</span>.',
  'html.ficha.titulo': 'Process sheet',
  'html.ficha.pista': 'Corporate metadata of the sheet. The <b>activities, systems, owners and the diagram</b> are generated automatically from the canvas flow.',
  'html.ficha.codigo': 'Code',
  'html.ficha.version': 'Version',
  'html.ficha.objetivo': 'Objective',
  'html.ficha.objetivoEjemplo': 'Describe the activities and responsibilities of the process…',
  'html.ficha.areas': 'Scope · areas involved',
  'html.ficha.areasEjemplo': 'Urban Lot Sales, Sales Administration',
  'html.ficha.desde': 'Starts with',
  'html.ficha.desdeEjemplo': '(auto from the Start node)',
  'html.ficha.hasta': 'Ends with',
  'html.ficha.hastaEjemplo': '(auto from the End node)',
  'html.ficha.incluye': 'Includes / excludes',
  'html.ficha.incluyeEjemplo': 'Covers residential and second-home lots',
  'html.ficha.descripcion': 'Description (optional)',
  'html.ficha.descripcionEjemplo': 'General context of the process…',
  'html.ficha.gobernanzaPista': 'Governance — <b>one row per line</b>, fields separated by <code>|</code>: <code>Role | Position | Name | Date</code>',
  'html.ficha.gobernanza': 'Governance',
  'html.ficha.gobernanzaEjemplo': 'Owner | Head of Sales | Carlos Rolleri | 10/02/2026\nApprover | VP Urban Development | Carlos Conroy | 10/02/2026',
  'html.ficha.sistemasPista': 'Process-level systems — <code>System | Use</code> (each node’s systems are also added automatically)',
  'html.ficha.sistemas': 'Systems',
  'html.ficha.sistemasEjemplo': 'ONBASE | Document management\nSAP | ERP / sale closing',
  'html.ficha.terminosPista': 'Key terms — <code>Term | Definition</code>',
  'html.ficha.terminos': 'Terms',
  'html.ficha.terminosEjemplo': 'Lead | Interested person who shares their contact details\nOpportunity | Potential sale of a lot to a prospect',
  'html.ficha.anexosPista': 'Appendices — <code>Code | Name</code>',
  'html.ficha.anexos': 'Appendices',
  'html.ficha.anexosEjemplo': 'Appendix No. 1 | Know-your-customer affidavit (AML)',
  'html.ficha.cambiosPista': 'Change log — <code>Version | Date | Description</code>',
  'html.ficha.cambios': 'Change log',
  'html.ficha.cambiosEjemplo': '1 | 10/04/2023 | Full update of the document',
  'html.ficha.generarTitulo': 'View and download the full sheet',
  'html.ficha.generar': 'Generate sheet',
  'html.copiloto.pista': 'An assistant to speed up process mapping and diagnosis.',
  'html.copiloto.generate': 'Generate process from a description',
  'html.copiloto.detectPains': 'Detect pain points in the diagram',
  'html.copiloto.suggestKpis': 'Suggest applicable KPIs',
  'html.copiloto.proposeTobe': 'Propose to-be redesign',
  'html.copiloto.raci': 'Generate RACI matrix',
  'html.copiloto.sipoc': 'Generate SIPOC',
  'html.copiloto.impactEffort': 'Impact–effort matrix',
  'html.copiloto.whatif': 'Scenario comparison (What-If)',
  'html.copiloto.automation': 'Automation opportunities',
  'html.copiloto.bottleneck': 'Bottleneck / critical path',
  'html.copiloto.variants': 'Variant analysis (event log)',
  'html.copiloto.valueMap': 'Lean value map (VA/NVA)',
  'html.copiloto.backlog': 'Initiative backlog',
  'html.copiloto.aiPains': 'In-depth pain point analysis (AI)',
  'html.copiloto.autofit': 'Auto-fit (check crossings)',
  'html.copiloto.relayout': 'Rearrange diagram (compact)',
  'html.copiloto.mergeGateways': 'Insert merging gateways',
  'html.copiloto.execSummary': 'Executive summary',
  'html.copiloto.comandos': 'Commands (in Spanish): \'agregar Validar score después de Registrar\', \'eliminar Aprobar\', \'renombrar X a Y\', \'conectar X con Y\', \'marcar X como automático\'…',
  'html.copiloto.enviar': 'Send',
  'comun.cancelar': 'Cancel',
  'comun.aceptar': 'OK',
  'html.ingesta.titulo': '📥 Ingest sources — build the process automatically',
  'html.ingesta.sub': 'ProcessIQ can map the flowchart from <strong>interview audio</strong>, <strong>client notes/documentation</strong>, or <strong>event logs</strong> from their systems.',
  'html.ingesta.pestNotas': '📝 Notes / Documentation',
  'html.ingesta.pestAudio': '🎤 Audio / Transcript',
  'html.ingesta.pestLog': '🗄 Event Log (Process Mining)',
  'html.ingesta.audioPista': 'Record the interview live (requires a microphone and Chrome/Edge) or paste an existing transcript. ProcessIQ will analyze the text and build the as-is flowchart.',
  'html.ingesta.grabar': '🔴 Record',
  'html.ingesta.detener': '⏹ Stop',
  'grabacion.listo': 'ready',
  'html.ingesta.transcripcion': 'The transcript will appear here. You can also paste text directly.',
  'html.ingesta.generarAudio': 'Generate process from transcript →',
  'html.ingesta.notasPista': 'Paste mapping notes, procedure manuals, client descriptions or any text that describes the process step by step. One sentence = one possible activity.',
  'html.ingesta.soltarAria': 'Drop your documents here or click to choose them; you can select several',
  'html.ingesta.soltar': 'Drop your documents here',
  'html.ingesta.soltarSub': 'or <b>click to choose them</b> (you can select several) — Word · PDF · PowerPoint · text · BPMN',
  'html.ingesta.ceroFuentes': '0 sources',
  'html.ingesta.otraFuenteTitulo': 'Add another document, transcript or diagram',
  'html.ingesta.otraFuente': '+ Add another source',
  'html.ingesta.combinar': 'They will be merged into a single AS-IS. Where they contradict each other, the most recent source prevails (e.g. the mapping-interview transcript over an old diagram).',
  'html.ingesta.procesando': 'Processing…',
  'html.ingesta.pegar': 'or paste the text by hand',
  'html.ingesta.notasEjemplo': 'Example:\n1. The client requests the service through the web portal.\n2. The sales advisor validates the data and records the request in Salesforce.\n3. If the amount exceeds 50,000 USD, approval from the sales manager is required.\n4. Operations receives the approved request and activates it in the core system.\n5. The client is notified and the case is closed.\n\nAny format works: bullets, paragraphs, mixed notes...',
  'html.ingesta.generarTitulo': 'Extracts, interprets and draws the process',
  'ingesta.generarProceso': 'Generate process',
  'html.ingesta.ejemplosTitulo': 'Explore the example processes',
  'html.ingesta.ejemplos': 'See examples',
  'html.ingesta.logPista': 'Upload an <strong>event log</strong> in CSV with at least these columns: <code>case_id, activity, timestamp</code> (optional: <code>resource</code>). ProcessIQ will run a lightweight <em>process discovery</em> — it identifies unique activities and the most frequent transitions (alpha-miner style).',
  'html.ingesta.muestra': '📋 Use sample',
  'html.ingesta.colCaso': 'case_id column',
  'html.ingesta.colActividad': 'activity column',
  'html.ingesta.colFecha': 'timestamp column',
  'html.ingesta.colRecurso': 'resource column (optional)',
  'html.ingesta.descubrir': 'Discover process →',
  // ---------------------------------------------------------------- Header, dialog and presentation
  'cabecera.confirmarNuevo': 'Create a new process? The current one will be lost if it has not been exported.',
  'cabecera.disenarToBe': 'Design the To-Be process (AI).',
  'estado.modo': 'Mode: {modo}',
  'estado.modoConexion': 'connect (click source and target)',
  'estado.modoEdicion': 'edit',
  'modal.error': 'Error: {mensaje}',
  'presentar.salir': '✕ Exit',
  // ---------------------------------------------------------------- Status bar, canvas and levels
  'estado.guardando': 'Saving',
  'estado.errorGuardar': 'Could not save',
  'estado.nodos': '{n} nodes',
  'estado.conexiones': '{n} connections',
  'lienzo.etiquetaConexionEj': 'Connection label (e.g. "Yes", "No", "Approved", or a frequency):',
  'lienzo.etiquetaConexion': 'Connection label:',
  'lienzo.etiquetaNodo': 'Node label:',
  'nivel.vista': '**View: {nombre}.** {desc}. **{n} steps** remain out of {total}. The full process is still saved: switching views loses nothing and does not call the AI again.',
  'nivel.info': '{n} of {total} steps',
  // ---------------------------------------------------------------- Ingestion
  'grabacion.sinTranscripcion': 'There is no transcript.',
  'grabacion.sinSoporte': 'Your browser does not support speech recognition. Use Chrome or Edge. You can also paste the transcript by hand.',
  'grabacion.detenido': 'stopped',
  'grabacion.grabando': 'recording…',
  'fuentes.leyendoDocumentos': 'Reading documents…',
  'fuentes.leyendo': 'Reading {i} of {n}: {nombre}',
  'fuentes.sinTexto': '{nombre}: has no readable text',
  'fuentes.anadidos': '{que} · add more or press {boton}',
  'fuentes.unoAnadido': '1 document added',
  'fuentes.variosAnadidos': '{n} documents added',
  'fuentes.combinarYGenerar': 'Combine and generate',
  'fuentes.noLeidos': '{n} file(s) could not be read:\n\n{lista}',
  'fuentes.tagTexto': 'TEXT',
  'fuentes.caracteres': '{n} chars',
  'fuentes.quitar': 'Remove this source',
  'fuentes.unaLista': '1 source ready',
  'fuentes.variasListas': '{n} sources ready to combine',
  'fuentes.excede': 'Together they add up to {total} characters and the AI reads up to {max}: the end of the longest sources will be cut. Remove the ones that add nothing or keep only the process chapters.',
  'fuentes.combinarN': 'Combine {n} sources and generate',
  'formatos.noCarga': 'Could not load {url} (offline or CDN blocked?)',
  'formatos.noLeido': 'The file could not be read.',
  'ingesta.generando': 'Generating…',
  'ingesta.cancelando': 'Canceling…',
  'flujo.abriendo': 'Opening {nombre}...',
  'flujo.diagramaComoFuente': 'Diagram added as a source',
  'flujo.diagramaImportado': 'Diagram imported',
  'flujo.bpmnImportado': '**BPMN imported from {nombre}:** {n} elements ({tareas} activities, {compuertas} gateways, {eventos} events) and {flujos} flows.',
  'flujo.fuenteAnadida': 'Source added: {nombre}',
  'flujo.sinTexto': 'There is no text to interpret. Load a file or paste the process text.',
  'flujo.interpretandoN': 'Interpreting {n} characters with AI... (it can take up to 1 min)',
  'flujo.analizandoN': 'Analyzing {n} characters...',
  'flujo.participantes': 'Participants detected: {n}. Defining roles...',
  'flujo.interpretando': 'Interpreting with AI...',
  'flujo.generadoIa': 'Process generated with AI',
  'flujo.interpretadoIa': '**Process interpreted with AI from {etiqueta}.** {n} elements with roles, systems and decisions. Review the diagram and complete the **Sheet** tab; then export to **Process Sheet**.',
  'flujo.excedia': '\n\nNote: the document exceeded {k}K characters, so I interpreted the first part. If the end of the process is missing, paste that section and generate again.',
  'flujo.generado': 'Process generated',
  'flujo.basico': '**Process generated in basic mode (no AI)** from {etiqueta}. The activities were extracted by keywords: review roles and decisions. To interpret it with Claude, enter the team code in AI settings (✨) and generate again.',
  'flujo.cancelado': 'Canceled.',
  'flujo.consumio': '{error}\n\nThis run still used {coste} at list price.',
  'flujo.noSePudo': 'Could not complete:\n\n{error}',
  'flujo.cargandoPdf': 'Loading the PDF reader (first time only)…',
  'participantes.intervenciones': '{n} contributions',
  'participantes.queRol': 'What is their role?',
  'participantes.intro': 'I detected <b>{n} person(s)</b> in the transcript. Enter each one’s <b>role</b>: the AI will use the role (not the name) as the flow <b>lane</b>, which is the right way to model a process.',
  'participantes.enBlanco': 'Leave blank anyone who does not take part in the process (e.g. the consultant facilitating the meeting): they will be skipped.',
  'participantes.titulo': '👥 Who is who in the meeting?',
  'participantes.usar': 'Use these roles',
  'participantes.omitir': 'Skip',
  'basico.sinActividades': 'I could not extract activities from the text. Try separating them with periods or bullets.',
  'basico.construido': 'I built the flowchart from the source **{fuente}**.\n\nI detected **{n} activities** (+ start/end).\nPatterns applied: activities with infinitive/imperative verbs, decision gateways from conditionals ("si", "cuando", "en caso").\n\nReview, adjust labels and fill in the owners. When you are done, ask me: *"detect pains"* or *"suggest KPIs"*.',
  'basico.recortado': '\n\n⚠️ **The document was very long** ({total} activities detected). I kept the first {n} so the diagram stays readable.\n\n**Recommendation:** set up the **AI (⚙ in the header)** — it interprets the whole document and builds the real flow with roles and decisions, instead of this keyword extraction.',
  // ---------------------------------------------------------------- AI
  'ia.interpretando': '⏳ Interpreting with AI… (it can take a few seconds)',
  'ia.recibiendo': 'Receiving the process from the AI… {n} characters',
  'ia.sinActividades': 'The AI did not return a process with activities.',
  'ia.coste': '\n\nCost of this run: **{usd}** ({entrada} input tokens and {salida} output tokens, {modelo} list price).',
  'ia.sinProceso': 'There is no process to analyze.',
  'ia.analisisFallido': '**The analysis could not be completed:** {error}',
  'tareas.analizando': '_{tarea}: analyzing the process with AI…_',
  'tareas.reintentar': '_You can try again or use basic mode._',
  'painsIa.sinIa': 'The in-depth pain point analysis uses AI (Claude). You have not set up your API key yet. Open AI settings?',
  'painsIa.analizando': '_Analyzing the process for pain points..._',
  'painsIa.detectados': '**{n} pain point(s) detected in the flow** (with evidence from the process itself):',
  'painsIa.puntaje': '  _(sev {sev} x freq {frec} = **{total}**)_',
  'painsIa.evidencia': '  - Evidence: {texto}',
  'painsIa.impacto': '  - Impact: {texto}',
  'painsIa.hipotesis': '**Industry hypotheses - NOT detected in this flow, to validate with the client:**',
  'painsIa.donde': '   - Where to look: {texto}',
  'painsIa.senal': '   - How to confirm it: {texto}',
  'painsIa.noAgregadas': '_These were NOT added to the diagram: they are questions for the mapping interviews, not findings._',
  'codigo.intro': 'ProcessIQ interprets the document with <b>AI (Claude)</b> using the team key. Enter the <b>access code</b> you got from whoever administers the tool: it is stored only in this browser and you will not be asked again.',
  'codigo.etiqueta': 'Team access code',
  'codigo.sinCodigo': 'Without a code you can continue in <b>basic mode</b>: it extracts activities by keywords, without AI.',
  'codigo.titulo': 'Interpret with AI',
  'codigo.usarIa': 'Use AI',
  'codigo.modoBasico': 'Basic mode',
  'profundidad.intro': 'The process is always generated <b>in full</b>. This sets how closely the AI looks at it and which view it opens in; you can switch views at any time with the <b>level of detail</b> selector, without generating again.',
  'profundidad.ejecutivo': 'Milestones and decisions. For a committee or SteerCo.',
  'profundidad.actividad': 'What each role does from start to finish. The usual balance.',
  'profundidad.detalle': 'Every operational step. For a procedures manual or automation.',
  'profundidad.modelo': 'AI model',
  'profundidad.opus': 'Highest interpretation quality. For long or ambiguous procedures, or ones with many decisions.',
  'profundidad.sonnet': 'Faster and 2.5 times cheaper per token. Usually enough for clear, well-structured texts.',
  'profundidad.tituloModelo': 'Level of detail and model',
  'profundidad.titulo': 'Mapping level of detail',
  'profundidad.estimado': 'Estimate: {min} – {max}',
  'profundidad.costeEstimado': 'Estimated cost of this run: <b>{min} – {max}</b>',
  'profundidad.costeDetalle': 'At most {tope}, if the AI uses the whole response ({tokens} tokens). {modelo} at list price: US$ {entrada} per million input tokens and US$ {salida} per million output tokens; ~{tokensEntrada} input tokens.',
  'profundidad.ajustadoUna': 'Range adjusted with {n} real run at this level in this browser.',
  'profundidad.ajustadoVarias': 'Range adjusted with {n} real runs at this level in this browser.',
  'profundidad.inicial': 'Initial estimate: it gets more accurate with your real runs.',
  'profundidad.generar': 'Generate',
  'ajustesIa.proyecto': 'Project AI',
  'ajustesIa.entendido': 'Got it',
  'ajustesIa.intro': 'ProcessIQ uses the <b>Anthropic API (Claude)</b>. In <b>team mode</b> the key lives in the MBC proxy and this browser only stores your access code. With <b>your own API key</b>, the key is stored only in this browser and goes straight to Anthropic.',
  'ajustesIa.modo': 'Mode',
  'ajustesIa.modoEquipo': 'Team key (MBC proxy)',
  'ajustesIa.modoPropia': 'My own API key',
  'ajustesIa.direccion': 'Proxy address',
  'ajustesIa.codigoPista': 'Whoever administers ProcessIQ gives you the code. The Anthropic key lives in the proxy: your browser never sees it.',
  'ajustesIa.apiKey': 'Anthropic API key',
  'ajustesIa.apiKeyPista': 'You get it at <b>console.anthropic.com → API Keys</b>. It starts with <code>sk-ant-</code>.',
  'ajustesIa.modelo': 'Model',
  'ajustesIa.probar': 'Test connection',
  'ajustesIa.byok': '⚠️ BYOK mode: use it for internal work or demos. For a shared public link, a proxy with the key on the server is better.',
  'ajustesIa.titulo': '⚙ AI settings (Claude)',
  'ajustesIa.guardar': 'Save',
  'ajustesIa.probando': '⏳ Testing…',
  'ajustesIa.correcta': '✓ Connection OK',
  'ajustesIa.respondio': '✓ It replied: {texto}',
  'modoIa.servidor': 'It will be interpreted with <b>AI on the server</b>: it rebuilds activities, roles and decisions, and the result is saved in the project.',
  'modoIa.servidorNo': 'Server-side AI is not available right now; <b>basic mode</b> (keywords) will be used.',
  'modoIa.modelo': 'It will be interpreted with <b>AI ({modelo})</b>: it rebuilds activities, roles and decisions.',
  'modoIa.equipo': 'It will be interpreted with <b>AI (Claude)</b> using the team key. When you generate, we will ask for the access code; without it, <b>basic mode</b> (keywords) will be used.',
  // ---------------------------------------------------------------- Copilot
  'copiloto.saludo': 'Hi! I am your **ProcessIQ** copilot.\n\nI am here to help you map, diagnose and redesign processes faster.\nStart by filling in the **name, industry and macroprocess** above, then use the quick actions or ask me something in plain language.\n\nExample: *"Generate the complaints management process for a Peruvian retail bank."*',
  'copiloto.autor': 'ProcessIQ · AI',
  'copiloto.tareaIa': '{tarea} (AI).',
  'copiloto.generarTitulo': 'Generate process from a description',
  'copiloto.generarEjemplo': 'Describe the process to map...',
  'copiloto.generarPedido': 'Generate process: {desc}',
  'copiloto.pedido.detectPains': 'Detect pain points in the current diagram.',
  'copiloto.pedido.suggestKpis': 'Suggest applicable KPIs.',
  'copiloto.pedido.proposeTobe': 'Propose a to-be redesign.',
  'copiloto.pedido.raci': 'Generate the RACI matrix.',
  'copiloto.pedido.sipoc': 'Generate the process SIPOC.',
  'copiloto.pedido.impactEffort': 'Generate the impact–effort matrix.',
  'copiloto.pedido.whatif': 'Compare What-If scenarios.',
  'copiloto.pedido.automation': 'Find automation opportunities.',
  'copiloto.pedido.bottleneck': 'Identify the bottleneck and critical path.',
  'copiloto.pedido.variants': 'Analyze process variants.',
  'copiloto.pedido.valueMap': 'Show the Lean value map (VA/NVA).',
  'copiloto.pedido.backlog': 'Generate the initiative backlog.',
  'copiloto.pedido.execSummary': 'Executive summary of the diagnosis.',
  'copiloto.pedido.mergeGateways': 'Insert merging gateways.',
  'copiloto.pedido.aiPains': 'In-depth pain point analysis (AI).',
  'copiloto.pedido.autofit': 'Auto-fit the diagram.',
  'copiloto.pedido.relayout': 'Rearrange the diagram.',
  'copiloto.reorganizado': '**Diagram rearranged.** {disposicion} Lanes ordered to minimize crossings, with rework loops routed through the bottom corridor.',
  'copiloto.envolvente': 'Wrap mode on: {bandas} bands of up to {columnas} columns (avoids a mile-long diagram).',
  'copiloto.unaBanda': 'Single-band layout.',
  // ---------------------------------------------------------------- Export, BPMN and validations
  'exportar.jsonInvalido': 'Invalid JSON file.',
  'exportar.sinProcesoFicha': 'There is no process to generate the sheet from.',
  'exportar.fichaTitulo': '📋 Process Sheet · preview (in Spanish)',
  'exportar.descargarWord': '⬇️ Download Word',
  'exportar.sinPptx': 'The PPTX library did not load (are you offline?). Connect to the internet or export to SVG/PNG.',
  'exportar.sinProceso': 'There is no process to export.',
  'exportar.sinProcesoWord': 'There is no process to document.',
  'bpmn.carriles': 'Lanes: {lista}.',
  'bpmn.unSubproceso': 'One subprocess with content',
  'bpmn.subprocesos': '{n} subprocesses with content',
  'bpmn.subprocesosNiveles': ': shown expanded at the Detail level and collapsed at Activity and Executive.',
  'lint.vacio': 'Generate or draw a process to validate it.',
  'lint.cero': 'Zero issues! The process meets the MBB playbook.',
  'lint.scoreSin': 'MBB score · no issues',
  'lint.score': 'MBB score',
  'lint.crit': '{n} crit',
  'lint.alto': '{n} high',
  'lint.medio': '{n} medium',
  'lint.bajo': '{n} low',
  'lint.detectado': '{n} issue found',
  'lint.detectados': '{n} issues found',
  'lint.irAlNodo': '→ click to go to the node',
  // ---------------------------------------------------------------- Simulator, examples, auto-fit and mining
  'sim.sinActividades': 'I need activities in the diagram first.',
  'sim.wizardIntro': 'Capture time and volume for each activity. Green rows already have data, yellow ones are empty. Tab/Enter to move on quickly.',
  'sim.colActividad': 'Activity',
  'sim.colResponsable': 'Owner',
  'sim.colTiempo': 'Time (min)',
  'sim.colVolumen': 'Volume/month',
  'sim.ejemplo': 'e.g. {n}',
  'sim.wizardTitulo': '⚡ Time capture wizard · {n} activities',
  'sim.capturados': 'I captured times/volumes for {n} activities. The simulation was updated automatically.',
  'sim.sinProceso': 'No process. Generate or draw one first.',
  'sim.sinDatos': '⚠ No activity has time and volume. Fill in those fields in Props.',
  'sim.conDatos': 'Activities with data',
  'sim.esfuerzo': 'Total effort / month',
  'sim.fteActual': 'Current FTE',
  'sim.leadTime': 'Flow lead time (sum)',
  'sim.costoMensual': 'Monthly operating cost',
  'sim.fteToBe': 'To-be FTE (-{pct}%)',
  'sim.ahorro': 'Estimated annual savings',
  'sim.liberados': '{n} FTE freed up',
  'ejemplos.intro': 'Choose a preloaded example process (with pain points, KPIs and simulation) to explore the capabilities. The examples are in Spanish.',
  'ejemplos.titulo': 'Example processes',
  'autoajuste.sinDiagrama': 'There is no diagram to fit.',
  'autoajuste.titulo': '**Diagram auto-fitted.**\n\n',
  'autoajuste.limpio': 'No arrows over boxes and no crossings. Layout: {disposicion}, {carriles} lanes.\n\n',
  'autoajuste.bandas': '{bandas} bands of up to {columnas} columns',
  'autoajuste.unaBanda': 'a single band',
  'autoajuste.defectos': '**{sobreCajas} arrow(s) over boxes** and **{cruces} crossing(s)** remain; it is the best of {variantes} layouts tried. It is usually caused by several branches pointing to the same end node.\n\n',
  'autoajuste.tamano': 'Size: {ancho} × {alto} px. Press **undo** (Ctrl+Z) if you prefer the previous layout.',
  'mineria.filas': '\n({n} rows in total)',
  'mineria.ninguna': '(none)',
  'mineria.completado': '**Process discovery completed** from the event log.\n\n• **{casos} cases** analyzed\n• **{actividades} unique activities** detected\n• **{transiciones} transitions** discovered (showing the most frequent)\n• Top start: *{inicio}*\n• Top end: *{fin}*\n\nThe number on each connection = observed frequency. High-frequency activities that reappear point to **rework** (a candidate pain point).',
  // ---------------------------------------------------------------- As-Is / To-Be views
  'vistas.indicadorToBe': 'TO-BE · REDESIGN',
  'vistas.sinAsIs': 'Generate or draw an As-Is process first.',
  'vistas.nadaQueClonar': 'There is no As-Is to clone.',
  'vistas.clonado': 'I cloned the As-Is into the To-Be. You can now edit the flow without affecting the original.\n\n**Quick redesign suggestions:**\n• Remove duplicate control nodes.\n• Mark manual activities as **system** (automation).\n• Merge handoffs into a cross-functional cell.\n• Move decisions into codified rules (DMN).\n\nWhen you are done, export to PPTX — I will include a side-by-side comparison slide.',
  'tobe.operativo.label': 'Operational — Quick wins',
  'tobe.operativo.desc': 'Automates repetitive manual tasks, removes rework. Low-risk changes, 0-3 months.',
  'tobe.tactico.label': 'Tactical — Flow redesign',
  'tobe.tactico.desc': 'Removes handoffs, parallelizes, consolidates duplicate controls. 3-9 months.',
  'tobe.estrategico.label': 'Strategic — Reimagine',
  'tobe.estrategico.desc': 'Digital self-service, removes non-value-adding steps, rethinks the process end to end. 9-18 months.',
  'tobe.intro': 'ProcessIQ clones the As-Is and applies redesign levers for the chosen <strong>level</strong>. You can then edit the result by hand.',
  'tobe.nivel': 'Transformation level',
  'tobe.cambios': 'Specific changes (optional)',
  'tobe.cambiosEjemplo': 'E.g. \'Remove the manual validation in step 3\', \'Add self-service at data capture\'…',
  'tobe.titulo': '✨ Transform to To-Be by level',
  'tobe.sinAsIs': 'There is no As-Is to transform.',
  'tobe.automatizada': 'Automated: "{etiqueta}" → {tipo}',
  'tobe.digitalizada': 'Digitized: "{etiqueta}" → User Task (system)',
  'tobe.decision': 'Decision "{etiqueta}" → codified rule (DMN)',
  'tobe.selfService': 'Self-service: "{etiqueta}"',
  'tobe.ia': 'AI-assisted: "{etiqueta}" → Script/AI Task',
  'tobe.manuales': 'Manual changes requested: {cambios}',
  'tobe.generado': '**To-Be generated · {nivel} level**\n\n{desc}\n\n**{n} change(s) applied:**\n',
  'tobe.sinCambios': '• No automatic changes — edit by hand.',
  'tobe.yMas': '\n• …and {n} more.',
  'tobe.editaManual': '\n\nEdit any node by hand in Props. Export to PPTX for the As-Is vs To-Be comparison.',
  // ---------------------------------------------------------------- Panels: pain points, properties and KPIs
  'pains.describe': 'Describe the pain point.',
  'pains.selecciona': 'Select a node to capture its pain points.',
  'pains.sinPains': 'No pain points captured yet.',
  'pains.meta': 'Sev {sev} · Freq {frec} · Score {score}',
  'pains.eliminar': 'Delete',
  'props.larga': 'Too long ({car} chars, {pal} words). Max 50 chars / 8 words — consider splitting it.',
  'props.fueraCatalogo': '"{verbo}" is not in the MBB catalog. Prefer: registrar, validar, aprobar, escalar, notificar, calcular… (activities are written in Spanish).',
  'props.namingOk': 'Naming OK · allowed verb + suitable length',
  'kpis.sinCoincidencias': 'No matches.',
  'kpis.benchmark': 'Benchmark: {valor}',
  'kpis.valorActual': 'Current value:',
  'kpis.gap': 'Gap:',
  'kpis.benchmarkSectorial': 'Industry benchmark: {valor}',
  'kpis.valorCliente': 'Client’s current value',
  'kpis.valorEjemplo': 'e.g. 6.2',
  'kpis.gapBenchmark': 'Gap vs benchmark (calculated or manual)',
  'kpis.gapEjemplo': 'e.g. -2.2 pp (above the benchmark)',
  'kpis.fuente': 'Data source',
  'kpis.fuenteEjemplo': 'e.g. SBS dashboard, internal BO report 04/2026',
  'kpis.capturadosPista': 'Captured KPIs appear on the PPTX slide with their gap. The gap is calculated automatically if the value and the benchmark are numeric.',
  'kpis.capturarTitulo': 'Capture current value · KPI',
  'kpis.capturado': 'KPI captured: **{kpi}** = {valor} (gap {gap}). It will be included in the PPTX KPI slide.',
  // ---------------------------------------------------------------- Copilot without AI: commands and rule-based answers
  'comando.noActividad': 'I could not find the activity "{nombre}". Check the name.',
  'comando.agregadoDespues': '✅ I added "{nuevo}" after "{ref}".',
  'comando.agregadoAntes': '✅ I added "{nuevo}" before "{ref}".',
  'comando.noEliminar': 'I could not find "{nombre}" to delete.',
  'comando.eliminado': '✅ I deleted "{nombre}" and reconnected the flow.',
  'comando.noRenombrar': 'I could not find "{nombre}" to rename.',
  'comando.renombrado': '✅ I renamed "{antes}" → "{ahora}".',
  'comando.noEncontre': 'I could not find "{nombre}".',
  'comando.conectado': '✅ I connected "{a}" → "{b}".',
  'comando.yaExiste': 'That connection already exists.',
  'comando.marcada': '✅ "{nombre}" marked as {tipo}.',
  'heur.generado': 'I generated an as-is process with **{n} activities** based on APQC PCF patterns + the MBB playbook.\n\nImmediate suggestions:\n• Fill in the **owners** and **supporting systems** for each activity.\n• Capture **pain points** (handoffs, waits, rework) — they are the input for the diagnosis.\n• Check the **KPIs** tab to link industry indicators.\n\nShall I detect typical industry pain points?',
  'heur.sinDiagrama': 'There is no diagram yet. Generate or draw a process first.',
  'heur.diagnostico': '**Automatic as-is diagnosis**\n\n• **{handoffs} handoff(s)** detected between different roles. Each handoff adds ~10-15% lead time and a risk of information loss.\n• **{decisiones} decision point(s)**. Without documented criteria, they are a source of variability and inconsistency.\n• **{manual} activity(ies) without a supporting system** — candidates for automation (RPA / workflow).\n\n**Typical pain points in the {industria} industry:**\n',
  'heur.defineIndustria': '(set the industry)',
  'heur.banca': '• Rework due to incomplete client documentation.\n• Response times that vary by channel.\n• Duplicate manual validations between frontline and back office.',
  'heur.retail': '• Stock-outs due to poor store–DC synchronization.\n• Returns without financial traceability.\n• Promotions executed out of step across channels.',
  'heur.manufactura': '• Unplanned stoppages due to reactive maintenance.\n• Oversized work-in-process inventory.\n• Quality detected at the end of the line, not at the station.',
  'heur.publico': '• Procedures with multiple service windows (no one-stop shop).\n• Paper documentation that duplicates digital records.\n• Statutory (TUPA) deadlines missed due to handoffs between departments.',
  'heur.sinIndustria': '• Set the process industry for specific suggestions.',
  'heur.kpis': '**Recommended KPIs** for {para}{macro}:\n\n',
  'heur.tuProceso': 'your process',
  'heur.kpisPie': '\nCheck the **KPIs** tab to see the full library and click each one to add it to the diagnosis.',
  'heur.sinAsIs': 'I need an as-is diagram to propose the to-be.',
  'heur.tobe': '**Redesign proposal (to-be)**\n\nAs-is reading: {n} activities, {handoffs} handoffs between roles, {manual} without a system, {pains} pain points captured.\n\n**Suggested levers:**\n1. **RPA automation** in the {manual} activities without a supporting system → estimated savings of 0.3-0.5 FTE per high-volume activity.\n2. **Remove handoffs** with a cross-functional cell or an orchestrated workflow → 20-30% lower lead time.\n3. **Self-service / digital channel** in data-capture activities → 40-60% fewer errors at the source.\n4. **Codified decision rules** (DMN / rules engine) at the gateways → consistency and traceability.\n5. **Real-time KPIs** on a single dashboard → monthly instead of quarterly improvement cycles.\n\n**Estimated benefits** (industry reference range):\n• Lead time: -35% to -50%\n• FTE freed up: 15-25% of current headcount\n• Quality (errors): -60%\n• CSAT/NPS: +10 to +20 points\n\nTell me "draw the to-be" if you want me to generate the optimized version on a new canvas.',
  'heur.nombreVacio': '[Process name]',
  'heur.industriaVacia': '[Industry]',
  'heur.macroVacio': '[Macroprocess]',
  'heur.resumen': '**EXECUTIVE SUMMARY — PROCESS DIAGNOSIS**\n\n**Process:** {nombre}\n**Industry / Macroprocess:** {industria} · {macro}\n\n**Key findings:**\n• The process comprises {n} activities with {handoffs} handoffs between roles.\n• {pains} pain points were identified ({criticos} critical, severity ≥ 4).\n• There is an automation opportunity in activities without a supporting system.\n\n**Prioritized recommendations:**\n1. Quick wins (0-3 months): standardize decision criteria + remove duplicate controls.\n2. Medium term (3-9 months): RPA/IDP automation of high-volume manual activities.\n3. Structural (9-18 months): organizational redesign toward cross-functional cells + a real-time dashboard.\n\n**Estimated impact:**\nLead time -40%, 15-25% of FTE freed up, double-digit CSAT/NPS improvement.\n\n**Suggested next step:**\nValidate the findings with the sponsor, prioritize opportunities in the impact–effort matrix, and build the business case.',
  'heur.hola': 'Hi! Which process can I help you with today?',
  'heur.interpretando': 'Interpreting your description with AI…',
  'heur.generico': 'Got it. Without AI the copilot works with local templates — with Claude connected, it answers in the context of your diagram, industry and the area’s previous deliverables.\n\nTry the quick actions above: generate, detect pain points, suggest KPIs, to-be, or executive summary.',
  'convergencia.ninguna': 'I found no merge points that need a closing gateway: this process’s branches end in different end events or already merge at a gateway.',
  'convergencia.insertadas': '**{n} merging gateway(s) inserted.**\n\nWhere several branches came back together at an activity, the closing gateway (✕) is now drawn — this is what rigorous BPMN requires and what committees expect to see.\n\nNodes: {antes} → {despues}. If you prefer the implicit merge, use **undo** (Ctrl+Z).',
  // ---------------------------------------------------------------- Advanced analytics, RACI, SIPOC and impact–effort
  'analitica.sinActividades': 'There are no activities to analyze.',
  'cuello.sinDatos': 'Capture **time** and **volume** for the activities (Props tab or the simulator wizard) to find the bottleneck.',
  'cuello.titulo': '**🔴 Bottleneck and critical path analysis**\n\n',
  'cuello.cuello': '**Bottleneck:** "{etiqueta}" — workload of **{horas} h/month** ({min} min × {casos} cases). It is the activity that consumes the most capacity; any improvement here has the greatest impact on throughput.\n\n',
  'cuello.top': '**Top 3 by workload:**\n',
  'cuello.topFila': '{i}. {etiqueta} — {horas} h/month',
  'cuello.ruta': '**Critical path** ({min} min of lead time): {ruta}.\n\n',
  'cuello.recomendacion': 'Recommendation: tackle the bottleneck first (automate, parallelize or redistribute the workload) and shorten the critical path by removing waits/handoffs.',
  'autom.nada': 'I did not find clearly automatable tasks. Make sure you have manual activities with time and volume captured.',
  'autom.intro': '{n} activity(ies) with automation potential, sorted by estimated annual savings.',
  'autom.tecnologia': 'Technology',
  'autom.ahorroAnio': 'Savings/year',
  'autom.esfuerzo': 'Effort',
  'autom.potencial': '<b>Total potential:</b> {fte} FTE freed up · <b style="color:#1E7E34">{ahorro}/year</b>',
  'autom.titulo': '🤖 Automation opportunities',
  'autom.mensaje': 'I found **{n} automation opportunities** with potential of **{fte} FTE** and **{ahorro}/year**. Top candidate: "{etiqueta}" ({tecnologia}). Use it to prioritize the RPA/IDP/AI roadmap.',
  'variantes.sinVariantes': 'There are no variants to analyze. Ingest a **CSV event log** (📥 Ingest → Event Log) — variants are computed from the real cases.',
  'variantes.intro': '<b>{n} variants</b> in {total} cases. Variant #1 is the "happy path"; the others are exceptions/rework — a direct source of pain points.',
  'variantes.secuencia': 'Sequence',
  'variantes.pasos': 'Steps',
  'variantes.casos': 'Cases',
  'variantes.resumen': '<b>Happy path:</b> {pct}% of cases ({n}). <b>Exceptions:</b> {excepciones} variants cover the remaining {resto}% — review them to standardize and reduce rework.',
  'variantes.titulo': '🔀 Variant analysis',
  'variantes.mensaje': '**{n} variants** detected. The happy path covers {pct}% of cases; the rest are exceptions (candidates for standardization). The more variants, the more variability and less discipline in the process.',
  'valor.sinActividades': 'There are no activities to map.',
  'valor.desactivado': 'Value map turned off — back to colors by task type.',
  'valor.activado': '**♻ Lean value map on** (green=VA · yellow=BVA · red=NVA · gray=unclassified)\n\n**Workload split by value:**\n• 🟢 Value Added (VA): **{va}%**\n• 🟡 Necessary non-value (BVA): **{bva}%**\n• 🔴 Waste (NVA): **{nva}%** — {n} activity(ies)\n',
  'valor.sinClasificar': '• ⚪ Unclassified: {pct}% ({n} activities — assign VA/BVA/NVA in Props)\n',
  'valor.diagnostico': '\n**Lean diagnosis:** {texto}\n\nPress again to turn the map off.',
  'valor.alto': 'High waste — prioritize removing/automating the NVA activities.',
  'valor.moderado': 'Moderate waste — review the NVA activities.',
  'valor.nada': 'No classified waste. Assign VA/BVA/NVA for the Lean analysis.',
  'backlog.sinInsumos': 'There is no input for the backlog. Capture pain points, have manual activities or KPIs with a gap.',
  'backlog.fuenteAutomatizacion': 'Automation',
  'backlog.intro': '{n} initiatives consolidated from pain points, automation and KPI gaps, prioritized by impact/effort ratio.',
  'backlog.fuente': 'Source',
  'backlog.iniciativa': 'Initiative',
  'backlog.esf': 'Eff',
  'backlog.horizonte': 'Horizon',
  'backlog.beneficio': 'Benefit',
  'backlog.exportar': '⤓ Export backlog (CSV)',
  'backlog.titulo': '📋 Initiative backlog · {n}',
  'backlog.mensaje': '**Backlog of {n} initiatives** generated and prioritized. {rapidos} quick wins (0-3m). Sources: {pains} pain points, {autom} automation, {kpi} KPI. Use it as the transformation roadmap.',
  'whatif.sinProceso': 'Generate a process first.',
  'whatif.sinDatos': '⚠ No activity has time and volume. Capture data (simulator wizard) so the comparison has figures.',
  'whatif.intro': 'Select the levers to build a <b>To-Be scenario</b> and compare it against the current As-Is.',
  'whatif.reduccion': 'Additional expected lead time reduction (%)',
  'whatif.titulo': '🔬 What-If scenario comparison',
  'whatif.aplicadas': '{n} lever(s) applied. As-Is vs To-Be scenario comparison:',
  'whatif.metrica': 'Metric',
  'whatif.leadTime': 'Lead time (min)',
  'whatif.costoMensual': 'Monthly cost',
  'whatif.ahorro': 'Scenario annual savings',
  'whatif.liberados': '{fte} FTE freed up · lead time −{pct}%',
  'whatif.resultado': '🔬 What-If result',
  'whatif.mensaje': '**What-If scenario:** with {n} lever(s), the process goes from {de} to {a} FTE (savings {ahorro}/year) and cuts lead time by ~{pct}%. Compare several scenarios to choose the one with the best impact/effort ratio.',
  'raci.sinActividades': 'I need activities in the diagram to generate the RACI.',
  'raci.r': 'R · Responsible',
  'raci.c': 'C · Consulted',
  'raci.i': 'I · Informed',
  'raci.pista': 'R=Responsible · A=Accountable · C=Consulted · I=Informed. The matrix will be exported to the PPTX automatically.',
  'raci.titulo': 'RACI matrix · {nombre}',
  'raci.proceso': 'Process',
  'raci.guardada': 'RACI matrix saved with {n} activities × {roles} roles. It will be included in the next PPTX export.',
  'sipoc.sinProceso': 'Generate or draw a process first.',
  'sipoc.pista': 'SIPOC prefilled from the diagram (roles, data nodes). Edit it freely. It will be included in the PPTX.',
  'sipoc.guardado': 'SIPOC saved. It will be exported with the PPTX.',
  // RACI and SIPOC with AI as editable matrices (divergence D11)
  'matriz.armando': '_{tarea}: building the editable matrix with AI…_',
  'matriz.alInforme': '_The editable matrix could not be built ({error}). Asking for the text report instead._',
  'matriz.sinResultado': 'the server did not return the matrix',
  'matriz.guardar': 'Save changes',
  'raci.generadaIa': 'RACI matrix proposed by the AI with {n} activities × {roles} roles. It is already in the process and will be included in the PPTX: review it and adjust whatever is needed.',
  'raci.pistaIa': 'AI proposal: review each cell (a single A per activity; R is who performs it). R=Responsible · A=Accountable · C=Consulted · I=Informed. The matrix will be exported to the PPTX automatically.',
  'sipoc.generadoIa': 'SIPOC proposed by the AI. It is already in the process and will be included in the PPTX: review it and adjust whatever is needed.',
  'sipoc.pistaIa': 'SIPOC proposed by the AI from the process. Edit it freely. It will be included in the PPTX.',
  'impacto.sinPains': 'Capture pain points first (select a node → Pains tab).',
  'impacto.estrategicos': 'STRATEGIC PROJECTS',
  'impacto.reconsiderar': 'RECONSIDER',
  'impacto.esfuerzo': '→ Effort',
  'impacto.impacto': '→ Impact',
  'impacto.leyenda': 'Legend',
  'impacto.sevFrec': '(sev {sev} · freq {frec})',
  'impacto.titulo': 'Impact · Effort matrix · {n} pain points',
  'impacto.lista': 'Impact–effort matrix ready with {n} opportunities. Quick wins (high impact / low effort) = candidates for the 0-3 month phase.',
  // ---------------------------------------------------------------- Platform: a project process
  'proyecto.sinCatalogos': 'The organization’s catalogs could not be loaded: the built-in ones are used.',
  'proyecto.laVersion': 'v{n}',
  'proyecto.procesoVacio': 'the empty process',
  'proyecto.tienesCambios': 'You have unsaved changes',
  'proyecto.cambiosSinGuardar': 'Unsaved changes',
  'proyecto.borradorOtra': 'This browser has changes to {version} of this process that were not saved to the project (last change: {fecha}). If you open {abres}, they will be lost.',
  'proyecto.estaVersion': 'this version',
  'proyecto.borradorMisma': 'This browser has changes to this version that were not saved to the project (last change: {fecha}).',
  'proyecto.seguirConMios': 'Keep my changes to {version}',
  'proyecto.recuperar': 'Recover my changes',
  'proyecto.descartarlos': 'Discard them',
  'proyecto.noEncontrado': 'That process was not found or you do not have access to it.',
  'proyecto.noAbierto': 'The process could not be opened.',
  'proyecto.archivado': 'The project is archived: you can view the process, but not save changes.',
  'proyecto.rolSinGuardar': 'Your project role ({rol}) does not allow saving revisions: changes you make here will not be saved to the project.',
  'proyecto.noEsLaUltima': 'You are working on v{base}, but the latest is v{ultima}: the new version will not include the changes in v{ultima}.',
  'proyecto.conErrores': 'The process has errors and cannot be saved:',
  'proyecto.guardadaIa': 'Process generated with AI and saved',
  'proyecto.guardada': 'Saved',
  'proyecto.conflicto': '{que} as v{n}. While you were working, someone saved v{otra}: this version does not include those changes. Review both in the project.',
  'proyecto.guardadaComo': '{que} as v{n} (draft).',
  'proyecto.sesionCaducada': 'Your session expired. Your changes are still saved in this browser: sign in again and press “Save revision” again.',
  'proyecto.entrar': 'Sign in',
  'proyecto.noGuardado': 'Could not save.',
  'proyecto.iaSoloLectura': 'Your role or the project status does not allow using AI here.',
  'proyecto.mensajeIa': 'Process generated with AI from {etiqueta}',
  'proyecto.pendienteTitulo': 'There is an unsaved process generated with AI',
  'proyecto.pendienteTexto': 'On {fecha} the AI generated this process from “{etiqueta}”, but it was never saved to the project (the tab was closed first). Shall we draw it now? It will be saved as a new version; the earlier ones do not change.',
  'proyecto.dibujarlo': 'Draw and save it',
  'proyecto.descartarlo': 'Discard it',
  'barra.aria': 'Project process',
  'barra.volver': 'Back to the project',
  'barra.guardarTitulo': 'Creates a new version in the project (Ctrl+S)',
  'barra.guardar': 'Save revision',
  'barra.noAbierto': 'The process could not be opened',
  'barra.abriendo': 'Opening the process…',
  'barra.proyecto': 'Project',
  'barra.laUltima': 'the latest is v{n}',
  'barra.sinRevisiones': 'no revisions yet',
  'barra.tuRol': 'your role: {rol}',
  'barra.soloLectura': 'read-only',
  'barra.guardando': 'Saving…',
  'barra.cerrarAviso': 'Close notice',
  'guardar.texto': 'This will create v{n} of “{nombre}”, as a draft. Earlier versions do not change.',
  'guardar.campo': 'What did you change? (optional, the team will see it)',
  'catalogos.pptxCliente': 'PPTX · {nombre} client',
  'catalogos.temaOrganizacion': 'organization theme',
  'colab.dondeAmbos': 'in the editor and on the process page',
  'colab.dondeEditor': 'in the editor',
  'colab.dondeShell': 'on the process page',
  'colab.dos': '{a} and {b}',
  'colab.varios': '{a} and {n} more',
  'colab.guardasteOtra': 'You saved v{n} from another tab',
  'colab.guardo': '{autor} saved v{n}',
  'colab.tusCambiosSobre': 'You have unsaved changes to v{n}: if you load the new version, they will be lost.',
  'colab.tusCambios': 'You have unsaved changes: if you load the new version, they will be lost.',
  'colab.cargarNueva': 'Load the new version',
  'colab.seguirMia': 'Keep mine',
  'colab.perderasSobre': 'If you load v{n}, the changes you made to v{base} will be lost.',
  'colab.perderas': 'If you load v{n}, the changes you made will be lost.',
  'colab.conservarlos': 'If you would rather keep them, continue with yours and save it as a new version: it will be flagged as a conflict and you can review both in the project.',
  'colab.cargarYDescartar': 'Load v{n} and discard my changes',
  'colab.tambien': 'Also have this process open',
  'colab.editandoEn': '{nombre}: editing {donde}',
  'colab.viendoEn': '{nombre}: viewing {donde}',
  'colab.versiones': ' ({lista})',
  'colab.versionAnterior': 'v{n}, earlier version',
  'colab.estaEditando': '{quien} is editing',
  'colab.estanEditando': '{quien} are editing',
  'colab.estaEditandoTambien': '{quien} is also editing',
  'colab.estanEditandoTambien': '{quien} are also editing',
  'colab.sinBloqueo': 'Nothing is locked: if both of you save, the second version will be flagged as a conflict and both can be reviewed in the project.',
  'iaRemota.sustitucion': 'The AI server does not allow {pedido}: this generation uses {usado}. The allowed models are decided by whoever administers ProcessIQ.',
  'iaRemota.reintentando': 'Retrying on the server… ({error})',
  'iaRemota.enCola': 'Queued on the AI server…',
  'iaRemota.interpretando': 'Interpreting with AI on the server… (it can take a few minutes)',
  'iaRemota.fallida': 'The AI could not complete the task.',
  'iaRemota.sinConexion': 'The connection to the server was lost. The AI is still working: open the process again to get the result.',
  'iaRemota.sinConfigurar': 'Server-side AI is not configured yet (the Anthropic key is missing).',
  'iaRemota.presupuesto': 'The organization’s monthly AI budget has been reached.',
  'iaRemota.limite': 'You have reached your monthly AI limit.',
  'iaRemota.noDisponible': '{motivo} Basic mode (no AI) is used.',
  'iaRemota.noDisponibleGenerico': 'Server-side AI is not available.',
  'iaRemota.nota': '{pedido} is not allowed on the server: {usado} is used.',
  'iaRemota.ajustesIntro': 'In project processes, AI is managed by the server: the Anthropic key never goes through your browser and every run is logged with its cost. If you close the tab while it generates, the result will be waiting when you open the process again.',
  'iaRemota.estado': 'Status: <b>{estado}</b>',
  'iaRemota.disponible': 'available',
  'iaRemota.modelos': 'Models for generation: {modelos}',
  'iaRemota.analisis': 'Analysis (pain points and copilot): {modelo}',
  'iaRemota.gastoOrg': 'Organization spend this month: <b>{gastado}</b> of {total}',
  'iaRemota.gastoTuyo': 'Your spend this month: <b>{gastado}</b> of {total}',
  // ---------------------------------------------------------------- Platform: guest view
  'invitado.noDisponible': 'This link is no longer available',
  'invitado.noAbierta': 'The revision could not be opened',
  'invitado.caducado': 'It may have expired or been revoked. Ask whoever sent it for a new link.',
  'invitado.reintentarLuego': 'Try again in a few minutes.',
  'invitado.reintentar': 'Retry',
  'invitado.barraAria': 'Shared revision',
  'invitado.abriendo': 'Opening the shared revision…',
  'invitado.version': ' · version {n}',
  'invitado.detalle': 'Read-only · shared with {para} · available until {fecha}',
  'invitado.ficha': 'Process sheet',
  'invitado.comentariosN': 'Comments ({n})',
  'invitado.comentarios': 'Comments',
  'invitado.cerrarComentarios': 'Close comments',
  'invitado.ayuda': 'Write whatever you would like the team to review. To comment on a specific step, click it in the diagram.',
  'invitado.tusComentarios': 'Your comments',
  'invitado.tuNombre': 'Your name',
  'invitado.comentario': 'Comment',
  'invitado.enviar': 'Send comment',
  'invitado.sinComentarios': 'You have not left any comments on this version yet.',
  'invitado.sobre': 'On “{elemento}”',
  'invitado.verEnDiagrama': 'Show in the diagram',
  'invitado.resuelto': 'The team marked it as resolved',
  'invitado.general': 'Comment on the process as a whole',
  'invitado.quitar': 'Remove',
  'invitado.quitarAria': 'Comment on the process as a whole',
  'invitado.pasoGenerado': 'That step was generated when the level of detail changed and is not in the shared version: go back to the initial level to comment on it.',
  'invitado.noEnVista': 'That element is not in the view or level of detail you have open.',
  'invitado.faltaNombre': 'your name',
  'invitado.faltaComentario': 'the comment',
  'invitado.escribe': 'Enter {que}.',
  'invitado.y': ' and ',
  'invitado.enviando': 'Sending…',
  'invitado.enviado': 'Comment sent. The team will see it alongside this version.',
  'invitado.noEnviado': 'The comment could not be sent.',
  // ---------------------------------------------------------------- Common
  'idioma.grupo': 'Language'
};

// =====================================================================
// Textos que vienen de los paquetes (en español) y se muestran en la interfaz.
// En español se usa el texto del paquete tal cual; en inglés, el de estos mapas
// (traducirDe de i18n.js), y si falta, el español.
// =====================================================================

/** Niveles de detalle (NIVELES de @processiq/motor), por id. */
export const NIVELES_EN = {
  1: { nombre: 'Executive', desc: 'One step per actor between decisions' },
  2: { nombre: 'Activity', desc: 'Groups consecutive tasks of the same actor' },
  3: { nombre: 'Detail', desc: 'Every task, as it was mapped' }
};

/** Tareas de IA del copiloto (TAREAS_IA de @processiq/ia), por clave: los mismos del shell. */
export const TAREAS_IA_EN = {
  'suggest-kpis': 'Suggest applicable KPIs',
  'propose-tobe': 'Propose To-Be redesign',
  'raci': 'RACI matrix',
  'impact-effort': 'Impact–effort matrix',
  'automation': 'Automation opportunities',
  'backlog': 'Initiative backlog',
  'exec-summary': 'Executive summary',
  'sipoc': 'SIPOC',
  'bottleneck': 'Bottleneck and critical path'
};

/** Tipos de ejecución (EXECUTION_TYPES de @processiq/dominio), por id: etiqueta y ayuda. */
export const EJECUCION_EN = {
  manual: { label: 'Manual', desc: 'A person without a system. Purely physical/mental work.' },
  system: { label: 'User Task (system)', desc: 'Person + system (workflow). A person works assisted by an application.' },
  automatic: { label: 'Service Task (auto)', desc: 'No human intervention. Batch, trigger, integration.' },
  ai: { label: 'Script/AI Task', desc: 'Assisted by ML/LLM. Copilots, agents, scoring.' },
  email: { label: 'Receive Task (email)', desc: 'Waits for/receives a message (email, incoming form).' },
  send: { label: 'Send Task', desc: 'Sends a message to an external participant (filled envelope).' },
  phone: { label: 'By phone', desc: 'Synchronous voice communication, call center.' },
  document: { label: 'Document-based', desc: 'Wet signature, paper, stamps, manual filing.' },
  rpa: { label: 'RPA / Bot', desc: 'Robotic Process Automation. A bot mimics a user.' }
};

/** Categorías de pain points (PAIN_CATEGORIES de @processiq/dominio), por id: los mismos del shell. */
export const CATEGORIAS_PAIN_EN = {
  handoff: 'Handoff',
  rework: 'Rework',
  wait: 'Waiting / bottleneck',
  control: 'Duplicate control',
  system: 'Systems / technology',
  regulatory: 'Regulatory / compliance',
  manual: 'Manual activity',
  data: 'Data quality'
};

/** Modelos de IA (MODELOS_IA de @processiq/ia), por id. */
export const MODELOS_EN = {
  'claude-opus-5': 'Claude Opus — highest interpretation quality',
  'claude-sonnet-5': 'Claude Sonnet — fast and economical',
  'claude-haiku-4-5': 'Claude Haiku — ultra-fast, simple tasks'
};

/**
 * Errores de los paquetes que llegan a la persona (alert, copiloto, progreso):
 * cliente de IA (@processiq/ia), lectura de documentos (@processiq/documentos) e
 * importación BPMN (@processiq/bpmn). [patrón del texto español, (m) => inglés].
 */
export const ERRORES_EN = [
  [/^Falta el código de acceso del equipo\. Configúralo en Ajustes de IA \(✨\)\.$/, () => 'The team access code is missing. Set it in AI settings (✨).'],
  [/^El servidor no tiene configurada la clave de Anthropic \(ANTHROPIC_API_KEY\)\.$/, () => 'The server has no Anthropic key configured (ANTHROPIC_API_KEY).'],
  [/^Falta la API key\. Configúrala en Ajustes de IA \(✨\)\.$/, () => 'The API key is missing. Set it in AI settings (✨).'],
  [/^La IA tardó más de (\d+)s y se canceló\./, (m) => `The AI took more than ${m[1]}s and was canceled. Try a shorter document or the Sonnet model (faster) in AI settings.`],
  [/^No se pudo conectar con el servicio de IA \((.*?)\) tras dos intentos\.[\s\S]*\(([\s\S]*)\)$/, (m) => `Could not connect to the AI service (${m[1]}) after two attempts. It may be a dropped connection, a corporate proxy or a browser ad/privacy blocker. Try again; if it persists, try from another network. (${m[2]})`],
  [/^No se pudo conectar con Anthropic tras dos intentos\. Revisa tu conexión a internet\. \(([\s\S]*)\)$/, (m) => `Could not connect to Anthropic after two attempts. Check your internet connection. (${m[1]})`],
  [/^Código de acceso del equipo incorrecto \(401\)\./, () => 'Incorrect team access code (401). Check it in AI settings.'],
  [/^La clave de Anthropic del servidor no es válida o fue revocada \(401\)/, () => 'The server’s Anthropic key is invalid or was revoked (401): check ANTHROPIC_API_KEY.'],
  [/^API key inválida o revocada \(401\)\./, () => 'Invalid or revoked API key (401). Check it in AI settings.'],
  [/^El intermediario rechazó este origen \(403\): abre la app desde su dominio oficial \((\S*) no esta en ALLOWED_ORIGINS\)\.$/, (m) => `The proxy rejected this origin (403): open the app from its official domain (${m[1]} is not in ALLOWED_ORIGINS).`],
  [/^Límite de uso alcanzado \(429\)\./, () => 'Usage limit reached (429). Wait a few seconds and try again.'],
  [/^La IA dejó de responder durante (\d+) s y se canceló\./, (m) => `The AI stopped responding for ${m[1]} s and was canceled. Try again; if it happens again, try a shorter document or the Sonnet model (faster) in AI settings.`],
  [/^Se cortó la conexión mientras la IA respondía \(([\s\S]*)\)\.$/, (m) => `The connection dropped while the AI was responding (${m[1]}).`],
  [/^La IA devolvió un error a mitad de la respuesta: ([\s\S]*)$/, (m) => `The AI returned an error midway through its response: ${m[1]}`],
  [/^El modelo rechazó la solicitud por políticas de seguridad\.$/, () => 'The model declined the request under its safety policies.'],
  [/^El proceso que generó la IA es más largo de lo que puede devolver en una sola respuesta \(([\d.,]+) tokens\)\./, (m) => `The process the AI generated is longer than it can return in a single response (${m[1]} tokens). Your text is fine: generate it again choosing the “Activity” or “Executive” level, or split the procedure into chapters.`],
  [/^Respuesta vacía de la IA\.$/, () => 'Empty response from the AI.'],
  [/^La IA no devolvió JSON\.$/, () => 'The AI did not return JSON.'],
  [/^La IA devolvió una matriz que no se pudo interpretar ni reparar: ([\s\S]*)$/, (m) => `The AI returned a matrix that could not be read or repaired: ${m[1]}`],
  [/^La IA devolvió una matriz que no se pudo interpretar \(([\s\S]*)\)\.$/, (m) => `The AI returned a matrix that could not be read (${m[1]}).`],
  [/^El archivo pesa ([\d.]+) MB \(máximo (\d+) MB\)\./, (m) => `The file is ${m[1]} MB (maximum ${m[2]} MB). Split it or export only the process chapter.`],
  [/^No se encontraron elementos BPMN \(actividades, eventos o compuertas\) en el archivo\.$/, () => 'No BPMN elements (activities, events or gateways) were found in the file.'],
  [/^El formato \.doc antiguo no se pudo leer\./, () => 'The old .doc format could not be read. Save it as .docx or PDF and try again.'],
  [/^El formato \.ppt antiguo no es compatible\./, () => 'The old .ppt format is not supported. Save it as .pptx and try again.'],
  [/^Formato no soportado: \.(\S*)\. Admite Word, PDF, PowerPoint, texto y BPMN\.$/, (m) => `Unsupported format: .${m[1]}. Supported: Word, PDF, PowerPoint, text and BPMN.`],
  [/^No se pudo extraer texto del documento\.$/, () => 'No text could be extracted from the document.'],
  [/^El PDF está protegido con contraseña\./, () => 'The PDF is password-protected. Remove the password and try again.'],
  [/^El PDF está dañado o no se puede abrir\./, () => 'The PDF is damaged or cannot be opened. Try saving it again from the viewer (File → Save as) and retry.'],
  [/^El PDF no tiene texto seleccionable/, () => 'The PDF has no selectable text (it looks scanned or made of images). It needs OCR: open it in Acrobat → “Recognize text”, or paste the text by hand.'],
  [/^El BPMN no tiene actividades, eventos ni compuertas que importar\.$/, () => 'The BPMN has no activities, events or gateways to import.'],
  [/^El archivo no es un XML válido: puede estar incompleto o no ser un diagrama BPMN\.$/, () => 'The file is not valid XML: it may be incomplete or not be a BPMN diagram.'],
  [/^El archivo es XPDL /, () => 'The file is XPDL (the old format of Bizagi and other tools), not BPMN 2.0. Export it again as BPMN 2.0.'],
  [/^El archivo es XML, pero no es un diagrama BPMN 2\.0: su elemento principal es <([^>]*)> y debería ser <definitions>\.$/, (m) => `The file is XML, but it is not a BPMN 2.0 diagram: its root element is <${m[1]}> and it should be <definitions>.`]
];

/** Progreso de la lectura de documentos (@processiq/documentos). */
export const PROGRESO_EN = [
  [/^Importando diagrama BPMN\.\.\.$/, () => 'Importing BPMN diagram...'],
  [/^Leyendo el archivo(\.\.\.|…)$/, (m) => 'Reading the file' + m[1]],
  [/^Abriendo el documento Word\.\.\.$/, () => 'Opening the Word document...'],
  [/^Extrayendo texto del Word\.\.\.$/, () => 'Extracting text from the Word document...'],
  [/^Abriendo la presentación\.\.\.$/, () => 'Opening the presentation...'],
  [/^Extrayendo texto… página (\d+) de (\d+)$/, (m) => `Extracting text… page ${m[1]} of ${m[2]}`]
];

/** Avisos de la importación de un BPMN de otra herramienta (@processiq/bpmn). */
export const AVISOS_BPMN_EN = [
  [/^Se ignoraron elementos que el editor no representa: ([\s\S]*)\.$/, (m) => `Elements the editor does not represent were ignored: ${m[1]}.`],
  [/^(\d+) compuertas? exclusivas? de convergencia se dibujan? como convergencia implícita/, (m) => `${m[1]} exclusive merging gateway(s) drawn as an implicit merge: the editor does not allow an exclusive gateway with a single outgoing flow.`],
  [/^(\d+) eventos? de borde quedan? como evento intermedio/, (m) => `${m[1]} boundary event(s) kept as an intermediate event after their activity: the editor draws one per activity (timer, error or message).`],
  [/^Los eventos de ([\s\S]*) se importan como eventos simples; el tipo queda en sus notas\.$/, (m) => `The ${m[1]} events are imported as plain events; the type is kept in their notes.`],
  [/^(\d+) llamadas? a otros? procesos? \(callActivity\) se importan? como subproceso plegado/, (m) => `${m[1]} call(s) to another process (callActivity) imported as a collapsed subprocess: its content is not in this file.`],
  [/^Los objetos y almacenes de datos pasan a los documentos de entrada y salida y al sistema de cada actividad\.$/, () => 'Data objects and data stores become the input and output documents and the system of each activity.']
];

/**
 * Hallazgos del linter del Playbook MBB (validarProceso de @processiq/dominio): título y
 * detalle. Las etiquetas del proceso van tal cual; el motivo de un verbo prohibido es del
 * catálogo y sigue en español.
 */
export const LINT_EN = [
  [/^Falta evento Start$/, () => 'Missing Start event'],
  [/^Falta evento End$/, () => 'Missing End event'],
  [/^End event genérico$/, () => 'Generic End event'],
  [/^Nodo sin etiqueta$/, () => 'Node without a label'],
  [/^Verbo prohibido: "([\s\S]*)"$/, (m) => `Banned verb: "${m[1]}"`],
  [/^Verbo fuera de catálogo: "([\s\S]*)"$/, (m) => `Verb not in the catalog: "${m[1]}"`],
  [/^Etiqueta demasiado larga$/, () => 'Label too long'],
  [/^Actividad sin responsable$/, () => 'Activity without an owner'],
  [/^Actividad sin tipo de ejecución$/, () => 'Activity without an execution type'],
  [/^Actividad manual >120 min$/, () => 'Manual activity >120 min'],
  [/^Automático con responsable humano$/, () => 'Automatic task with a human owner'],
  [/^Gateway sin pregunta$/, () => 'Gateway without a question'],
  [/^Nodo sin entrada$/, () => 'Node without an incoming flow'],
  [/^Nodo sin salida$/, () => 'Node without an outgoing flow'],
  [/^Gateway con (\d+) salida\(s\) sin etiquetar$/, (m) => `Gateway with ${m[1]} unlabeled outgoing flow(s)`],
  [/^Gateway con >4 salidas$/, () => 'Gateway with >4 outgoing flows'],
  [/^Proceso con (\d+) nodos$/, (m) => `Process with ${m[1]} nodes`],
  [/^Proceso muy simple$/, () => 'Process too simple'],
  [/^(\d+) roles distintos$/, (m) => `${m[1]} different roles`],
  [/^Todo proceso debe iniciar en un evento "Inicio"\.$/, () => 'Every process must begin with a "Start" event.'],
  [/^Todo proceso debe cerrar en al menos un "Fin"\.$/, () => 'Every process must close with at least one "End".'],
  [/^Cada "Fin" debe describir un outcome distinto/, () => 'Each "End" should describe a different outcome (e.g. "Crédito aprobado", "Solicitud rechazada").'],
  [/^Asigna un nombre descriptivo al nodo\.$/, () => 'Give the node a descriptive name.'],
  [/^Considera un verbo del catálogo MBB \(registrar, validar, aprobar…\)\.$/, () => 'Consider a verb from the MBB catalog (registrar, validar, aprobar…).'],
  [/^"([\s\S]*)" tiene (\d+) car \/ (\d+) pal\. Máx 50\/8 → considera descomponer\.$/, (m) => `"${m[1]}" has ${m[2]} chars / ${m[3]} words. Max 50/8 → consider splitting it.`],
  [/^"([\s\S]*)" debe tener un rol asignado\.$/, (m) => `"${m[1]}" must have an assigned role.`],
  [/^Asigna manual\/sistema\/automático\/IA\/etc\. a "([\s\S]*)"\.$/, (m) => `Assign manual/system/automatic/AI/etc. to "${m[1]}".`],
  [/^"([\s\S]*)" es manual y dura más de 2 horas — considera descomponer\.$/, (m) => `"${m[1]}" is manual and takes more than 2 hours — consider splitting it.`],
  [/^"([\s\S]*)" es automática pero tiene responsable "([\s\S]*)"\. ¿Es correcto\?$/, (m) => `"${m[1]}" is automatic but its owner is "${m[2]}". Is that right?`],
  [/^"([\s\S]*)" debe formularse como pregunta cerrada/, (m) => `"${m[1]}" should be phrased as a closed question (¿Sí/No?) or a branching question (¿Qué tipo?).`],
  [/^"([\s\S]*)" no tiene conexión entrante\. Conecta o elimina\.$/, (m) => `"${m[1]}" has no incoming connection. Connect it or delete it.`],
  [/^"([\s\S]*)" no tiene conexión saliente\. Conecta o márcalo como Fin\.$/, (m) => `"${m[1]}" has no outgoing connection. Connect it or mark it as End.`],
  [/^"([\s\S]*)" — etiqueta cada salida \(Sí\/No o valor específico\)\.$/, (m) => `"${m[1]}" — label each outgoing flow (Sí/No or a specific value).`],
  [/^"([\s\S]*)" tiene (\d+) salidas\. Considera descomponer o usar subproceso\.$/, (m) => `"${m[1]}" has ${m[2]} outgoing flows. Consider splitting it or using a subprocess.`],
  [/^Más de 15 nodos visibles → considera extraer secciones a subprocesos\.$/, () => 'More than 15 visible nodes → consider extracting sections into subprocesses.'],
  [/^Menos de 3 nodos\. ¿Falta detalle\?$/, () => 'Fewer than 3 nodes. Is detail missing?'],
  [/^Considera agrupar roles o dividir el proceso para mejorar claridad\.$/, () => 'Consider grouping roles or splitting the process for clarity.']
];

/** Etiqueta de la fuente de una ingesta (dato en español que va al prompt), para los mensajes. */
export const ETIQUETAS_FUENTE_EN = [
  [/^(\d+) fuentes combinadas$/, (m) => `${m[1]} combined sources`],
  [/^texto pegado$/, () => 'pasted text'],
  [/^documento$/, () => 'document']
];

/** Palancas del What-If (PALANCAS_WHATIF de @processiq/analitica), por clave. */
export const PALANCAS_EN = {
  autom_manual: 'Automate rule-based manual tasks',
  elim_handoff: 'Eliminate handoffs (−20% lead time)',
  parallel: 'Parallelize steps (−25% lead time)',
  selfservice: 'Self-service in data capture (−40% capture tasks)'
};
