// Textos del editor en inglés (EE. UU.), con el vocabulario de consultoría de procesos
// del shell (shell/textos/en.ts): process sheet, pain points, revision, standalone
// editor, lane, gateway. Mismas claves y variables {x} que es.js.
export const en = {
  // ---------------------------------------------------------------- index.html (textos/html.js)
  'html.titulo': 'ProcessIQ — BPMN process diagramming · MBC Peru',
  'html.movil.titulo': 'ProcessIQ is designed for desktop',
  'html.movil.texto': 'It is a process diagramming tool with editing panels and a wide canvas: it works best on a large screen (laptop or monitor).',
  'html.movil.continuar': 'Continue anyway',
  'html.movil.pie': 'MBC · Business Consulting · Peru',
  'html.marca.sub': 'Business Consulting · Peru',
  'html.cab.nombre': 'Process name (e.g. Claims Management)',
  'html.cab.meta': 'Industry and macroprocess',
  'html.cab.industria': 'Industry',
  'html.cab.industriaVacia': '— Industry —',
  'html.cab.macro': 'Macroprocess',
  'html.cab.macroVacio': '— Macroprocess —',
  'html.cab.vistas': 'Switch between the As-Is and To-Be views',
  'html.cab.clonar': 'Clone As-Is → To-Be (to start the redesign)',
  'html.cab.clonarAria': 'Clone As-Is to To-Be',
  'html.cab.transformar': 'Generates the To-Be by applying redesign levers by level (Operational/Tactical/Strategic)',
  'html.cab.transformarBoton': 'AI To-Be',
  'html.cab.nuevoTitulo': 'New process',
  'html.cab.nuevo': 'New',
  'html.cab.ingestarTitulo': 'Ingest from audio, notes or an event log',
  'html.cab.ingestar': 'Ingest',
  'html.cab.importar': 'Import JSON project',
  'html.cab.ajustesIa': 'AI settings (Claude)',
  'html.cab.presentarTitulo': 'Presentation mode: hides the toolbars and maximizes the diagram (Esc to exit)',
  'presentar.boton': '⛶ Present',
  'html.cab.exportar': 'Export',
  'html.exp.json': 'JSON · project',
  'html.exp.svg': 'SVG · vector',
  'html.exp.png': 'PNG · image',
  'html.exp.grupoPptx': 'PPTX by design',
  'html.exp.mbcPista': 'blue, Montserrat',
  'html.exp.bbva': 'PPTX · BBVA client',
  'html.exp.bbvaPista': 'Flow Value template',
  'html.exp.grupoOtros': 'Other formats',
  'html.exp.word': 'Word · process report',
  'html.exp.ficha': 'Process Sheet · corporate format',
  'html.riel.aria': 'Drawing tools',
  'html.riel.formasTitulo': 'Add a shape to the canvas',
  'html.riel.formas': 'Add',
  'html.riel.arrastra': 'Drag onto the canvas',
  'html.forma.inicio': 'Start',
  'html.forma.actividad': 'Activity',
  'html.forma.decisionTitulo': 'Decision / gateway',
  'html.forma.decision': 'Decision',
  'html.forma.documento': 'Document',
  'html.forma.sistema': 'System',
  'html.forma.fin': 'End',
  'html.riel.conectarTitulo': 'Connect mode (C)',
  'html.riel.conectar': 'Connect',
  'html.riel.eliminarTitulo': 'Delete selection (Del)',
  'html.riel.eliminar': 'Delete',
  'html.riel.ordenarTitulo': 'Auto-layout: rearranges the diagram',
  'html.riel.ordenar': 'Arrange',
  'html.inicio.titulo': 'Start your process mapping',
  'html.inicio.sub': 'Three ways to create the process flowchart',
  'html.inicio.ingestar': 'Ingest a source',
  'html.inicio.ingestarDesc': 'Interview audio, notes, a document or a CSV event log',
  'html.inicio.ejemplo': 'Load an example',
  'html.inicio.ejemploDesc': 'A complete demo process (pain points, KPIs, simulation) to explore',
  'html.inicio.dibujar': 'Draw it yourself',
  'html.inicio.dibujarDesc': 'Press ＋ on the left toolbar or use the AI copilot',
  'html.hist.deshacerTitulo': 'Undo (Ctrl/⌘ Z)',
  'html.hist.deshacerAria': 'Undo the last change',
  'html.hist.rehacerTitulo': 'Redo (Ctrl/⌘ Y · Ctrl/⌘ Shift Z)',
  'html.hist.rehacerAria': 'Redo the undone change',
  'html.hist.autoajustarTitulo': 'Auto-fit: rearranges the diagram and checks that no arrows cross',
  'html.hist.autoajustarAria': 'Auto-fit the diagram',
  'html.hist.atajosTitulo': 'Keyboard shortcuts (? key)',
  'html.hist.atajosAria': 'Show keyboard shortcuts',
  'html.atajos.titulo': 'Keyboard shortcuts',
  'comun.cerrar': 'Close',
  'html.atajos.cerrar': 'Close shortcuts',
  'html.atajos.deshacer': 'Undo',
  'html.atajos.rehacer': 'Redo',
  'html.atajos.acercar': 'Zoom in',
  'html.atajos.alejar': 'Zoom out',
  'html.atajos.rueda': 'wheel',
  'html.atajos.zoomCursor': 'Zoom toward the cursor',
  'html.atajos.ajustar': 'Fit to screen',
  'html.atajos.conectar': 'Connect mode',
  'html.atajos.supr': 'Backspace',
  'html.atajos.eliminar': 'Delete selection',
  'html.atajos.esc': 'Deselect / exit mode',
  'html.atajos.mostrar': 'Show/hide these shortcuts',
  'html.atajos.nota': 'Double-click a node to edit its label · ＋ opens the shapes to drag',
  'html.leyenda.titulo': 'BPMN 2.0 notation',
  'html.leyenda.cerrar': 'Close legend',
  'html.leyenda.formas': 'Shapes and flows',
  'html.leyenda.actividad': 'Activity / task',
  'html.leyenda.tareaSistema': 'System task',
  'html.leyenda.datos': 'Data / record',
  'html.leyenda.secuencia': 'Sequence flow',
  'html.leyenda.mensaje': 'Message flow (between lanes)',
  'html.leyenda.eventos': 'Events (circles)',
  'html.leyenda.inicioMensaje': 'Start (message)',
  'html.leyenda.intermedio': 'Intermediate · double ring (timer)',
  'html.leyenda.finError': 'End (error)',
  'html.leyenda.senal': 'Signal (broadcast 1→N)',
  'html.leyenda.terminacion': 'Terminate (ends the instance)',
  'html.leyenda.borde': 'Boundary (SLA/exception on a task)',
  'html.leyenda.notaEventos': 'Outline = catch (receives) · Filled = throw (sends) · Dashed = non-interrupting',
  'html.leyenda.gateways': 'Gateways and markers',
  'html.leyenda.xor': 'Exclusive XOR (one path)',
  'html.leyenda.and': 'Parallel AND (fork/join)',
  'html.leyenda.or': 'Inclusive OR (one or more)',
  'html.leyenda.subproceso': 'Marker: subprocess',
  'html.leyenda.loop': 'Marker: loop (repeating)',
  'html.leyenda.multi': 'Marker: multi-instance',
  'html.leyenda.notaTareas': 'Tasks carry a color chip + code [USR-01].',
  'html.estado.modo': 'Edit mode',
  'estado.guardado': 'Saved',
  'html.nivel.titulo': 'Flow level of detail',
  'html.nivel.ejecutivoTitulo': 'Executive: the process in 5-10 stages, without lanes',
  'nivel.ejecutivo': 'Executive',
  'html.nivel.actividadTitulo': 'Activity: groups consecutive tasks of the same actor',
  'nivel.actividad': 'Activity',
  'html.nivel.detalleTitulo': 'Detail: every task, as it was mapped',
  'nivel.detalle': 'Detail',
  'html.zoom.titulo': 'Zoom · Ctrl/⌘ + mouse wheel to zoom in at the cursor · F key to fit',
  'html.zoom.alejarTitulo': 'Zoom out (Ctrl/⌘ −)',
  'html.zoom.nivelTitulo': 'Reset to 100% (Ctrl/⌘ 0)',
  'html.zoom.nivelAria': 'Zoom level; click to reset to 100%',
  'html.zoom.acercarTitulo': 'Zoom in (Ctrl/⌘ +)',
  'html.zoom.ajustarTitulo': 'Fit the whole process to the screen (F key)',
  'html.zoom.ajustarAria': 'Fit the whole process to the screen',
  'html.zoom.ajustar': '⤢ Fit',
  'html.pest.aria': 'Analysis panels',
  'html.pest.props': 'Properties of the selected node',
  'html.pest.kpis': 'KPI library',
  'html.pest.sim': 'FTE and lead time simulator',
  'html.pest.lint': 'MBB validations · linter',
  'html.pest.ficha': 'Corporate process sheet',
  'html.pest.fichaCorta': 'Sheet',
  'html.pest.copiloto': 'AI copilot',
  'html.pest.copilotoCorta': 'AI',
  'html.pest.leyendaTitulo': 'BPMN notation legend',
  'html.pest.leyenda': 'Legend',
  'html.cajon.titulo': 'Properties',
  'html.cajon.cerrarTitulo': 'Close panel (Esc)',
  'html.cajon.cerrarAria': 'Close panel',
  'html.props.vacio': 'Select a node to see its properties.',
  'html.props.tipo': 'BPMN block type',
  'html.props.tipoInicio': '● Start',
  'html.props.tipoIntermedio': '◎ Intermediate event',
  'html.props.tipoActividad': '▭ Activity',
  'html.props.tipoSistema': '▭ System',
  'html.props.tipoDecision': '◇ Decision / Gateway',
  'html.props.tipoDocumento': '▤ Document',
  'html.props.tipoFin': '◉ End',
  'html.props.codigo': 'Activity code',
  'html.props.gateway': 'BPMN gateway type',
  'html.props.gwExclusivo': '✕ Exclusive (XOR — a single path)',
  'html.props.gwParalelo': '＋ Parallel (AND — every path)',
  'html.props.gwInclusivo': '○ Inclusive (OR — one or more)',
  'html.props.evento': 'BPMN event type',
  'html.props.evNinguno': '— Plain (none)',
  'html.props.evMensaje': '✉ Message',
  'html.props.evTimer': '⏱ Timer (wait)',
  'html.props.evSenal': '▲ Signal',
  'html.props.terminacion': 'Terminate event ⬤ <span style="text-transform:none;color:var(--gray-500);font-weight:400">— ends the whole instance</span>',
  'html.props.etiqueta': 'Label ·',
  'html.props.etiquetaPista': 'verb + object',
  'html.props.etiquetaEjemplo': 'E.g. Validar identidad del cliente',
  'html.props.tipoTarea': 'Task type (BPMN marker)',
  'html.props.selecciona': '— Select —',
  'html.props.marcador': 'BPMN activity marker',
  'html.props.mkSimple': '— Plain task',
  'html.props.mkSubproceso': '⊞ Subprocess (collapsed)',
  'html.props.mkLoop': '↻ Loop (repeating)',
  'html.props.mkMulti': '‖ Multi-instance (parallel)',
  'html.props.mkMultiSeq': '≡ Multi-instance (sequential)',
  'html.props.borde': 'BPMN boundary event',
  'html.props.bordePista': '— exception/SLA on the task',
  'html.props.bdNinguno': '— None',
  'html.props.bdTimerInt': '⏱ Timer — interrupting',
  'html.props.bdTimerNoInt': '⏱ Timer — non-interrupting (dashed)',
  'html.props.bdErrorInt': '⚡ Error — interrupting',
  'html.props.bdMensajeNoInt': '✉ Message — non-interrupting (dashed)',
  'html.props.responsable': 'Owner / Role',
  'html.props.responsableEjemplo': 'E.g. Back office analyst',
  'html.props.sistema': 'Supporting system',
  'html.props.sistemaEjemplo': 'E.g. SAP, Salesforce',
  'html.props.tiempo': 'Time (min)',
  'html.props.volumen': 'Volume / month',
  'html.props.valor': 'Value added',
  'html.props.va': 'VA — Value Added',
  'html.props.slaEjemplo': 'E.g. ≤ 2h',
  'html.props.docsEntrada': 'Input documents',
  'html.props.docsEntradaEjemplo': 'E.g. ID, proof of income',
  'html.props.docsSalida': 'Output documents',
  'html.props.docsSalidaEjemplo': 'E.g. Signed contract, receipt',
  'html.props.reglas': 'Decision rules / criteria',
  'html.props.reglasEjemplo': 'Conditional logic, approval criteria, thresholds…',
  'html.props.notas': 'Notes / additional comments',
  'html.pains.pista': 'Select a node and capture its pain points.',
  'html.pains.describe': 'Describe the pain point...',
  'html.pains.severidad': 'Severity',
  'html.pains.sev1': '1 — low',
  'html.pains.sev3': '3 — medium',
  'html.pains.sev5': '5 — critical',
  'html.pains.frecuencia': 'Frequency',
  'html.pains.frec1': '1 — rare',
  'html.pains.frec5': '5 — constant',
  'html.pains.agregar': '+ Add pain point',
  'html.kpis.buscar': 'Search KPIs...',
  'html.kpis.todas': 'All industries',
  'html.sim.titulo': 'Workload simulator',
  'html.sim.pista': 'Calculates FTE, lead time and cost from the <strong>times</strong> and <strong>volumes</strong> captured for each activity. Fill in "Time (min)" and "Volume / month" in the Props tab to feed the simulation.',
  'html.sim.costo': 'Monthly FTE cost (PEN)',
  'html.sim.horas': 'Working hours/month',
  'html.sim.reduccion': '% expected to-be reduction',
  'html.sim.wizard': '⚡ Quick time capture (wizard)',
  'html.sim.ejecutar': '▶ Run simulation',
  'html.lint.titulo': 'Validations · MBB Playbook',
  'html.lint.pista': 'Automatic linter that checks naming, layout, gateways, metadata and anti-patterns. Severity: <span class="sev-tag sev-critical">critical</span> (best resolved before exporting) · <span class="sev-tag sev-high">high</span> · <span class="sev-tag sev-medium">medium</span> · <span class="sev-tag sev-low">low</span>.',
  'html.ficha.titulo': 'Process sheet',
  'html.ficha.pista': 'Corporate metadata of the sheet. The <b>activities, systems, owners and the diagram</b> are generated automatically from the canvas flow.',
  'html.ficha.codigo': 'Code',
  'html.ficha.version': 'Version',
  'html.ficha.objetivo': 'Objective',
  'html.ficha.objetivoEjemplo': 'Describe the activities and responsibilities of the process…',
  'html.ficha.areas': 'Scope · areas involved',
  'html.ficha.areasEjemplo': 'Urban Lot Sales, Sales Administration',
  'html.ficha.desde': 'Starts with',
  'html.ficha.desdeEjemplo': '(auto from the Start node)',
  'html.ficha.hasta': 'Ends with',
  'html.ficha.hastaEjemplo': '(auto from the End node)',
  'html.ficha.incluye': 'Includes / excludes',
  'html.ficha.incluyeEjemplo': 'Covers residential and second-home lots',
  'html.ficha.descripcion': 'Description (optional)',
  'html.ficha.descripcionEjemplo': 'General context of the process…',
  'html.ficha.gobernanzaPista': 'Governance — <b>one row per line</b>, fields separated by <code>|</code>: <code>Role | Position | Name | Date</code>',
  'html.ficha.gobernanza': 'Governance',
  'html.ficha.gobernanzaEjemplo': 'Owner | Head of Sales | Carlos Rolleri | 10/02/2026\nApprover | VP Urban Development | Carlos Conroy | 10/02/2026',
  'html.ficha.sistemasPista': 'Process-level systems — <code>System | Use</code> (each node’s systems are also added automatically)',
  'html.ficha.sistemas': 'Systems',
  'html.ficha.sistemasEjemplo': 'ONBASE | Document management\nSAP | ERP / sale closing',
  'html.ficha.terminosPista': 'Key terms — <code>Term | Definition</code>',
  'html.ficha.terminos': 'Terms',
  'html.ficha.terminosEjemplo': 'Lead | Interested person who shares their contact details\nOpportunity | Potential sale of a lot to a prospect',
  'html.ficha.anexosPista': 'Appendices — <code>Code | Name</code>',
  'html.ficha.anexos': 'Appendices',
  'html.ficha.anexosEjemplo': 'Appendix No. 1 | Know-your-customer affidavit (AML)',
  'html.ficha.cambiosPista': 'Change log — <code>Version | Date | Description</code>',
  'html.ficha.cambios': 'Change log',
  'html.ficha.cambiosEjemplo': '1 | 10/04/2023 | Full update of the document',
  'html.ficha.generarTitulo': 'View and download the full sheet',
  'html.ficha.generar': 'Generate sheet',
  'html.copiloto.pista': 'An assistant to speed up process mapping and diagnosis.',
  'html.copiloto.generate': 'Generate process from a description',
  'html.copiloto.detectPains': 'Detect pain points in the diagram',
  'html.copiloto.suggestKpis': 'Suggest applicable KPIs',
  'html.copiloto.proposeTobe': 'Propose to-be redesign',
  'html.copiloto.raci': 'Generate RACI matrix',
  'html.copiloto.sipoc': 'Generate SIPOC',
  'html.copiloto.impactEffort': 'Impact–effort matrix',
  'html.copiloto.whatif': 'Scenario comparison (What-If)',
  'html.copiloto.automation': 'Automation opportunities',
  'html.copiloto.bottleneck': 'Bottleneck / critical path',
  'html.copiloto.variants': 'Variant analysis (event log)',
  'html.copiloto.valueMap': 'Lean value map (VA/NVA)',
  'html.copiloto.backlog': 'Initiative backlog',
  'html.copiloto.aiPains': 'In-depth pain point analysis (AI)',
  'html.copiloto.autofit': 'Auto-fit (check crossings)',
  'html.copiloto.relayout': 'Rearrange diagram (compact)',
  'html.copiloto.mergeGateways': 'Insert merging gateways',
  'html.copiloto.execSummary': 'Executive summary',
  'html.copiloto.comandos': 'Commands (in Spanish): \'agregar Validar score después de Registrar\', \'eliminar Aprobar\', \'renombrar X a Y\', \'conectar X con Y\', \'marcar X como automático\'…',
  'html.copiloto.enviar': 'Send',
  'comun.cancelar': 'Cancel',
  'comun.aceptar': 'OK',
  'html.ingesta.titulo': '📥 Ingest sources — build the process automatically',
  'html.ingesta.sub': 'ProcessIQ can map the flowchart from <strong>interview audio</strong>, <strong>client notes/documentation</strong>, or <strong>event logs</strong> from their systems.',
  'html.ingesta.pestNotas': '📝 Notes / Documentation',
  'html.ingesta.pestAudio': '🎤 Audio / Transcript',
  'html.ingesta.pestLog': '🗄 Event Log (Process Mining)',
  'html.ingesta.audioPista': 'Record the interview live (requires a microphone and Chrome/Edge) or paste an existing transcript. ProcessIQ will analyze the text and build the as-is flowchart.',
  'html.ingesta.grabar': '🔴 Record',
  'html.ingesta.detener': '⏹ Stop',
  'grabacion.listo': 'ready',
  'html.ingesta.transcripcion': 'The transcript will appear here. You can also paste text directly.',
  'html.ingesta.generarAudio': 'Generate process from transcript →',
  'html.ingesta.notasPista': 'Paste mapping notes, procedure manuals, client descriptions or any text that describes the process step by step. One sentence = one possible activity.',
  'html.ingesta.soltarAria': 'Drop your documents here or click to choose them; you can select several',
  'html.ingesta.soltar': 'Drop your documents here',
  'html.ingesta.soltarSub': 'or <b>click to choose them</b> (you can select several) — Word · PDF · PowerPoint · text · BPMN',
  'html.ingesta.ceroFuentes': '0 sources',
  'html.ingesta.otraFuenteTitulo': 'Add another document, transcript or diagram',
  'html.ingesta.otraFuente': '+ Add another source',
  'html.ingesta.combinar': 'They will be merged into a single AS-IS. Where they contradict each other, the most recent source prevails (e.g. the mapping-interview transcript over an old diagram).',
  'html.ingesta.procesando': 'Processing…',
  'html.ingesta.pegar': 'or paste the text by hand',
  'html.ingesta.notasEjemplo': 'Example:\n1. The client requests the service through the web portal.\n2. The sales advisor validates the data and records the request in Salesforce.\n3. If the amount exceeds 50,000 USD, approval from the sales manager is required.\n4. Operations receives the approved request and activates it in the core system.\n5. The client is notified and the case is closed.\n\nAny format works: bullets, paragraphs, mixed notes...',
  'html.ingesta.generarTitulo': 'Extracts, interprets and draws the process',
  'ingesta.generarProceso': 'Generate process',
  'html.ingesta.ejemplosTitulo': 'Explore the example processes',
  'html.ingesta.ejemplos': 'See examples',
  'html.ingesta.logPista': 'Upload an <strong>event log</strong> in CSV with at least these columns: <code>case_id, activity, timestamp</code> (optional: <code>resource</code>). ProcessIQ will run a lightweight <em>process discovery</em> — it identifies unique activities and the most frequent transitions (alpha-miner style).',
  'html.ingesta.muestra': '📋 Use sample',
  'html.ingesta.colCaso': 'case_id column',
  'html.ingesta.colActividad': 'activity column',
  'html.ingesta.colFecha': 'timestamp column',
  'html.ingesta.colRecurso': 'resource column (optional)',
  'html.ingesta.descubrir': 'Discover process →',
  // ---------------------------------------------------------------- Header, dialog and presentation
  'cabecera.confirmarNuevo': 'Create a new process? The current one will be lost if it has not been exported.',
  'cabecera.disenarToBe': 'Design the To-Be process (AI).',
  'estado.modo': 'Mode: {modo}',
  'estado.modoConexion': 'connect (click source and target)',
  'estado.modoEdicion': 'edit',
  'modal.error': 'Error: {mensaje}',
  'presentar.salir': '✕ Exit',
  // ---------------------------------------------------------------- Status bar, canvas and levels
  'estado.guardando': 'Saving',
  'estado.errorGuardar': 'Could not save',
  'estado.nodos': '{n} nodes',
  'estado.conexiones': '{n} connections',
  'lienzo.etiquetaConexionEj': 'Connection label (e.g. "Yes", "No", "Approved", or a frequency):',
  'lienzo.etiquetaConexion': 'Connection label:',
  'lienzo.etiquetaNodo': 'Node label:',
  'nivel.vista': '**View: {nombre}.** {desc}. **{n} steps** remain out of {total}. The full process is still saved: switching views loses nothing and does not call the AI again.',
  'nivel.info': '{n} of {total} steps',
  // ---------------------------------------------------------------- Ingestion
  'grabacion.sinTranscripcion': 'There is no transcript.',
  'grabacion.sinSoporte': 'Your browser does not support speech recognition. Use Chrome or Edge. You can also paste the transcript by hand.',
  'grabacion.detenido': 'stopped',
  'grabacion.grabando': 'recording…',
  'fuentes.leyendoDocumentos': 'Reading documents…',
  'fuentes.leyendo': 'Reading {i} of {n}: {nombre}',
  'fuentes.sinTexto': '{nombre}: has no readable text',
  'fuentes.anadidos': '{que} · add more or press {boton}',
  'fuentes.unoAnadido': '1 document added',
  'fuentes.variosAnadidos': '{n} documents added',
  'fuentes.combinarYGenerar': 'Combine and generate',
  'fuentes.noLeidos': '{n} file(s) could not be read:\n\n{lista}',
  'fuentes.tagTexto': 'TEXT',
  'fuentes.caracteres': '{n} chars',
  'fuentes.quitar': 'Remove this source',
  'fuentes.unaLista': '1 source ready',
  'fuentes.variasListas': '{n} sources ready to combine',
  'fuentes.excede': 'Together they add up to {total} characters and the AI reads up to {max}: the end of the longest sources will be cut. Remove the ones that add nothing or keep only the process chapters.',
  'fuentes.combinarN': 'Combine {n} sources and generate',
  'formatos.noCarga': 'Could not load {url} (offline or CDN blocked?)',
  'formatos.noLeido': 'The file could not be read.',
  'ingesta.generando': 'Generating…',
  'ingesta.cancelando': 'Canceling…',
  'flujo.abriendo': 'Opening {nombre}...',
  'flujo.diagramaComoFuente': 'Diagram added as a source',
  'flujo.diagramaImportado': 'Diagram imported',
  'flujo.bpmnImportado': '**BPMN imported from {nombre}:** {n} elements ({tareas} activities, {compuertas} gateways, {eventos} events) and {flujos} flows.',
  'flujo.fuenteAnadida': 'Source added: {nombre}',
  'flujo.sinTexto': 'There is no text to interpret. Load a file or paste the process text.',
  'flujo.interpretandoN': 'Interpreting {n} characters with AI... (it can take up to 1 min)',
  'flujo.analizandoN': 'Analyzing {n} characters...',
  'flujo.participantes': 'Participants detected: {n}. Defining roles...',
  'flujo.interpretando': 'Interpreting with AI...',
  'flujo.generadoIa': 'Process generated with AI',
  'flujo.interpretadoIa': '**Process interpreted with AI from {etiqueta}.** {n} elements with roles, systems and decisions. Review the diagram and complete the **Sheet** tab; then export to **Process Sheet**.',
  'flujo.excedia': '\n\nNote: the document exceeded {k}K characters, so I interpreted the first part. If the end of the process is missing, paste that section and generate again.',
  'flujo.generado': 'Process generated',
  'flujo.basico': '**Process generated in basic mode (no AI)** from {etiqueta}. The activities were extracted by keywords: review roles and decisions. To interpret it with Claude, enter the team code in AI settings (✨) and generate again.',
  'flujo.cancelado': 'Canceled.',
  'flujo.consumio': '{error}\n\nThis run still used {coste} at list price.',
  'flujo.noSePudo': 'Could not complete:\n\n{error}',
  'flujo.cargandoPdf': 'Loading the PDF reader (first time only)…',
  'participantes.intervenciones': '{n} contributions',
  'participantes.queRol': 'What is their role?',
  'participantes.intro': 'I detected <b>{n} person(s)</b> in the transcript. Enter each one’s <b>role</b>: the AI will use the role (not the name) as the flow <b>lane</b>, which is the right way to model a process.',
  'participantes.enBlanco': 'Leave blank anyone who does not take part in the process (e.g. the consultant facilitating the meeting): they will be skipped.',
  'participantes.titulo': '👥 Who is who in the meeting?',
  'participantes.usar': 'Use these roles',
  'participantes.omitir': 'Skip',
  'basico.sinActividades': 'I could not extract activities from the text. Try separating them with periods or bullets.',
  'basico.construido': 'I built the flowchart from the source **{fuente}**.\n\nI detected **{n} activities** (+ start/end).\nPatterns applied: activities with infinitive/imperative verbs, decision gateways from conditionals ("si", "cuando", "en caso").\n\nReview, adjust labels and fill in the owners. When you are done, ask me: *"detect pains"* or *"suggest KPIs"*.',
  'basico.recortado': '\n\n⚠️ **The document was very long** ({total} activities detected). I kept the first {n} so the diagram stays readable.\n\n**Recommendation:** set up the **AI (⚙ in the header)** — it interprets the whole document and builds the real flow with roles and decisions, instead of this keyword extraction.',
  // ---------------------------------------------------------------- AI
  'ia.interpretando': '⏳ Interpreting with AI… (it can take a few seconds)',
  'ia.recibiendo': 'Receiving the process from the AI… {n} characters',
  'ia.sinActividades': 'The AI did not return a process with activities.',
  'ia.coste': '\n\nCost of this run: **{usd}** ({entrada} input tokens and {salida} output tokens, {modelo} list price).',
  'ia.sinProceso': 'There is no process to analyze.',
  'ia.analisisFallido': '**The analysis could not be completed:** {error}',
  'tareas.analizando': '_{tarea}: analyzing the process with AI…_',
  'tareas.reintentar': '_You can try again or use basic mode._',
  'painsIa.sinIa': 'The in-depth pain point analysis uses AI (Claude). You have not set up your API key yet. Open AI settings?',
  'painsIa.analizando': '_Analyzing the process for pain points..._',
  'painsIa.detectados': '**{n} pain point(s) detected in the flow** (with evidence from the process itself):',
  'painsIa.puntaje': '  _(sev {sev} x freq {frec} = **{total}**)_',
  'painsIa.evidencia': '  - Evidence: {texto}',
  'painsIa.impacto': '  - Impact: {texto}',
  'painsIa.hipotesis': '**Industry hypotheses - NOT detected in this flow, to validate with the client:**',
  'painsIa.donde': '   - Where to look: {texto}',
  'painsIa.senal': '   - How to confirm it: {texto}',
  'painsIa.noAgregadas': '_These were NOT added to the diagram: they are questions for the mapping interviews, not findings._',
  'codigo.intro': 'ProcessIQ interprets the document with <b>AI (Claude)</b> using the team key. Enter the <b>access code</b> you got from whoever administers the tool: it is stored only in this browser and you will not be asked again.',
  'codigo.etiqueta': 'Team access code',
  'codigo.sinCodigo': 'Without a code you can continue in <b>basic mode</b>: it extracts activities by keywords, without AI.',
  'codigo.titulo': 'Interpret with AI',
  'codigo.usarIa': 'Use AI',
  'codigo.modoBasico': 'Basic mode',
  'profundidad.intro': 'The process is always generated <b>in full</b>. This sets how closely the AI looks at it and which view it opens in; you can switch views at any time with the <b>level of detail</b> selector, without generating again.',
  'profundidad.ejecutivo': 'Milestones and decisions. For a committee or SteerCo.',
  'profundidad.actividad': 'What each role does from start to finish. The usual balance.',
  'profundidad.detalle': 'Every operational step. For a procedures manual or automation.',
  'profundidad.modelo': 'AI model',
  'profundidad.opus': 'Highest interpretation quality. For long or ambiguous procedures, or ones with many decisions.',
  'profundidad.sonnet': 'Faster and 2.5 times cheaper per token. Usually enough for clear, well-structured texts.',
  'profundidad.tituloModelo': 'Level of detail and model',
  'profundidad.titulo': 'Mapping level of detail',
  'profundidad.estimado': 'Estimate: {min} – {max}',
  'profundidad.costeEstimado': 'Estimated cost of this run: <b>{min} – {max}</b>',
  'profundidad.costeDetalle': 'At most {tope}, if the AI uses the whole response ({tokens} tokens). {modelo} at list price: US$ {entrada} per million input tokens and US$ {salida} per million output tokens; ~{tokensEntrada} input tokens.',
  'profundidad.ajustadoUna': 'Range adjusted with {n} real run at this level in this browser.',
  'profundidad.ajustadoVarias': 'Range adjusted with {n} real runs at this level in this browser.',
  'profundidad.inicial': 'Initial estimate: it gets more accurate with your real runs.',
  'profundidad.generar': 'Generate',
  'ajustesIa.proyecto': 'Project AI',
  'ajustesIa.entendido': 'Got it',
  'ajustesIa.intro': 'ProcessIQ uses the <b>Anthropic API (Claude)</b>. In <b>team mode</b> the key lives in the MBC proxy and this browser only stores your access code. With <b>your own API key</b>, the key is stored only in this browser and goes straight to Anthropic.',
  'ajustesIa.modo': 'Mode',
  'ajustesIa.modoEquipo': 'Team key (MBC proxy)',
  'ajustesIa.modoPropia': 'My own API key',
  'ajustesIa.direccion': 'Proxy address',
  'ajustesIa.codigoPista': 'Whoever administers ProcessIQ gives you the code. The Anthropic key lives in the proxy: your browser never sees it.',
  'ajustesIa.apiKey': 'Anthropic API key',
  'ajustesIa.apiKeyPista': 'You get it at <b>console.anthropic.com → API Keys</b>. It starts with <code>sk-ant-</code>.',
  'ajustesIa.modelo': 'Model',
  'ajustesIa.probar': 'Test connection',
  'ajustesIa.byok': '⚠️ BYOK mode: use it for internal work or demos. For a shared public link, a proxy with the key on the server is better.',
  'ajustesIa.titulo': '⚙ AI settings (Claude)',
  'ajustesIa.guardar': 'Save',
  'ajustesIa.probando': '⏳ Testing…',
  'ajustesIa.correcta': '✓ Connection OK',
  'ajustesIa.respondio': '✓ It replied: {texto}',
  'modoIa.servidor': 'It will be interpreted with <b>AI on the server</b>: it rebuilds activities, roles and decisions, and the result is saved in the project.',
  'modoIa.servidorNo': 'Server-side AI is not available right now; <b>basic mode</b> (keywords) will be used.',
  'modoIa.modelo': 'It will be interpreted with <b>AI ({modelo})</b>: it rebuilds activities, roles and decisions.',
  'modoIa.equipo': 'It will be interpreted with <b>AI (Claude)</b> using the team key. When you generate, we will ask for the access code; without it, <b>basic mode</b> (keywords) will be used.',
  // ---------------------------------------------------------------- Copilot
  'copiloto.saludo': 'Hi! I am your **ProcessIQ** copilot.\n\nI am here to help you map, diagnose and redesign processes faster.\nStart by filling in the **name, industry and macroprocess** above, then use the quick actions or ask me something in plain language.\n\nExample: *"Generate the complaints management process for a Peruvian retail bank."*',
  'copiloto.autor': 'ProcessIQ · AI',
  'copiloto.tareaIa': '{tarea} (AI).',
  'copiloto.generarTitulo': 'Generate process from a description',
  'copiloto.generarEjemplo': 'Describe the process to map...',
  'copiloto.generarPedido': 'Generate process: {desc}',
  'copiloto.pedido.detectPains': 'Detect pain points in the current diagram.',
  'copiloto.pedido.suggestKpis': 'Suggest applicable KPIs.',
  'copiloto.pedido.proposeTobe': 'Propose a to-be redesign.',
  'copiloto.pedido.raci': 'Generate the RACI matrix.',
  'copiloto.pedido.sipoc': 'Generate the process SIPOC.',
  'copiloto.pedido.impactEffort': 'Generate the impact–effort matrix.',
  'copiloto.pedido.whatif': 'Compare What-If scenarios.',
  'copiloto.pedido.automation': 'Find automation opportunities.',
  'copiloto.pedido.bottleneck': 'Identify the bottleneck and critical path.',
  'copiloto.pedido.variants': 'Analyze process variants.',
  'copiloto.pedido.valueMap': 'Show the Lean value map (VA/NVA).',
  'copiloto.pedido.backlog': 'Generate the initiative backlog.',
  'copiloto.pedido.execSummary': 'Executive summary of the diagnosis.',
  'copiloto.pedido.mergeGateways': 'Insert merging gateways.',
  'copiloto.pedido.aiPains': 'In-depth pain point analysis (AI).',
  'copiloto.pedido.autofit': 'Auto-fit the diagram.',
  'copiloto.pedido.relayout': 'Rearrange the diagram.',
  'copiloto.reorganizado': '**Diagram rearranged.** {disposicion} Lanes ordered to minimize crossings, with rework loops routed through the bottom corridor.',
  'copiloto.envolvente': 'Wrap mode on: {bandas} bands of up to {columnas} columns (avoids a mile-long diagram).',
  'copiloto.unaBanda': 'Single-band layout.',
  // ---------------------------------------------------------------- Common
  'idioma.grupo': 'Language'
};

// =====================================================================
// Textos que vienen de los paquetes (en español) y se muestran en la interfaz.
// En español se usa el texto del paquete tal cual; en inglés, el de estos mapas
// (traducirDe de i18n.js), y si falta, el español.
// =====================================================================

/** Niveles de detalle (NIVELES de @processiq/motor), por id. */
export const NIVELES_EN = {
  1: { nombre: 'Executive', desc: 'One step per actor between decisions' },
  2: { nombre: 'Activity', desc: 'Groups consecutive tasks of the same actor' },
  3: { nombre: 'Detail', desc: 'Every task, as it was mapped' }
};

/** Tareas de IA del copiloto (TAREAS_IA de @processiq/ia), por clave: los mismos del shell. */
export const TAREAS_IA_EN = {
  'suggest-kpis': 'Suggest applicable KPIs',
  'propose-tobe': 'Propose To-Be redesign',
  'raci': 'RACI matrix',
  'impact-effort': 'Impact–effort matrix',
  'automation': 'Automation opportunities',
  'backlog': 'Initiative backlog',
  'exec-summary': 'Executive summary',
  'sipoc': 'SIPOC',
  'bottleneck': 'Bottleneck and critical path'
};

/** Tipos de ejecución (EXECUTION_TYPES de @processiq/dominio), por id: etiqueta y ayuda. */
export const EJECUCION_EN = {
  manual: { label: 'Manual', desc: 'A person without a system. Purely physical/mental work.' },
  system: { label: 'User Task (system)', desc: 'Person + system (workflow). A person works assisted by an application.' },
  automatic: { label: 'Service Task (auto)', desc: 'No human intervention. Batch, trigger, integration.' },
  ai: { label: 'Script/AI Task', desc: 'Assisted by ML/LLM. Copilots, agents, scoring.' },
  email: { label: 'Receive Task (email)', desc: 'Waits for/receives a message (email, incoming form).' },
  send: { label: 'Send Task', desc: 'Sends a message to an external participant (filled envelope).' },
  phone: { label: 'By phone', desc: 'Synchronous voice communication, call center.' },
  document: { label: 'Document-based', desc: 'Wet signature, paper, stamps, manual filing.' },
  rpa: { label: 'RPA / Bot', desc: 'Robotic Process Automation. A bot mimics a user.' }
};

/** Categorías de pain points (PAIN_CATEGORIES de @processiq/dominio), por id: los mismos del shell. */
export const CATEGORIAS_PAIN_EN = {
  handoff: 'Handoff',
  rework: 'Rework',
  wait: 'Waiting / bottleneck',
  control: 'Duplicate control',
  system: 'Systems / technology',
  regulatory: 'Regulatory / compliance',
  manual: 'Manual activity',
  data: 'Data quality'
};

/** Modelos de IA (MODELOS_IA de @processiq/ia), por id. */
export const MODELOS_EN = {
  'claude-opus-5': 'Claude Opus — highest interpretation quality',
  'claude-sonnet-5': 'Claude Sonnet — fast and economical',
  'claude-haiku-4-5': 'Claude Haiku — ultra-fast, simple tasks'
};

/**
 * Errores de los paquetes que llegan a la persona (alert, copiloto, progreso):
 * cliente de IA (@processiq/ia), lectura de documentos (@processiq/documentos) e
 * importación BPMN (@processiq/bpmn). [patrón del texto español, (m) => inglés].
 */
export const ERRORES_EN = [
  [/^Falta el código de acceso del equipo\. Configúralo en Ajustes de IA \(✨\)\.$/, () => 'The team access code is missing. Set it in AI settings (✨).'],
  [/^El servidor no tiene configurada la clave de Anthropic \(ANTHROPIC_API_KEY\)\.$/, () => 'The server has no Anthropic key configured (ANTHROPIC_API_KEY).'],
  [/^Falta la API key\. Configúrala en Ajustes de IA \(✨\)\.$/, () => 'The API key is missing. Set it in AI settings (✨).'],
  [/^La IA tardó más de (\d+)s y se canceló\./, (m) => `The AI took more than ${m[1]}s and was canceled. Try a shorter document or the Sonnet model (faster) in AI settings.`],
  [/^No se pudo conectar con el servicio de IA \((.*?)\) tras dos intentos\.[\s\S]*\(([\s\S]*)\)$/, (m) => `Could not connect to the AI service (${m[1]}) after two attempts. It may be a dropped connection, a corporate proxy or a browser ad/privacy blocker. Try again; if it persists, try from another network. (${m[2]})`],
  [/^No se pudo conectar con Anthropic tras dos intentos\. Revisa tu conexión a internet\. \(([\s\S]*)\)$/, (m) => `Could not connect to Anthropic after two attempts. Check your internet connection. (${m[1]})`],
  [/^Código de acceso del equipo incorrecto \(401\)\./, () => 'Incorrect team access code (401). Check it in AI settings.'],
  [/^La clave de Anthropic del servidor no es válida o fue revocada \(401\)/, () => 'The server’s Anthropic key is invalid or was revoked (401): check ANTHROPIC_API_KEY.'],
  [/^API key inválida o revocada \(401\)\./, () => 'Invalid or revoked API key (401). Check it in AI settings.'],
  [/^El intermediario rechazó este origen \(403\): abre la app desde su dominio oficial \((\S*) no esta en ALLOWED_ORIGINS\)\.$/, (m) => `The proxy rejected this origin (403): open the app from its official domain (${m[1]} is not in ALLOWED_ORIGINS).`],
  [/^Límite de uso alcanzado \(429\)\./, () => 'Usage limit reached (429). Wait a few seconds and try again.'],
  [/^La IA dejó de responder durante (\d+) s y se canceló\./, (m) => `The AI stopped responding for ${m[1]} s and was canceled. Try again; if it happens again, try a shorter document or the Sonnet model (faster) in AI settings.`],
  [/^Se cortó la conexión mientras la IA respondía \(([\s\S]*)\)\.$/, (m) => `The connection dropped while the AI was responding (${m[1]}).`],
  [/^La IA devolvió un error a mitad de la respuesta: ([\s\S]*)$/, (m) => `The AI returned an error midway through its response: ${m[1]}`],
  [/^El modelo rechazó la solicitud por políticas de seguridad\.$/, () => 'The model declined the request under its safety policies.'],
  [/^El proceso que generó la IA es más largo de lo que puede devolver en una sola respuesta \(([\d.,]+) tokens\)\./, (m) => `The process the AI generated is longer than it can return in a single response (${m[1]} tokens). Your text is fine: generate it again choosing the “Activity” or “Executive” level, or split the procedure into chapters.`],
  [/^Respuesta vacía de la IA\.$/, () => 'Empty response from the AI.'],
  [/^La IA no devolvió JSON\.$/, () => 'The AI did not return JSON.'],
  [/^El archivo pesa ([\d.]+) MB \(máximo (\d+) MB\)\./, (m) => `The file is ${m[1]} MB (maximum ${m[2]} MB). Split it or export only the process chapter.`],
  [/^No se encontraron elementos BPMN \(actividades, eventos o compuertas\) en el archivo\.$/, () => 'No BPMN elements (activities, events or gateways) were found in the file.'],
  [/^El formato \.doc antiguo no se pudo leer\./, () => 'The old .doc format could not be read. Save it as .docx or PDF and try again.'],
  [/^El formato \.ppt antiguo no es compatible\./, () => 'The old .ppt format is not supported. Save it as .pptx and try again.'],
  [/^Formato no soportado: \.(\S*)\. Admite Word, PDF, PowerPoint, texto y BPMN\.$/, (m) => `Unsupported format: .${m[1]}. Supported: Word, PDF, PowerPoint, text and BPMN.`],
  [/^No se pudo extraer texto del documento\.$/, () => 'No text could be extracted from the document.'],
  [/^El PDF está protegido con contraseña\./, () => 'The PDF is password-protected. Remove the password and try again.'],
  [/^El PDF está dañado o no se puede abrir\./, () => 'The PDF is damaged or cannot be opened. Try saving it again from the viewer (File → Save as) and retry.'],
  [/^El PDF no tiene texto seleccionable/, () => 'The PDF has no selectable text (it looks scanned or made of images). It needs OCR: open it in Acrobat → “Recognize text”, or paste the text by hand.'],
  [/^El BPMN no tiene actividades, eventos ni compuertas que importar\.$/, () => 'The BPMN has no activities, events or gateways to import.'],
  [/^El archivo no es un XML válido: puede estar incompleto o no ser un diagrama BPMN\.$/, () => 'The file is not valid XML: it may be incomplete or not be a BPMN diagram.'],
  [/^El archivo es XPDL /, () => 'The file is XPDL (the old format of Bizagi and other tools), not BPMN 2.0. Export it again as BPMN 2.0.'],
  [/^El archivo es XML, pero no es un diagrama BPMN 2\.0: su elemento principal es <([^>]*)> y debería ser <definitions>\.$/, (m) => `The file is XML, but it is not a BPMN 2.0 diagram: its root element is <${m[1]}> and it should be <definitions>.`]
];

/** Progreso de la lectura de documentos (@processiq/documentos). */
export const PROGRESO_EN = [
  [/^Importando diagrama BPMN\.\.\.$/, () => 'Importing BPMN diagram...'],
  [/^Leyendo el archivo(\.\.\.|…)$/, (m) => 'Reading the file' + m[1]],
  [/^Abriendo el documento Word\.\.\.$/, () => 'Opening the Word document...'],
  [/^Extrayendo texto del Word\.\.\.$/, () => 'Extracting text from the Word document...'],
  [/^Abriendo la presentación\.\.\.$/, () => 'Opening the presentation...'],
  [/^Extrayendo texto… página (\d+) de (\d+)$/, (m) => `Extracting text… page ${m[1]} of ${m[2]}`]
];

/** Avisos de la importación de un BPMN de otra herramienta (@processiq/bpmn). */
export const AVISOS_BPMN_EN = [
  [/^Se ignoraron elementos que el editor no representa: ([\s\S]*)\.$/, (m) => `Elements the editor does not represent were ignored: ${m[1]}.`],
  [/^(\d+) compuertas? exclusivas? de convergencia se dibujan? como convergencia implícita/, (m) => `${m[1]} exclusive merging gateway(s) drawn as an implicit merge: the editor does not allow an exclusive gateway with a single outgoing flow.`],
  [/^(\d+) eventos? de borde quedan? como evento intermedio/, (m) => `${m[1]} boundary event(s) kept as an intermediate event after their activity: the editor draws one per activity (timer, error or message).`],
  [/^Los eventos de ([\s\S]*) se importan como eventos simples; el tipo queda en sus notas\.$/, (m) => `The ${m[1]} events are imported as plain events; the type is kept in their notes.`],
  [/^(\d+) llamadas? a otros? procesos? \(callActivity\) se importan? como subproceso plegado/, (m) => `${m[1]} call(s) to another process (callActivity) imported as a collapsed subprocess: its content is not in this file.`],
  [/^Los objetos y almacenes de datos pasan a los documentos de entrada y salida y al sistema de cada actividad\.$/, () => 'Data objects and data stores become the input and output documents and the system of each activity.']
];

/**
 * Hallazgos del linter del Playbook MBB (validarProceso de @processiq/dominio): título y
 * detalle. Las etiquetas del proceso van tal cual; el motivo de un verbo prohibido es del
 * catálogo y sigue en español.
 */
export const LINT_EN = [
  [/^Falta evento Start$/, () => 'Missing Start event'],
  [/^Falta evento End$/, () => 'Missing End event'],
  [/^End event genérico$/, () => 'Generic End event'],
  [/^Nodo sin etiqueta$/, () => 'Node without a label'],
  [/^Verbo prohibido: "([\s\S]*)"$/, (m) => `Banned verb: "${m[1]}"`],
  [/^Verbo fuera de catálogo: "([\s\S]*)"$/, (m) => `Verb not in the catalog: "${m[1]}"`],
  [/^Etiqueta demasiado larga$/, () => 'Label too long'],
  [/^Actividad sin responsable$/, () => 'Activity without an owner'],
  [/^Actividad sin tipo de ejecución$/, () => 'Activity without an execution type'],
  [/^Actividad manual >120 min$/, () => 'Manual activity >120 min'],
  [/^Automático con responsable humano$/, () => 'Automatic task with a human owner'],
  [/^Gateway sin pregunta$/, () => 'Gateway without a question'],
  [/^Nodo sin entrada$/, () => 'Node without an incoming flow'],
  [/^Nodo sin salida$/, () => 'Node without an outgoing flow'],
  [/^Gateway con (\d+) salida\(s\) sin etiquetar$/, (m) => `Gateway with ${m[1]} unlabeled outgoing flow(s)`],
  [/^Gateway con >4 salidas$/, () => 'Gateway with >4 outgoing flows'],
  [/^Proceso con (\d+) nodos$/, (m) => `Process with ${m[1]} nodes`],
  [/^Proceso muy simple$/, () => 'Process too simple'],
  [/^(\d+) roles distintos$/, (m) => `${m[1]} different roles`],
  [/^Todo proceso debe iniciar en un evento "Inicio"\.$/, () => 'Every process must begin with a "Start" event.'],
  [/^Todo proceso debe cerrar en al menos un "Fin"\.$/, () => 'Every process must close with at least one "End".'],
  [/^Cada "Fin" debe describir un outcome distinto/, () => 'Each "End" should describe a different outcome (e.g. "Crédito aprobado", "Solicitud rechazada").'],
  [/^Asigna un nombre descriptivo al nodo\.$/, () => 'Give the node a descriptive name.'],
  [/^Considera un verbo del catálogo MBB \(registrar, validar, aprobar…\)\.$/, () => 'Consider a verb from the MBB catalog (registrar, validar, aprobar…).'],
  [/^"([\s\S]*)" tiene (\d+) car \/ (\d+) pal\. Máx 50\/8 → considera descomponer\.$/, (m) => `"${m[1]}" has ${m[2]} chars / ${m[3]} words. Max 50/8 → consider splitting it.`],
  [/^"([\s\S]*)" debe tener un rol asignado\.$/, (m) => `"${m[1]}" must have an assigned role.`],
  [/^Asigna manual\/sistema\/automático\/IA\/etc\. a "([\s\S]*)"\.$/, (m) => `Assign manual/system/automatic/AI/etc. to "${m[1]}".`],
  [/^"([\s\S]*)" es manual y dura más de 2 horas — considera descomponer\.$/, (m) => `"${m[1]}" is manual and takes more than 2 hours — consider splitting it.`],
  [/^"([\s\S]*)" es automática pero tiene responsable "([\s\S]*)"\. ¿Es correcto\?$/, (m) => `"${m[1]}" is automatic but its owner is "${m[2]}". Is that right?`],
  [/^"([\s\S]*)" debe formularse como pregunta cerrada/, (m) => `"${m[1]}" should be phrased as a closed question (¿Sí/No?) or a branching question (¿Qué tipo?).`],
  [/^"([\s\S]*)" no tiene conexión entrante\. Conecta o elimina\.$/, (m) => `"${m[1]}" has no incoming connection. Connect it or delete it.`],
  [/^"([\s\S]*)" no tiene conexión saliente\. Conecta o márcalo como Fin\.$/, (m) => `"${m[1]}" has no outgoing connection. Connect it or mark it as End.`],
  [/^"([\s\S]*)" — etiqueta cada salida \(Sí\/No o valor específico\)\.$/, (m) => `"${m[1]}" — label each outgoing flow (Sí/No or a specific value).`],
  [/^"([\s\S]*)" tiene (\d+) salidas\. Considera descomponer o usar subproceso\.$/, (m) => `"${m[1]}" has ${m[2]} outgoing flows. Consider splitting it or using a subprocess.`],
  [/^Más de 15 nodos visibles → considera extraer secciones a subprocesos\.$/, () => 'More than 15 visible nodes → consider extracting sections into subprocesses.'],
  [/^Menos de 3 nodos\. ¿Falta detalle\?$/, () => 'Fewer than 3 nodes. Is detail missing?'],
  [/^Considera agrupar roles o dividir el proceso para mejorar claridad\.$/, () => 'Consider grouping roles or splitting the process for clarity.']
];

/** Etiqueta de la fuente de una ingesta (dato en español que va al prompt), para los mensajes. */
export const ETIQUETAS_FUENTE_EN = [
  [/^(\d+) fuentes combinadas$/, (m) => `${m[1]} combined sources`],
  [/^texto pegado$/, () => 'pasted text'],
  [/^documento$/, () => 'document']
];

/** Palancas del What-If (PALANCAS_WHATIF de @processiq/analitica), por clave. */
export const PALANCAS_EN = {
  autom_manual: 'Automate rule-based manual tasks',
  elim_handoff: 'Eliminate handoffs (−20% lead time)',
  parallel: 'Parallelize steps (−25% lead time)',
  selfservice: 'Self-service in data capture (−40% capture tasks)'
};
