// Textos del editor en español: la fuente de verdad. Son los textos que había, byte
// a byte (la fidelidad compara el editor en español con el MVP): no se cambian aquí.
// Un texto nuevo va aquí y en en.js con la misma clave y las mismas variables {x}
// (lo comprueba editor-idioma.spec.mjs). Sin imports: la prueba lo lee desde Node.
export const es = {
  // ---------------------------------------------------------------- index.html (textos/html.js)
  'html.titulo': 'ProcessIQ — Diagramador de procesos BPMN · MBC Perú',
  'html.movil.titulo': 'ProcessIQ está optimizado para escritorio',
  'html.movil.texto': 'Es un diagramador de procesos con paneles de edición y un lienzo amplio: la mejor experiencia es en una pantalla grande (laptop o monitor).',
  'html.movil.continuar': 'Continuar de todos modos',
  'html.movil.pie': 'MBC · Business Consulting · Perú',
  'html.marca.sub': 'Business Consulting · Perú',
  'html.cab.nombre': 'Nombre del proceso (ej. Gestión de Reclamos)',
  'html.cab.meta': 'Industria y macroproceso',
  'html.cab.industria': 'Industria',
  'html.cab.industriaVacia': '— Industria —',
  'html.cab.macro': 'Macroproceso',
  'html.cab.macroVacio': '— Macroproceso —',
  'html.cab.vistas': 'Cambia entre vista As-Is y To-Be',
  'html.cab.clonar': 'Clonar As-Is → To-Be (para empezar a reingenierar)',
  'html.cab.clonarAria': 'Clonar As-Is a To-Be',
  'html.cab.transformar': 'Genera el To-Be aplicando reingeniería por nivel (Operativo/Táctico/Estratégico)',
  'html.cab.transformarBoton': 'To-Be IA',
  'html.cab.nuevoTitulo': 'Nuevo proceso',
  'html.cab.nuevo': 'Nuevo',
  'html.cab.ingestarTitulo': 'Ingestar desde audio, notas o event log',
  'html.cab.ingestar': 'Ingestar',
  'html.cab.importar': 'Importar proyecto JSON',
  'html.cab.ajustesIa': 'Ajustes de IA (Claude)',
  'html.cab.presentarTitulo': 'Modo presentación: oculta las barras y maximiza el diagrama (Esc para salir)',
  'presentar.boton': '⛶ Presentar',
  'html.cab.exportar': 'Exportar',
  'html.exp.json': 'JSON · proyecto',
  'html.exp.svg': 'SVG · vectorial',
  'html.exp.png': 'PNG · imagen',
  'html.exp.grupoPptx': 'PPTX por diseño',
  'html.exp.mbcPista': 'azul, Montserrat',
  'html.exp.bbva': 'PPTX · cliente BBVA',
  'html.exp.bbvaPista': 'plantilla Flow Value',
  'html.exp.grupoOtros': 'Otros formatos',
  'html.exp.word': 'Word · informe del proceso',
  'html.exp.ficha': 'Ficha de Proceso · formato corporativo',
  'html.riel.aria': 'Herramientas de dibujo',
  'html.riel.formasTitulo': 'Añadir forma al lienzo',
  'html.riel.formas': 'Añadir',
  'html.riel.arrastra': 'Arrastra al lienzo',
  'html.forma.inicio': 'Inicio',
  'html.forma.actividad': 'Actividad',
  'html.forma.decisionTitulo': 'Decisión / gateway',
  'html.forma.decision': 'Decisión',
  'html.forma.documento': 'Documento',
  'html.forma.sistema': 'Sistema',
  'html.forma.fin': 'Fin',
  'html.riel.conectarTitulo': 'Modo conexión (C)',
  'html.riel.conectar': 'Conectar',
  'html.riel.eliminarTitulo': 'Eliminar selección (Supr)',
  'html.riel.eliminar': 'Eliminar',
  'html.riel.ordenarTitulo': 'Auto-layout: reordena el diagrama',
  'html.riel.ordenar': 'Ordenar',
  'html.inicio.titulo': 'Empieza tu levantamiento',
  'html.inicio.sub': 'Tres formas de crear el flujograma del proceso',
  'html.inicio.ingestar': 'Ingestar fuente',
  'html.inicio.ingestarDesc': 'Audio de entrevista, notas, documento o event log CSV',
  'html.inicio.ejemplo': 'Cargar ejemplo',
  'html.inicio.ejemploDesc': 'Proceso demo completo (pains, KPIs, simulación) para explorar',
  'html.inicio.dibujar': 'Dibujar manual',
  'html.inicio.dibujarDesc': 'Pulsa ＋ en la barra izquierda o usa el copiloto IA',
  'html.hist.deshacerTitulo': 'Deshacer (Ctrl/⌘ Z)',
  'html.hist.deshacerAria': 'Deshacer el último cambio',
  'html.hist.rehacerTitulo': 'Rehacer (Ctrl/⌘ Y · Ctrl/⌘ Shift Z)',
  'html.hist.rehacerAria': 'Rehacer el cambio deshecho',
  'html.hist.autoajustarTitulo': 'Autoajustar: reordena y verifica que no se crucen las flechas',
  'html.hist.autoajustarAria': 'Autoajustar diagrama',
  'html.hist.atajosTitulo': 'Atajos de teclado (tecla ?)',
  'html.hist.atajosAria': 'Ver atajos de teclado',
  'html.atajos.titulo': 'Atajos de teclado',
  'comun.cerrar': 'Cerrar',
  'html.atajos.cerrar': 'Cerrar atajos',
  'html.atajos.deshacer': 'Deshacer',
  'html.atajos.rehacer': 'Rehacer',
  'html.atajos.acercar': 'Acercar zoom',
  'html.atajos.alejar': 'Alejar zoom',
  'html.atajos.rueda': 'rueda',
  'html.atajos.zoomCursor': 'Zoom hacia el cursor',
  'html.atajos.ajustar': 'Ajustar a la pantalla',
  'html.atajos.conectar': 'Modo conectar',
  'html.atajos.supr': 'Supr',
  'html.atajos.eliminar': 'Eliminar selección',
  'html.atajos.esc': 'Deseleccionar / salir de modo',
  'html.atajos.mostrar': 'Mostrar/ocultar estos atajos',
  'html.atajos.nota': 'Doble-clic en un nodo edita su etiqueta · ＋ abre las formas para arrastrar',
  'html.leyenda.titulo': 'Nomenclatura BPMN 2.0',
  'html.leyenda.cerrar': 'Cerrar leyenda',
  'html.leyenda.formas': 'Formas y flujos',
  'html.leyenda.actividad': 'Actividad / tarea',
  'html.leyenda.tareaSistema': 'Tarea de sistema',
  'html.leyenda.datos': 'Datos / registro',
  'html.leyenda.secuencia': 'Flujo de secuencia',
  'html.leyenda.mensaje': 'Flujo de mensaje (entre carriles)',
  'html.leyenda.eventos': 'Eventos (círculos)',
  'html.leyenda.inicioMensaje': 'Inicio (mensaje)',
  'html.leyenda.intermedio': 'Intermedio · doble anillo (timer)',
  'html.leyenda.finError': 'Fin (error)',
  'html.leyenda.senal': 'Señal (broadcast 1→N)',
  'html.leyenda.terminacion': 'Terminación (corta la instancia)',
  'html.leyenda.borde': 'De borde (SLA/excepción sobre tarea)',
  'html.leyenda.notaEventos': 'Contorno = catch (recibe) · Relleno = throw (lanza) · Punteado = no interrumpe',
  'html.leyenda.gateways': 'Gateways y marcadores',
  'html.leyenda.xor': 'Exclusivo XOR (un camino)',
  'html.leyenda.and': 'Paralelo AND (fork/join)',
  'html.leyenda.or': 'Inclusivo OR (uno o varios)',
  'html.leyenda.subproceso': 'Marcador: subproceso',
  'html.leyenda.loop': 'Marcador: loop (cíclica)',
  'html.leyenda.multi': 'Marcador: multi-instancia',
  'html.leyenda.notaTareas': 'Las tareas llevan chip de color + código [USR-01].',
  'html.estado.modo': 'Modo edición',
  'estado.guardado': 'Guardado',
  'html.nivel.titulo': 'Nivel de detalle del flujo',
  'html.nivel.ejecutivoTitulo': 'Ejecutivo: el proceso en 5-10 etapas, sin carriles',
  'nivel.ejecutivo': 'Ejecutivo',
  'html.nivel.actividadTitulo': 'Actividad: agrupa tareas consecutivas del mismo actor',
  'nivel.actividad': 'Actividad',
  'html.nivel.detalleTitulo': 'Detalle: todas las tareas, como se levantó',
  'nivel.detalle': 'Detalle',
  'html.zoom.titulo': 'Zoom · Ctrl/⌘ + rueda del mouse para acercar sobre el cursor · tecla F para ajustar',
  'html.zoom.alejarTitulo': 'Alejar (Ctrl/⌘ −)',
  'html.zoom.nivelTitulo': 'Restablecer a 100% (Ctrl/⌘ 0)',
  'html.zoom.nivelAria': 'Nivel de zoom; clic para restablecer a 100%',
  'html.zoom.acercarTitulo': 'Acercar (Ctrl/⌘ +)',
  'html.zoom.ajustarTitulo': 'Ajustar todo el proceso a la pantalla (tecla F)',
  'html.zoom.ajustarAria': 'Ajustar todo el proceso a la pantalla',
  'html.zoom.ajustar': '⤢ Ajustar',
  'html.pest.aria': 'Paneles de análisis',
  'html.pest.props': 'Propiedades del nodo seleccionado',
  'html.pest.kpis': 'Librería de KPIs',
  'html.pest.sim': 'Simulador FTE y lead time',
  'html.pest.lint': 'Validaciones MBB · linter',
  'html.pest.ficha': 'Ficha de proceso corporativa',
  'html.pest.fichaCorta': 'Ficha',
  'html.pest.copiloto': 'Copiloto IA',
  'html.pest.copilotoCorta': 'IA',
  'html.pest.leyendaTitulo': 'Leyenda de nomenclatura BPMN',
  'html.pest.leyenda': 'Leyenda',
  'html.cajon.titulo': 'Propiedades',
  'html.cajon.cerrarTitulo': 'Cerrar panel (Esc)',
  'html.cajon.cerrarAria': 'Cerrar panel',
  'html.props.vacio': 'Selecciona un nodo para ver sus propiedades.',
  'html.props.tipo': 'Tipo de bloque BPMN',
  'html.props.tipoInicio': '● Inicio',
  'html.props.tipoIntermedio': '◎ Evento intermedio',
  'html.props.tipoActividad': '▭ Actividad',
  'html.props.tipoSistema': '▭ Sistema',
  'html.props.tipoDecision': '◇ Decisión / Gateway',
  'html.props.tipoDocumento': '▤ Documento',
  'html.props.tipoFin': '◉ Fin',
  'html.props.codigo': 'Código actividad',
  'html.props.gateway': 'Tipo de gateway BPMN',
  'html.props.gwExclusivo': '✕ Exclusivo (XOR — un solo camino)',
  'html.props.gwParalelo': '＋ Paralelo (AND — todos los caminos)',
  'html.props.gwInclusivo': '○ Inclusivo (OR — uno o varios)',
  'html.props.evento': 'Tipo de evento BPMN',
  'html.props.evNinguno': '— Simple (ninguno)',
  'html.props.evMensaje': '✉ Mensaje',
  'html.props.evTimer': '⏱ Temporizador (espera)',
  'html.props.evSenal': '▲ Señal',
  'html.props.terminacion': 'Evento de terminación ⬤ <span style="text-transform:none;color:var(--gray-500);font-weight:400">— corta toda la instancia</span>',
  'html.props.etiqueta': 'Etiqueta ·',
  'html.props.etiquetaPista': 'verbo + objeto',
  'html.props.etiquetaEjemplo': 'Ej. Validar identidad del cliente',
  'html.props.tipoTarea': 'Tipo de tarea (marcador BPMN)',
  'html.props.selecciona': '— Selecciona —',
  'html.props.marcador': 'Marcador de actividad BPMN',
  'html.props.mkSimple': '— Tarea simple',
  'html.props.mkSubproceso': '⊞ Subproceso (colapsado)',
  'html.props.mkLoop': '↻ Loop (cíclica)',
  'html.props.mkMulti': '‖ Multi-instancia (paralela)',
  'html.props.mkMultiSeq': '≡ Multi-instancia (secuencial)',
  'html.props.borde': 'Evento de borde BPMN',
  'html.props.bordePista': '— excepción/SLA sobre la tarea',
  'html.props.bdNinguno': '— Ninguno',
  'html.props.bdTimerInt': '⏱ Timer — interrumpe',
  'html.props.bdTimerNoInt': '⏱ Timer — no interrumpe (punteado)',
  'html.props.bdErrorInt': '⚡ Error — interrumpe',
  'html.props.bdMensajeNoInt': '✉ Mensaje — no interrumpe (punteado)',
  'html.props.responsable': 'Responsable / Rol',
  'html.props.responsableEjemplo': 'Ej. Analista back office',
  'html.props.sistema': 'Sistema soporte',
  'html.props.sistemaEjemplo': 'Ej. SAP, Salesforce',
  'html.props.tiempo': 'Tiempo (min)',
  'html.props.volumen': 'Volumen / mes',
  'html.props.valor': 'Valor añadido',
  'html.props.va': 'VA — Valor Añadido',
  'html.props.slaEjemplo': 'Ej. ≤ 2h',
  'html.props.docsEntrada': 'Documentos entrada',
  'html.props.docsEntradaEjemplo': 'Ej. DNI, comprobante de ingresos',
  'html.props.docsSalida': 'Documentos salida',
  'html.props.docsSalidaEjemplo': 'Ej. Contrato firmado, voucher',
  'html.props.reglas': 'Reglas / criterios de decisión',
  'html.props.reglasEjemplo': 'Lógica condicional, criterios de aprobación, umbrales…',
  'html.props.notas': 'Notas / comentarios adicionales',
  'html.pains.pista': 'Selecciona un nodo y captura sus dolores.',
  'html.pains.describe': 'Describe el pain...',
  'html.pains.severidad': 'Severidad',
  'html.pains.sev1': '1 — baja',
  'html.pains.sev3': '3 — media',
  'html.pains.sev5': '5 — crítica',
  'html.pains.frecuencia': 'Frecuencia',
  'html.pains.frec1': '1 — rara',
  'html.pains.frec5': '5 — constante',
  'html.pains.agregar': '+ Agregar pain',
  'html.kpis.buscar': 'Buscar KPI...',
  'html.kpis.todas': 'Todas las industrias',
  'html.sim.titulo': 'Simulador de carga',
  'html.sim.pista': 'Calcula FTE, lead time y costo a partir de los <strong>tiempos</strong> y <strong>volúmenes</strong> capturados en cada actividad. Completa "Tiempo (min)" y "Volumen mensual" en la pestaña Props para alimentar la simulación.',
  'html.sim.costo': 'Costo FTE mensual (PEN)',
  'html.sim.horas': 'Horas hábiles/mes',
  'html.sim.reduccion': '% reducción esperada to-be',
  'html.sim.wizard': '⚡ Capturar tiempos rápido (wizard)',
  'html.sim.ejecutar': '▶ Ejecutar simulación',
  'html.lint.titulo': 'Validaciones · Playbook MBB',
  'html.lint.pista': 'Linter automático que verifica naming, layout, gateways, metadata y antipatrones. Severidad: <span class="sev-tag sev-critical">crítico</span> (conviene resolverlo antes de exportar) · <span class="sev-tag sev-high">alto</span> · <span class="sev-tag sev-medium">medio</span> · <span class="sev-tag sev-low">bajo</span>.',
  'html.ficha.titulo': 'Ficha de proceso',
  'html.ficha.pista': 'Metadatos corporativos de la ficha. Las <b>actividades, sistemas, responsables y el diagrama</b> se generan automáticamente desde el flujo del canvas.',
  'html.ficha.codigo': 'Código',
  'html.ficha.version': 'Versión',
  'html.ficha.objetivo': 'Objetivo',
  'html.ficha.objetivoEjemplo': 'Describir las actividades y responsabilidades del proceso…',
  'html.ficha.areas': 'Alcance · áreas involucradas',
  'html.ficha.areasEjemplo': 'Ventas de Lotes Urbanos, Administración de Ventas',
  'html.ficha.desde': 'Inicia con',
  'html.ficha.desdeEjemplo': '(auto desde el nodo Inicio)',
  'html.ficha.hasta': 'Termina con',
  'html.ficha.hastaEjemplo': '(auto desde el nodo Fin)',
  'html.ficha.incluye': 'Incluye / excluye',
  'html.ficha.incluyeEjemplo': 'Abarca lotes residenciales y de segunda vivienda',
  'html.ficha.descripcion': 'Descripción (opcional)',
  'html.ficha.descripcionEjemplo': 'Contexto general del proceso…',
  'html.ficha.gobernanzaPista': 'Gobernanza — <b>una fila por línea</b>, campos separados por <code>|</code>: <code>Rol | Cargo | Nombre | Fecha</code>',
  'html.ficha.gobernanza': 'Gobernanza',
  'html.ficha.gobernanzaEjemplo': 'Dueño | Jefe de Ventas | Carlos Rolleri | 10/02/2026\nAprobador | VP Desarrollo Urbano | Carlos Conroy | 10/02/2026',
  'html.ficha.sistemasPista': 'Sistemas de nivel proceso — <code>Sistema | Uso</code> (además, los sistemas de cada nodo se agregan solos)',
  'html.ficha.sistemas': 'Sistemas',
  'html.ficha.sistemasEjemplo': 'ONBASE | Gestión documental\nSAP | ERP / cierre de venta',
  'html.ficha.terminosPista': 'Términos clave — <code>Término | Definición</code>',
  'html.ficha.terminos': 'Términos',
  'html.ficha.terminosEjemplo': 'Lead | Persona interesada que comparte su contacto\nOportunidad | Potencial venta de lote a un prospecto',
  'html.ficha.anexosPista': 'Anexos — <code>Código | Nombre</code>',
  'html.ficha.anexos': 'Anexos',
  'html.ficha.anexosEjemplo': 'Anexo N°1 | DJ de conocimiento de clientes PN LAFT',
  'html.ficha.cambiosPista': 'Control de cambios — <code>Versión | Fecha | Descripción</code>',
  'html.ficha.cambios': 'Control de cambios',
  'html.ficha.cambiosEjemplo': '1 | 10/04/2023 | Actualización completa del documento',
  'html.ficha.generarTitulo': 'Ver y descargar la ficha completa',
  'html.ficha.generar': 'Generar ficha',
  'html.copiloto.pista': 'Asistente para acelerar el levantamiento y diagnóstico.',
  'html.copiloto.generate': 'Generar proceso desde descripción',
  'html.copiloto.detectPains': 'Detectar pains en el diagrama',
  'html.copiloto.suggestKpis': 'Sugerir KPIs aplicables',
  'html.copiloto.proposeTobe': 'Proponer reingeniería to-be',
  'html.copiloto.raci': 'Generar matriz RACI',
  'html.copiloto.sipoc': 'Generar SIPOC',
  'html.copiloto.impactEffort': 'Matriz impacto-esfuerzo',
  'html.copiloto.whatif': 'Comparador de escenarios (What-If)',
  'html.copiloto.automation': 'Oportunidades de automatización',
  'html.copiloto.bottleneck': 'Cuello de botella / ruta crítica',
  'html.copiloto.variants': 'Análisis de variantes (event log)',
  'html.copiloto.valueMap': 'Mapa de valor Lean (VA/NVA)',
  'html.copiloto.backlog': 'Backlog de iniciativas',
  'html.copiloto.aiPains': 'Análisis profundo de dolores (IA)',
  'html.copiloto.autofit': 'Autoajustar (verificar cruces)',
  'html.copiloto.relayout': 'Reorganizar diagrama (compactar)',
  'html.copiloto.mergeGateways': 'Insertar compuertas de convergencia',
  'html.copiloto.execSummary': 'Resumen ejecutivo',
  'html.copiloto.comandos': 'Comandos: \'agregar Validar score después de Registrar\', \'eliminar Aprobar\', \'renombrar X a Y\', \'conectar X con Y\', \'marcar X como automático\'…',
  'html.copiloto.enviar': 'Enviar',
  'comun.cancelar': 'Cancelar',
  'comun.aceptar': 'Aceptar',
  'html.ingesta.titulo': '📥 Ingestar fuentes — construir proceso automáticamente',
  'html.ingesta.sub': 'ProcessIQ puede levantar el flujograma a partir de <strong>audio de entrevista</strong>, <strong>notas/documentación del cliente</strong>, o <strong>event logs</strong> de sus sistemas.',
  'html.ingesta.pestNotas': '📝 Notas / Documentación',
  'html.ingesta.pestAudio': '🎤 Audio / Transcripción',
  'html.ingesta.pestLog': '🗄 Event Log (Process Mining)',
  'html.ingesta.audioPista': 'Graba la entrevista en vivo (requiere micrófono y Chrome/Edge) o pega una transcripción existente. ProcessIQ analizará el texto y construirá el flujograma as-is.',
  'html.ingesta.grabar': '🔴 Grabar',
  'html.ingesta.detener': '⏹ Detener',
  'grabacion.listo': 'listo',
  'html.ingesta.transcripcion': 'La transcripción aparecerá aquí. También puedes pegar texto directamente.',
  'html.ingesta.generarAudio': 'Generar proceso desde transcripción →',
  'html.ingesta.notasPista': 'Pega notas de levantamiento, manuales de procedimiento, descripciones del cliente o cualquier texto que describa el proceso paso a paso. Una oración = una posible actividad.',
  'html.ingesta.soltarAria': 'Suelta tus documentos aquí o haz clic para elegirlos; puedes seleccionar varios',
  'html.ingesta.soltar': 'Suelta aquí tus documentos',
  'html.ingesta.soltarSub': 'o <b>haz clic para elegirlos</b> (puedes seleccionar varios) — Word · PDF · PowerPoint · texto · BPMN',
  'html.ingesta.ceroFuentes': '0 fuentes',
  'html.ingesta.otraFuenteTitulo': 'Añadir otro documento, transcripción o diagrama',
  'html.ingesta.otraFuente': '+ Añadir otra fuente',
  'html.ingesta.combinar': 'Se combinarán en un solo AS-IS. Ante contradicciones prevalece la fuente más reciente (p. ej. la transcripción del levantamiento sobre un diagrama antiguo).',
  'html.ingesta.procesando': 'Procesando…',
  'html.ingesta.pegar': 'o pega el texto a mano',
  'html.ingesta.notasEjemplo': 'Ejemplo:\n1. El cliente solicita el servicio a través del portal web.\n2. El asesor comercial valida los datos y registra la solicitud en Salesforce.\n3. Si el monto supera 50,000 USD se requiere aprobación del gerente comercial.\n4. Operaciones recibe la solicitud aprobada y procede a la activación en el core.\n5. Se notifica al cliente y se cierra el caso.\n\nCualquier formato funciona: bullets, párrafos, notas mezcladas...',
  'html.ingesta.generarTitulo': 'Extrae, interpreta y dibuja el proceso',
  'ingesta.generarProceso': 'Generar proceso',
  'html.ingesta.ejemplosTitulo': 'Explora los procesos de ejemplo',
  'html.ingesta.ejemplos': 'Ver ejemplos',
  'html.ingesta.logPista': 'Sube un <strong>event log</strong> en CSV con columnas mínimas: <code>case_id, activity, timestamp</code> (opcional: <code>resource</code>). ProcessIQ ejecutará un <em>process discovery</em> ligero — identifica actividades únicas y transiciones más frecuentes (estilo alpha miner).',
  'html.ingesta.muestra': '📋 Usar muestra',
  'html.ingesta.colCaso': 'Columna case_id',
  'html.ingesta.colActividad': 'Columna activity',
  'html.ingesta.colFecha': 'Columna timestamp',
  'html.ingesta.colRecurso': 'Columna resource (opcional)',
  'html.ingesta.descubrir': 'Descubrir proceso →',
  // ---------------------------------------------------------------- Cabecera, modal y presentación
  'cabecera.confirmarNuevo': '¿Crear un nuevo proceso? Se perderá el actual si no fue exportado.',
  'cabecera.disenarToBe': 'Diseñar el proceso To-Be (IA).',
  'estado.modo': 'Modo: {modo}',
  'estado.modoConexion': 'conexión (click origen y destino)',
  'estado.modoEdicion': 'edición',
  'modal.error': 'Error: {mensaje}',
  'presentar.salir': '✕ Salir',
  // ---------------------------------------------------------------- Barra de estado, lienzo y niveles
  'estado.guardando': 'Guardando',
  'estado.errorGuardar': 'Error al guardar',
  'estado.nodos': '{n} nodos',
  'estado.conexiones': '{n} conexiones',
  'lienzo.etiquetaConexionEj': 'Etiqueta de la conexión (ej. "Sí", "No", "Aprobado", o frecuencia):',
  'lienzo.etiquetaConexion': 'Etiqueta de la conexión:',
  'lienzo.etiquetaNodo': 'Etiqueta del nodo:',
  'nivel.vista': '**Vista {nombre}.** {desc}. Quedan **{n} pasos** de {total}. El proceso completo sigue guardado: cambiar de vista no pierde nada ni vuelve a llamar a la IA.',
  'nivel.info': '{n} de {total} pasos',
  // ---------------------------------------------------------------- Ingesta
  'grabacion.sinTranscripcion': 'No hay transcripción.',
  'grabacion.sinSoporte': 'Tu navegador no soporta reconocimiento de voz. Usa Chrome o Edge. También puedes pegar la transcripción manualmente.',
  'grabacion.detenido': 'detenido',
  'grabacion.grabando': 'grabando…',
  'fuentes.leyendoDocumentos': 'Leyendo documentos…',
  'fuentes.leyendo': 'Leyendo {i} de {n}: {nombre}',
  'fuentes.sinTexto': '{nombre}: no tiene texto legible',
  'fuentes.anadidos': '{que} · añade más o pulsa {boton}',
  'fuentes.unoAnadido': '1 documento añadido',
  'fuentes.variosAnadidos': '{n} documentos añadidos',
  'fuentes.combinarYGenerar': 'Combinar y generar',
  'fuentes.noLeidos': 'No se pudieron leer {n} archivo(s):\n\n{lista}',
  'fuentes.tagTexto': 'TEXTO',
  'fuentes.caracteres': '{n} car.',
  'fuentes.quitar': 'Quitar esta fuente',
  'fuentes.unaLista': '1 fuente lista',
  'fuentes.variasListas': '{n} fuentes listas para combinar',
  'fuentes.excede': 'Entre todas suman {total} caracteres y la IA lee hasta {max}: se recortará el final de las fuentes más largas. Quita las que no aporten o deja solo los capítulos del proceso.',
  'fuentes.combinarN': 'Combinar {n} fuentes y generar',
  'formatos.noCarga': 'No se pudo cargar {url} (¿sin conexión o CDN bloqueado?)',
  'formatos.noLeido': 'No se pudo leer el archivo.',
  'ingesta.generando': 'Generando…',
  'ingesta.cancelando': 'Cancelando…',
  'flujo.abriendo': 'Abriendo {nombre}...',
  'flujo.diagramaComoFuente': 'Diagrama añadido como fuente',
  'flujo.diagramaImportado': 'Diagrama importado',
  'flujo.bpmnImportado': '**BPMN importado desde {nombre}:** {n} elementos ({tareas} actividades, {compuertas} compuertas, {eventos} eventos) y {flujos} flujos.',
  'flujo.fuenteAnadida': 'Fuente añadida: {nombre}',
  'flujo.sinTexto': 'No hay texto que interpretar. Carga un archivo o pega el texto del proceso.',
  'flujo.interpretandoN': 'Interpretando con IA {n} caracteres... (puede tardar hasta 1 min)',
  'flujo.analizandoN': 'Analizando {n} caracteres...',
  'flujo.participantes': 'Participantes detectados: {n}. Definiendo roles...',
  'flujo.interpretando': 'Interpretando con IA...',
  'flujo.generadoIa': 'Proceso generado con IA',
  'flujo.interpretadoIa': '**Proceso interpretado con IA desde {etiqueta}.** {n} elementos con roles, sistemas y decisiones. Revisa el diagrama y completa la pestaña **Ficha**; luego exporta a **Ficha de Proceso**.',
  'flujo.excedia': '\n\nNota: el documento excedía {k}K caracteres, interpreté la primera parte. Si falta el final del proceso, pega esa sección y vuelve a generar.',
  'flujo.generado': 'Proceso generado',
  'flujo.basico': '**Proceso generado en modo básico (sin IA)** desde {etiqueta}. Las actividades se extrajeron por palabras clave: revisa roles y decisiones. Para interpretarlo con Claude, pon el código del equipo en Ajustes de IA (✨) y vuelve a generar.',
  'flujo.cancelado': 'Cancelado.',
  'flujo.consumio': '{error}\n\nEsta ejecución igual consumió {coste} a precio de lista.',
  'flujo.noSePudo': 'No se pudo completar:\n\n{error}',
  'flujo.cargandoPdf': 'Cargando el lector de PDF (solo la primera vez)…',
  'participantes.intervenciones': '{n} intervenciones',
  'participantes.queRol': '¿Qué rol cumple?',
  'participantes.intro': 'Detecté <b>{n} persona(s)</b> en la transcripción. Indica el <b>rol</b> de cada una: la IA usará el rol (no el nombre) como <b>carril</b> del flujo, que es lo correcto en un proceso.',
  'participantes.enBlanco': 'Deja en blanco a quien no participe en el proceso (p. ej. el consultor que facilita la reunión): se omitirá.',
  'participantes.titulo': '👥 ¿Quién es quién en la reunión?',
  'participantes.usar': 'Usar estos roles',
  'participantes.omitir': 'Omitir',
  'basico.sinActividades': 'No pude extraer actividades del texto. Intenta separar por puntos o bullets.',
  'basico.construido': 'He construido el flujograma desde la fuente **{fuente}**.\n\nDetecté **{n} actividades** (+ inicio/fin).\nPatrones aplicados: actividades con verbos en infinitivo/imperativo, gateways de decisión por condicionales ("si", "cuando", "en caso").\n\nRevisa, ajusta etiquetas y completa responsables. Cuando termines pídeme: *"detecta pains"* o *"sugiere KPIs"*.',
  'basico.recortado': '\n\n⚠️ **El documento era muy largo** ({total} actividades detectadas). Me quedé con las primeras {n} para que el diagrama siga siendo legible.\n\n**Recomendación:** configura la **IA (⚙ en la cabecera)** — interpreta el documento completo y arma el flujo real con roles y decisiones, en vez de esta extracción por palabras clave.',
  // ---------------------------------------------------------------- IA
  'ia.interpretando': '⏳ Interpretando con IA… (puede tardar unos segundos)',
  'ia.recibiendo': 'Recibiendo el proceso de la IA… {n} caracteres',
  'ia.sinActividades': 'La IA no devolvió un proceso con actividades.',
  'ia.coste': '\n\nCoste de esta ejecución: **{usd}** ({entrada} tokens de entrada y {salida} de salida, precio de lista de {modelo}).',
  'ia.sinProceso': 'No hay proceso que analizar.',
  'ia.analisisFallido': '**No se pudo completar el análisis:** {error}',
  'tareas.analizando': '_{tarea}: analizando el proceso con IA…_',
  'tareas.reintentar': '_Puedes reintentar o usar el modo básico._',
  'painsIa.sinIa': 'El análisis profundo de dolores usa la IA (Claude). Aún no configuraste tu API key. ¿Abrir Ajustes de IA?',
  'painsIa.analizando': '_Analizando el proceso en busca de dolores..._',
  'painsIa.detectados': '**{n} dolor(es) detectados en el flujo** (con evidencia del propio proceso):',
  'painsIa.puntaje': '  _(sev {sev} x frec {frec} = **{total}**)_',
  'painsIa.evidencia': '  - Evidencia: {texto}',
  'painsIa.impacto': '  - Impacto: {texto}',
  'painsIa.hipotesis': '**Hipótesis del sector - NO detectadas en este flujo, a validar con el cliente:**',
  'painsIa.donde': '   - Dónde mirar: {texto}',
  'painsIa.senal': '   - Cómo confirmarlo: {texto}',
  'painsIa.noAgregadas': '_Estas NO se agregaron al diagrama: son preguntas para el levantamiento, no hallazgos._',
  'codigo.intro': 'ProcessIQ interpreta el documento con <b>IA (Claude)</b> usando la clave del equipo. Escribe el <b>código de acceso</b> que te dio quien administra la herramienta: se guarda solo en este navegador y no se te volverá a pedir.',
  'codigo.etiqueta': 'Código de acceso del equipo',
  'codigo.sinCodigo': 'Sin código puedes seguir en <b>modo básico</b>: extrae actividades por palabras clave, sin IA.',
  'codigo.titulo': 'Interpretar con IA',
  'codigo.usarIa': 'Usar IA',
  'codigo.modoBasico': 'Modo básico',
  'profundidad.intro': 'El proceso se genera <b>completo</b> en cualquier caso. Esto define con cuánto detalle lo mira la IA y en qué vista se abre; podrás cambiar de vista cuando quieras con el selector <b>Nivel de detalle</b>, sin volver a generar.',
  'profundidad.ejecutivo': 'Los hitos y las decisiones. Para comité o SteerCo.',
  'profundidad.actividad': 'Lo que hace cada rol de principio a fin. El equilibrio habitual.',
  'profundidad.detalle': 'Cada paso operativo. Para manual de procedimientos o automatización.',
  'profundidad.modelo': 'Modelo de IA',
  'profundidad.opus': 'Máxima calidad de interpretación. Para procedimientos largos, ambiguos o con muchas decisiones.',
  'profundidad.sonnet': 'Más rápido y 2,5 veces más barato por token. Suele bastar con textos claros y bien estructurados.',
  'profundidad.tituloModelo': 'Nivel de detalle y modelo',
  'profundidad.titulo': 'Nivel de detalle del levantamiento',
  'profundidad.estimado': 'Estimado: {min} – {max}',
  'profundidad.costeEstimado': 'Coste estimado de esta ejecución: <b>{min} – {max}</b>',
  'profundidad.costeDetalle': 'Máximo posible {tope}, si la IA usa toda la respuesta ({tokens} tokens). {modelo} a precio de lista: US$ {entrada} por millón de tokens de entrada y US$ {salida} de salida; ~{tokensEntrada} tokens de entrada.',
  'profundidad.ajustadoUna': 'Rango ajustado con {n} ejecución real de este nivel en este navegador.',
  'profundidad.ajustadoVarias': 'Rango ajustado con {n} ejecuciones reales de este nivel en este navegador.',
  'profundidad.inicial': 'Estimación inicial: se afina con tus ejecuciones reales.',
  'profundidad.generar': 'Generar',
  'ajustesIa.proyecto': 'IA del proyecto',
  'ajustesIa.entendido': 'Entendido',
  'ajustesIa.intro': 'ProcessIQ usa el <b>API de Anthropic (Claude)</b>. En <b>modo equipo</b> la clave vive en el intermediario de MBC y en este navegador solo se guarda tu código de acceso. Con <b>tu propia API key</b>, la key se guarda solo en este navegador y va directo a Anthropic.',
  'ajustesIa.modo': 'Modo',
  'ajustesIa.modoEquipo': 'Clave del equipo (intermediario MBC)',
  'ajustesIa.modoPropia': 'Mi propia API key',
  'ajustesIa.direccion': 'Dirección del intermediario',
  'ajustesIa.codigoPista': 'El código te lo da quien administra ProcessIQ. La clave de Anthropic vive en el intermediario: tu navegador nunca la ve.',
  'ajustesIa.apiKey': 'API key de Anthropic',
  'ajustesIa.apiKeyPista': 'La obtienes en <b>console.anthropic.com → API Keys</b>. Empieza con <code>sk-ant-</code>.',
  'ajustesIa.modelo': 'Modelo',
  'ajustesIa.probar': 'Probar conexión',
  'ajustesIa.byok': '⚠️ Modo BYOK: úsalo para trabajo interno o demos. Para un link público compartido, conviene un proxy con la key en el servidor.',
  'ajustesIa.titulo': '⚙ Ajustes de IA (Claude)',
  'ajustesIa.guardar': 'Guardar',
  'ajustesIa.probando': '⏳ Probando…',
  'ajustesIa.correcta': '✓ Conexión correcta',
  'ajustesIa.respondio': '✓ Respondió: {texto}',
  'modoIa.servidor': 'Se interpretará con <b>IA en el servidor</b>: reconstruye actividades, roles y decisiones, y el resultado se guarda en el proyecto.',
  'modoIa.servidorNo': 'La IA del servidor no está disponible ahora; se usará el <b>modo básico</b> por palabras clave.',
  'modoIa.modelo': 'Se interpretará con <b>IA ({modelo})</b>: reconstruye actividades, roles y decisiones.',
  'modoIa.equipo': 'Se interpretará con <b>IA (Claude)</b> usando la clave del equipo. Al generar te pediremos el código de acceso; sin él seguirá el <b>modo básico</b> por palabras clave.',
  // ---------------------------------------------------------------- Copiloto
  'copiloto.saludo': '¡Hola! Soy tu copiloto **ProcessIQ**.\n\nEstoy aquí para ayudarte a levantar, diagnosticar y reingenierizar procesos más rápido.\nEmpieza completando el **nombre, industria y macroproceso** arriba, y luego usa las acciones rápidas o pídeme algo en lenguaje natural.\n\nEjemplo: *"Levanta el proceso de gestión de reclamos para un banco minorista peruano."*',
  'copiloto.autor': 'ProcessIQ · IA',
  'copiloto.tareaIa': '{tarea} (IA).',
  'copiloto.generarTitulo': 'Generar proceso desde descripción',
  'copiloto.generarEjemplo': 'Describe el proceso a levantar...',
  'copiloto.generarPedido': 'Generar proceso: {desc}',
  'copiloto.pedido.detectPains': 'Detecta pains en el diagrama actual.',
  'copiloto.pedido.suggestKpis': 'Sugiere KPIs aplicables.',
  'copiloto.pedido.proposeTobe': 'Propón reingeniería to-be.',
  'copiloto.pedido.raci': 'Generar matriz RACI.',
  'copiloto.pedido.sipoc': 'Generar SIPOC del proceso.',
  'copiloto.pedido.impactEffort': 'Generar matriz impacto-esfuerzo.',
  'copiloto.pedido.whatif': 'Comparar escenarios What-If.',
  'copiloto.pedido.automation': 'Detectar oportunidades de automatización.',
  'copiloto.pedido.bottleneck': 'Identificar cuello de botella y ruta crítica.',
  'copiloto.pedido.variants': 'Analizar variantes del proceso.',
  'copiloto.pedido.valueMap': 'Mostrar mapa de valor Lean (VA/NVA).',
  'copiloto.pedido.backlog': 'Generar backlog de iniciativas.',
  'copiloto.pedido.execSummary': 'Resumen ejecutivo del diagnóstico.',
  'copiloto.pedido.mergeGateways': 'Insertar compuertas de convergencia.',
  'copiloto.pedido.aiPains': 'Análisis profundo de dolores (IA).',
  'copiloto.pedido.autofit': 'Autoajustar el diagrama.',
  'copiloto.pedido.relayout': 'Reorganizar el diagrama.',
  'copiloto.reorganizado': '**Diagrama reorganizado.** {disposicion} Carriles ordenados para minimizar cruces y retornos de reproceso por corredor inferior.',
  'copiloto.envolvente': 'Modo envolvente activo: {bandas} bandas de hasta {columnas} columnas (evita el diagrama kilométrico).',
  'copiloto.unaBanda': 'Disposición en una sola banda.',
  // ---------------------------------------------------------------- Exportar, BPMN y validaciones
  'exportar.jsonInvalido': 'Archivo JSON inválido.',
  'exportar.sinProcesoFicha': 'No hay proceso para generar la ficha.',
  'exportar.fichaTitulo': '📋 Ficha de Proceso · vista previa',
  'exportar.descargarWord': '⬇️ Descargar Word',
  'exportar.sinPptx': 'La librería PPTX no se cargó (¿estás offline?). Conecta a internet o usa export SVG/PNG.',
  'exportar.sinProceso': 'No hay proceso para exportar.',
  'exportar.sinProcesoWord': 'No hay proceso para documentar.',
  'bpmn.carriles': 'Carriles: {lista}.',
  'bpmn.unSubproceso': 'Un subproceso con contenido',
  'bpmn.subprocesos': '{n} subprocesos con contenido',
  'bpmn.subprocesosNiveles': ': se ve desplegado en el nivel Detalle y plegado en Actividad y Ejecutivo.',
  'lint.vacio': 'Genera o dibuja un proceso para validar.',
  'lint.cero': '¡Cero issues! El proceso cumple el playbook MBB.',
  'lint.scoreSin': 'Score MBB · sin issues',
  'lint.score': 'Score MBB',
  'lint.crit': '{n} crit',
  'lint.alto': '{n} alto',
  'lint.medio': '{n} medio',
  'lint.bajo': '{n} bajo',
  'lint.detectado': '{n} issue detectado',
  'lint.detectados': '{n} issues detectados',
  'lint.irAlNodo': '→ click para ir al nodo',
  // ---------------------------------------------------------------- Simulador, ejemplos, autoajuste y minería
  'sim.sinActividades': 'Necesito actividades en el diagrama primero.',
  'sim.wizardIntro': 'Captura tiempo y volumen para cada actividad. Los verdes ya tienen datos, los amarillos están vacíos. Tab/Enter para avanzar rápido.',
  'sim.colActividad': 'Actividad',
  'sim.colResponsable': 'Responsable',
  'sim.colTiempo': 'Tiempo (min)',
  'sim.colVolumen': 'Volumen/mes',
  'sim.ejemplo': 'ej. {n}',
  'sim.wizardTitulo': '⚡ Wizard de tiempos · {n} actividades',
  'sim.capturados': 'Capturé tiempos/volúmenes en {n} actividades. Simulación actualizada automáticamente.',
  'sim.sinProceso': 'Sin proceso. Genera o dibuja uno primero.',
  'sim.sinDatos': '⚠ Ninguna actividad tiene tiempo y volumen. Completa esos campos en Props.',
  'sim.conDatos': 'Actividades con datos',
  'sim.esfuerzo': 'Esfuerzo total / mes',
  'sim.fteActual': 'FTE actual',
  'sim.leadTime': 'Lead time del flujo (suma)',
  'sim.costoMensual': 'Costo mensual de operación',
  'sim.fteToBe': 'FTE to-be (-{pct}%)',
  'sim.ahorro': 'Ahorro anual estimado',
  'sim.liberados': '{n} FTE liberados',
  'ejemplos.intro': 'Elige un proceso de ejemplo pre-cargado (con pains, KPIs y simulación) para explorar las capacidades.',
  'ejemplos.titulo': 'Procesos de ejemplo',
  'autoajuste.sinDiagrama': 'No hay diagrama que ajustar.',
  'autoajuste.titulo': '**Diagrama autoajustado.**\n\n',
  'autoajuste.limpio': 'Sin flechas sobre cajas ni cruces. Disposición: {disposicion}, {carriles} carriles.\n\n',
  'autoajuste.bandas': '{bandas} bandas de hasta {columnas} columnas',
  'autoajuste.unaBanda': 'una sola banda',
  'autoajuste.defectos': 'Quedan **{sobreCajas} flecha(s) sobre cajas** y **{cruces} cruce(s)**; es la mejor de {variantes} disposiciones probadas. Suele deberse a varias ramas que apuntan al mismo nodo final.\n\n',
  'autoajuste.tamano': 'Tamaño: {ancho} × {alto} px. Pulsa **deshacer** (Ctrl+Z) si prefieres la disposición anterior.',
  'mineria.filas': '\n({n} filas totales)',
  'mineria.ninguna': '(ninguna)',
  'mineria.completado': '**Process discovery completado** desde event log.\n\n• **{casos} casos** analizados\n• **{actividades} actividades únicas** detectadas\n• **{transiciones} transiciones** descubiertas (mostrando las más frecuentes)\n• Top inicio: *{inicio}*\n• Top fin: *{fin}*\n\nEl número en cada conexión = frecuencia observada. Las actividades con alta frecuencia que reaparecen son indicio de **reprocesos** (pain candidato).',
  // ---------------------------------------------------------------- Vistas As-Is / To-Be
  'vistas.indicadorToBe': 'TO-BE · REINGENIERÍA',
  'vistas.sinAsIs': 'Genera o dibuja un proceso As-Is primero.',
  'vistas.nadaQueClonar': 'No hay un As-Is que clonar.',
  'vistas.clonado': 'Cloné el As-Is al To-Be. Ahora puedes editar el flujo sin afectar el original.\n\n**Sugerencias de reingeniería rápidas:**\n• Elimina nodos de control duplicado.\n• Marca actividades manuales como **sistema** (automatización).\n• Une handoffs en una célula multifuncional.\n• Mueve decisiones a reglas codificadas (DMN).\n\nCuando termines, exporta a PPTX — incluiré un slide comparativo lado a lado.',
  'tobe.operativo.label': 'Operativo — Quick wins',
  'tobe.operativo.desc': 'Automatiza tareas manuales repetitivas, elimina reprocesos. Cambios de bajo riesgo, 0-3 meses.',
  'tobe.tactico.label': 'Táctico — Rediseño de flujo',
  'tobe.tactico.desc': 'Elimina handoffs, paraleliza, consolida controles duplicados. 3-9 meses.',
  'tobe.estrategico.label': 'Estratégico — Reimaginar',
  'tobe.estrategico.desc': 'Self-service digital, elimina pasos sin valor, repensar el proceso end-to-end. 9-18 meses.',
  'tobe.intro': 'ProcessIQ clona el As-Is y aplica palancas de reingeniería según el <strong>nivel</strong> elegido. Luego puedes editar manualmente el resultado.',
  'tobe.nivel': 'Nivel de transformación',
  'tobe.cambios': 'Cambios específicos (opcional)',
  'tobe.cambiosEjemplo': 'Ej. \'Eliminar la validación manual del paso 3\', \'Añadir autoservicio en la captura\'…',
  'tobe.titulo': '✨ Transformar a To-Be por nivel',
  'tobe.sinAsIs': 'No hay As-Is que transformar.',
  'tobe.automatizada': 'Automatizada: "{etiqueta}" → {tipo}',
  'tobe.digitalizada': 'Digitalizada: "{etiqueta}" → User Task (sistema)',
  'tobe.decision': 'Decisión "{etiqueta}" → regla codificada (DMN)',
  'tobe.selfService': 'Self-service: "{etiqueta}"',
  'tobe.ia': 'IA-assisted: "{etiqueta}" → Script/IA Task',
  'tobe.manuales': 'Cambios manuales solicitados: {cambios}',
  'tobe.generado': '**To-Be generado · nivel {nivel}**\n\n{desc}\n\n**{n} cambio(s) aplicado(s):**\n',
  'tobe.sinCambios': '• Sin cambios automáticos — edita manualmente.',
  'tobe.yMas': '\n• …y {n} más.',
  'tobe.editaManual': '\n\nEdita manualmente cualquier nodo en Props. Exporta a PPTX para el comparativo As-Is vs To-Be.',
  // ---------------------------------------------------------------- Paneles: pains, propiedades y KPIs
  'pains.describe': 'Describe el pain.',
  'pains.selecciona': 'Selecciona un nodo para capturar sus pain points.',
  'pains.sinPains': 'Sin pains capturados aún.',
  'pains.meta': 'Sev {sev} · Frec {frec} · Score {score}',
  'pains.eliminar': 'Eliminar',
  'props.larga': 'Demasiado larga ({car} car, {pal} pal). Máx 50 car / 8 palabras — considera descomponer.',
  'props.fueraCatalogo': '"{verbo}" no está en el catálogo MBB. Prefiere: registrar, validar, aprobar, escalar, notificar, calcular…',
  'props.namingOk': 'Naming OK · verbo permitido + longitud adecuada',
  'kpis.sinCoincidencias': 'Sin coincidencias.',
  'kpis.benchmark': 'Benchmark: {valor}',
  'kpis.valorActual': 'Valor actual:',
  'kpis.gap': 'Gap:',
  'kpis.benchmarkSectorial': 'Benchmark sectorial: {valor}',
  'kpis.valorCliente': 'Valor actual del cliente',
  'kpis.valorEjemplo': 'ej. 6.2',
  'kpis.gapBenchmark': 'Gap vs benchmark (calculado o manual)',
  'kpis.gapEjemplo': 'ej. -2.2 pp (por encima del benchmark)',
  'kpis.fuente': 'Fuente del dato',
  'kpis.fuenteEjemplo': 'ej. Dashboard SBS, reporte interno BO 04/2026',
  'kpis.capturadosPista': 'Los KPIs capturados aparecen en el slide PPTX con su gap. El gap se calcula automáticamente si valor y benchmark son numéricos.',
  'kpis.capturarTitulo': 'Capturar valor actual · KPI',
  'kpis.capturado': 'KPI capturado: **{kpi}** = {valor} (gap {gap}). Se incluirá en el slide de KPIs del PPTX.',
  // ---------------------------------------------------------------- Copiloto sin IA: comandos y respuestas por reglas
  'comando.noActividad': 'No encontré la actividad "{nombre}". Verifica el nombre.',
  'comando.agregadoDespues': '✅ Agregué "{nuevo}" después de "{ref}".',
  'comando.agregadoAntes': '✅ Agregué "{nuevo}" antes de "{ref}".',
  'comando.noEliminar': 'No encontré "{nombre}" para eliminar.',
  'comando.eliminado': '✅ Eliminé "{nombre}" y reconecté el flujo.',
  'comando.noRenombrar': 'No encontré "{nombre}" para renombrar.',
  'comando.renombrado': '✅ Renombré "{antes}" → "{ahora}".',
  'comando.noEncontre': 'No encontré "{nombre}".',
  'comando.conectado': '✅ Conecté "{a}" → "{b}".',
  'comando.yaExiste': 'Ya existe esa conexión.',
  'comando.marcada': '✅ "{nombre}" marcada como {tipo}.',
  'heur.generado': 'He generado un proceso as-is con **{n} actividades** basado en patrones APQC PCF + playbook MBB.\n\nSugerencias inmediatas:\n• Completa los **responsables** y **sistemas soporte** en cada actividad.\n• Captura **pain points** (handoffs, esperas, reprocesos) — son el insumo del diagnóstico.\n• Revisa la pestaña **KPIs** para vincular indicadores sectoriales.\n\n¿Quieres que detecte pains típicos del sector?',
  'heur.sinDiagrama': 'No hay un diagrama aún. Genera o dibuja un proceso primero.',
  'heur.diagnostico': '**Diagnóstico automático del as-is**\n\n• **{handoffs} handoff(s)** detectados entre roles distintos. Cada handoff agrega ~10-15% de lead time y riesgo de pérdida de información.\n• **{decisiones} punto(s) de decisión**. Si carecen de criterios documentados, son fuente de variabilidad e inequidad.\n• **{manual} actividad(es) sin sistema soporte** — candidatas a automatización (RPA / workflow).\n\n**Pain points típicos del sector {industria}:**\n',
  'heur.defineIndustria': '(define industria)',
  'heur.banca': '• Reproceso por documentación incompleta del cliente.\n• Tiempos de respuesta heterogéneos según canal.\n• Validaciones manuales duplicadas entre frontline y back office.',
  'heur.retail': '• Quiebres de stock por baja sincronización tienda-CD.\n• Devoluciones sin trazabilidad financiera.\n• Promociones ejecutadas con desfase entre canales.',
  'heur.manufactura': '• Paradas no planificadas por mantenimiento reactivo.\n• Inventario en proceso sobre-dimensionado.\n• Calidad detectada al final de línea, no en estación.',
  'heur.publico': '• Trámites con múltiples ventanillas (one-stop-shop ausente).\n• Documentación física que duplica registros digitales.\n• Plazos TUPA incumplidos por handoffs inter-áreas.',
  'heur.sinIndustria': '• Define la industria del proceso para sugerencias específicas.',
  'heur.kpis': '**KPIs recomendados** para {para}{macro}:\n\n',
  'heur.tuProceso': 'tu proceso',
  'heur.kpisPie': '\nRevisa la pestaña **KPIs** para ver la librería completa y hacer click en cada uno para agregarlo al diagnóstico.',
  'heur.sinAsIs': 'Necesito un diagrama as-is para proponer el to-be.',
  'heur.tobe': '**Propuesta de reingeniería (to-be)**\n\nLectura del as-is: {n} actividades, {handoffs} handoffs entre roles, {manual} sin sistema, {pains} pains capturados.\n\n**Palancas sugeridas:**\n1. **Automatización RPA** en las {manual} actividades sin sistema soporte → ahorro estimado 0.3-0.5 FTE por actividad de alto volumen.\n2. **Eliminar handoffs** mediante célula multifuncional o workflow orquestado → reducción 20-30% en lead time.\n3. **Self-service / canal digital** en las actividades de captura → reducción 40-60% en errores de origen.\n4. **Reglas de decisión codificadas** (DMN / motor de reglas) en los puntos de gateway → consistencia y trazabilidad.\n5. **KPIs en tiempo real** con dashboard único → ciclos de mejora mensuales en lugar de trimestrales.\n\n**Beneficios estimados** (rango referencia industria):\n• Lead time: -35% a -50%\n• FTE liberados: 15-25% de la dotación actual\n• Calidad (errores): -60%\n• CSAT/NPS: +10 a +20 puntos\n\nDime "dibuja el to-be" si quieres que genere la versión optimizada en un nuevo lienzo.',
  'heur.nombreVacio': '[Nombre del proceso]',
  'heur.industriaVacia': '[Industria]',
  'heur.macroVacio': '[Macroproceso]',
  'heur.resumen': '**RESUMEN EJECUTIVO — DIAGNÓSTICO DE PROCESO**\n\n**Proceso:** {nombre}\n**Industria / Macroproceso:** {industria} · {macro}\n\n**Hallazgos clave:**\n• El proceso comprende {n} actividades con {handoffs} handoffs inter-rol.\n• Se identificaron {pains} pain points ({criticos} críticos, severidad ≥ 4).\n• Existe oportunidad de automatización en actividades sin sistema soporte.\n\n**Recomendaciones priorizadas:**\n1. Quick wins (0-3 meses): estandarización de criterios de decisión + eliminación de controles duplicados.\n2. Mediano plazo (3-9 meses): automatización RPA/IDP en actividades manuales de alto volumen.\n3. Estructural (9-18 meses): rediseño organizacional hacia células multifuncionales + dashboard en tiempo real.\n\n**Impacto estimado:**\nLead time -40%, FTE liberados 15-25%, mejora de CSAT/NPS doble dígito.\n\n**Próximo paso sugerido:**\nValidar hallazgos con sponsor, priorizar oportunidades en matriz impacto-esfuerzo, y construir business case.',
  'heur.hola': '¡Hola! ¿En qué proceso te ayudo hoy?',
  'heur.interpretando': 'Interpretando tu descripción con IA…',
  'heur.generico': 'Entiendo tu pedido. En el MVP el copiloto trabaja con plantillas locales — al conectar Claude API en v1 daré respuestas contextualizadas a tu diagrama, industria y entregables previos del área.\n\nPrueba con las acciones rápidas arriba: generar, detectar pains, sugerir KPIs, to-be, o resumen ejecutivo.',
  'convergencia.ninguna': 'No encontré convergencias que necesiten compuerta de cierre: las ramas de este proceso terminan en fines distintos o ya convergen en una compuerta.',
  'convergencia.insertadas': '**{n} compuerta(s) de convergencia insertada(s).**\n\nDonde varias ramas volvían a juntarse en una actividad, ahora se dibuja la compuerta de cierre (✕) — es lo que exige el BPMN riguroso y lo que esperan ver los comités.\n\nNodos: {antes} → {despues}. Si prefieres el merge implícito, usa **deshacer** (Ctrl+Z).',
  // ---------------------------------------------------------------- Analítica avanzada, RACI, SIPOC e impacto-esfuerzo
  'analitica.sinActividades': 'No hay actividades para analizar.',
  'cuello.sinDatos': 'Captura **tiempo** y **volumen** en las actividades (pestaña Props o wizard del simulador) para detectar el cuello de botella.',
  'cuello.titulo': '**🔴 Análisis de cuello de botella y ruta crítica**\n\n',
  'cuello.cuello': '**Cuello de botella:** "{etiqueta}" — carga de **{horas} h/mes** ({min} min × {casos} casos). Es la actividad que más capacidad consume; cualquier mejora aquí tiene el mayor impacto en throughput.\n\n',
  'cuello.top': '**Top 3 por carga:**\n',
  'cuello.topFila': '{i}. {etiqueta} — {horas} h/mes',
  'cuello.ruta': '**Ruta crítica** ({min} min de lead time): {ruta}.\n\n',
  'cuello.recomendacion': 'Recomendación: ataca primero el cuello (automatizar, paralelizar o redistribuir carga) y acorta la ruta crítica eliminando esperas/handoffs.',
  'autom.nada': 'No detecté tareas claramente automatizables. Asegúrate de tener actividades manuales con tiempo y volumen capturados.',
  'autom.intro': '{n} actividad(es) con potencial de automatización, ordenadas por ahorro anual estimado.',
  'autom.tecnologia': 'Tecnología',
  'autom.ahorroAnio': 'Ahorro/año',
  'autom.esfuerzo': 'Esfuerzo',
  'autom.potencial': '<b>Potencial total:</b> {fte} FTE liberados · <b style="color:#1E7E34">{ahorro}/año</b>',
  'autom.titulo': '🤖 Oportunidades de automatización',
  'autom.mensaje': 'Detecté **{n} oportunidades de automatización** con potencial de **{fte} FTE** y **{ahorro}/año**. Top candidato: "{etiqueta}" ({tecnologia}). Úsalo para priorizar el roadmap de RPA/IDP/IA.',
  'variantes.sinVariantes': 'No hay variantes para analizar. Ingresa un **event log CSV** (📥 Ingestar → Event Log) — las variantes se calculan de los casos reales.',
  'variantes.intro': '<b>{n} variantes</b> en {total} casos. La variante #1 es el "happy path"; las demás son excepciones/reprocesos — fuente directa de pains.',
  'variantes.secuencia': 'Secuencia',
  'variantes.pasos': 'Pasos',
  'variantes.casos': 'Casos',
  'variantes.resumen': '<b>Happy path:</b> {pct}% de los casos ({n}). <b>Excepciones:</b> {excepciones} variantes cubren el {resto}% restante — revisar para estandarizar y reducir reprocesos.',
  'variantes.titulo': '🔀 Análisis de variantes',
  'variantes.mensaje': '**{n} variantes** detectadas. El happy path cubre {pct}% de los casos; el resto son excepciones (candidatas a estandarización). Mientras más variantes, mayor variabilidad e indisciplina del proceso.',
  'valor.sinActividades': 'No hay actividades para mapear.',
  'valor.desactivado': 'Mapa de valor desactivado — vuelve a colores por tipo de tarea.',
  'valor.activado': '**♻ Mapa de valor Lean activado** (verde=VA · amarillo=BVA · rojo=NVA · gris=sin clasificar)\n\n**Reparto de carga por valor:**\n• 🟢 Valor Añadido (VA): **{va}%**\n• 🟡 Necesario sin valor (BVA): **{bva}%**\n• 🔴 Desperdicio (NVA): **{nva}%** — {n} actividad(es)\n',
  'valor.sinClasificar': '• ⚪ Sin clasificar: {pct}% ({n} actividades — asigna VA/BVA/NVA en Props)\n',
  'valor.diagnostico': '\n**Diagnóstico Lean:** {texto}\n\nVuelve a pulsar para desactivar el mapa.',
  'valor.alto': 'Alto desperdicio — prioriza eliminar/automatizar las actividades NVA.',
  'valor.moderado': 'Desperdicio moderado — revisa las actividades NVA.',
  'valor.nada': 'Sin desperdicio clasificado. Asigna VA/BVA/NVA para el análisis Lean.',
  'backlog.sinInsumos': 'No hay insumos para el backlog. Captura pains, ten actividades manuales o KPIs con gap.',
  'backlog.fuenteAutomatizacion': 'Automatización',
  'backlog.intro': '{n} iniciativas consolidadas de pains, automatización y gaps de KPI, priorizadas por ratio impacto/esfuerzo.',
  'backlog.fuente': 'Fuente',
  'backlog.iniciativa': 'Iniciativa',
  'backlog.esf': 'Esf',
  'backlog.horizonte': 'Horizonte',
  'backlog.beneficio': 'Beneficio',
  'backlog.exportar': '⤓ Exportar backlog (CSV)',
  'backlog.titulo': '📋 Backlog de iniciativas · {n}',
  'backlog.mensaje': '**Backlog de {n} iniciativas** generado y priorizado. {rapidos} quick wins (0-3m). Fuentes: {pains} pains, {autom} automatización, {kpi} KPI. Úsalo como roadmap de transformación.',
  'whatif.sinProceso': 'Genera un proceso primero.',
  'whatif.sinDatos': '⚠ Ninguna actividad tiene tiempo y volumen. Captura datos (wizard del simulador) para que la comparación tenga cifras.',
  'whatif.intro': 'Selecciona las palancas para construir un <b>escenario To-Be</b> y compáralo contra el As-Is actual.',
  'whatif.reduccion': 'Reducción adicional de lead time esperada (%)',
  'whatif.titulo': '🔬 Comparador de escenarios What-If',
  'whatif.aplicadas': '{n} palanca(s) aplicada(s). Comparación As-Is vs escenario To-Be:',
  'whatif.metrica': 'Métrica',
  'whatif.leadTime': 'Lead time (min)',
  'whatif.costoMensual': 'Costo mensual',
  'whatif.ahorro': 'Ahorro anual del escenario',
  'whatif.liberados': '{fte} FTE liberados · lead time −{pct}%',
  'whatif.resultado': '🔬 Resultado What-If',
  'whatif.mensaje': '**Escenario What-If:** con {n} palanca(s), el proceso pasa de {de} a {a} FTE (ahorro {ahorro}/año) y reduce lead time ~{pct}%. Compara varios escenarios para elegir el de mejor relación impacto/esfuerzo.',
  'raci.sinActividades': 'Necesito actividades en el diagrama para generar RACI.',
  'raci.r': 'R · Responsable',
  'raci.c': 'C · Consulta',
  'raci.i': 'I · Informado',
  'raci.pista': 'R=Responsable · A=Accountable · C=Consultado · I=Informado. La matriz se exportará al PPTX automáticamente.',
  'raci.titulo': 'Matriz RACI · {nombre}',
  'raci.proceso': 'Proceso',
  'raci.guardada': 'Matriz RACI guardada con {n} actividades × {roles} roles. Se incluirá en el próximo export PPTX.',
  'sipoc.sinProceso': 'Genera o dibuja un proceso primero.',
  'sipoc.pista': 'SIPOC pre-llenado desde el diagrama (roles, data nodes). Edita libremente. Se incluirá en el PPTX.',
  'sipoc.guardado': 'SIPOC guardado. Se exportará junto al PPTX.',
  // RACI y SIPOC con IA como matrices editables (divergencia D11)
  'matriz.armando': '_{tarea}: armando la matriz editable con IA…_',
  'matriz.alInforme': '_No se pudo armar la matriz editable ({error}). Pido el informe en texto._',
  'matriz.sinResultado': 'el servidor no devolvió la matriz',
  'matriz.guardar': 'Guardar cambios',
  'raci.generadaIa': 'Matriz RACI propuesta por la IA con {n} actividades × {roles} roles. Ya quedó en el proceso y se incluirá en el PPTX: revísala y ajusta lo que haga falta.',
  'raci.pistaIa': 'Propuesta de la IA: revisa cada celda (un solo A por actividad; R es quien ejecuta). R=Responsable · A=Accountable · C=Consultado · I=Informado. La matriz se exportará al PPTX automáticamente.',
  'sipoc.generadoIa': 'SIPOC propuesto por la IA. Ya quedó en el proceso y se incluirá en el PPTX: revísalo y ajusta lo que haga falta.',
  'sipoc.pistaIa': 'SIPOC propuesto por la IA a partir del proceso. Edita libremente. Se incluirá en el PPTX.',
  'impacto.sinPains': 'Captura pains primero (selecciona un nodo → tab Pains).',
  'impacto.estrategicos': 'PROYECTOS ESTRATÉGICOS',
  'impacto.reconsiderar': 'RECONSIDERAR',
  'impacto.esfuerzo': '→ Esfuerzo',
  'impacto.impacto': '→ Impacto',
  'impacto.leyenda': 'Leyenda',
  'impacto.sevFrec': '(sev {sev} · frec {frec})',
  'impacto.titulo': 'Matriz Impacto · Esfuerzo · {n} pains',
  'impacto.lista': 'Matriz impacto-esfuerzo lista con {n} oportunidades. Quick wins (alto impacto / bajo esfuerzo) = candidatos para fase 0-3 meses.',
  // ---------------------------------------------------------------- Plataforma: proceso de un proyecto
  'proyecto.sinCatalogos': 'No se pudieron cargar los catálogos de la organización: se usan los de por defecto.',
  'proyecto.laVersion': 'la v{n}',
  'proyecto.procesoVacio': 'el proceso vacío',
  'proyecto.tienesCambios': 'Tienes cambios sin guardar',
  'proyecto.cambiosSinGuardar': 'Cambios sin guardar',
  'proyecto.borradorOtra': 'En este navegador hay cambios sobre {version} de este proceso que no se guardaron en el proyecto (último cambio: {fecha}). Si abres {abres}, se perderán.',
  'proyecto.estaVersion': 'esta versión',
  'proyecto.borradorMisma': 'En este navegador hay cambios sobre esta versión que no se guardaron en el proyecto (último cambio: {fecha}).',
  'proyecto.seguirConMios': 'Seguir con mis cambios sobre {version}',
  'proyecto.recuperar': 'Recuperar mis cambios',
  'proyecto.descartarlos': 'Descartarlos',
  'proyecto.noEncontrado': 'No se encontró ese proceso o no tienes acceso a él.',
  'proyecto.noAbierto': 'No se pudo abrir el proceso.',
  'proyecto.archivado': 'El proyecto está archivado: puedes ver el proceso, pero no guardar cambios.',
  'proyecto.rolSinGuardar': 'Tu rol en el proyecto ({rol}) no permite guardar revisiones: los cambios que hagas aquí no se guardarán en el proyecto.',
  'proyecto.noEsLaUltima': 'Estás trabajando sobre la v{base}, pero la última es la v{ultima}: la versión nueva no incluirá los cambios de la v{ultima}.',
  'proyecto.conErrores': 'El proceso tiene errores y no se puede guardar:',
  'proyecto.guardadaIa': 'Proceso generado con IA y guardado',
  'proyecto.guardada': 'Guardada',
  'proyecto.conflicto': '{que} como v{n}. Mientras trabajabas, alguien guardó la v{otra}: esta versión no incluye esos cambios. Revisa las dos en el proyecto.',
  'proyecto.guardadaComo': '{que} como v{n} (borrador).',
  'proyecto.sesionCaducada': 'Tu sesión caducó. Tus cambios siguen guardados en este navegador: entra de nuevo y vuelve a pulsar «Guardar revisión».',
  'proyecto.entrar': 'Entrar',
  'proyecto.noGuardado': 'No se pudo guardar.',
  'proyecto.iaSoloLectura': 'Tu rol o el estado del proyecto no permiten usar la IA aquí.',
  'proyecto.mensajeIa': 'Proceso generado con IA desde {etiqueta}',
  'proyecto.pendienteTitulo': 'Hay un proceso generado con IA sin guardar',
  'proyecto.pendienteTexto': 'El {fecha} la IA generó este proceso desde «{etiqueta}», pero no llegó a guardarse en el proyecto (se cerró la pestaña antes). ¿Lo dibujamos ahora? Se guardará como una versión nueva; las anteriores no cambian.',
  'proyecto.dibujarlo': 'Dibujarlo y guardarlo',
  'proyecto.descartarlo': 'Descartarlo',
  'barra.aria': 'Proceso del proyecto',
  'barra.volver': 'Volver al proyecto',
  'barra.guardarTitulo': 'Crea una versión nueva en el proyecto (Ctrl+S)',
  'barra.guardar': 'Guardar revisión',
  'barra.noAbierto': 'No se pudo abrir el proceso',
  'barra.abriendo': 'Abriendo el proceso…',
  'barra.proyecto': 'Proyecto',
  'barra.laUltima': 'la última es la v{n}',
  'barra.sinRevisiones': 'sin revisiones todavía',
  'barra.tuRol': 'tu rol: {rol}',
  'barra.soloLectura': 'solo lectura',
  'barra.guardando': 'Guardando…',
  'barra.cerrarAviso': 'Cerrar aviso',
  'guardar.texto': 'Se creará la v{n} de «{nombre}», en borrador. Las versiones anteriores no cambian.',
  'guardar.campo': '¿Qué cambiaste? (opcional, lo verá el equipo)',
  'catalogos.pptxCliente': 'PPTX · cliente {nombre}',
  'catalogos.temaOrganizacion': 'tema de la organización',
  'colab.dondeAmbos': 'en el editor y en la página del proceso',
  'colab.dondeEditor': 'en el editor',
  'colab.dondeShell': 'en la página del proceso',
  'colab.dos': '{a} y {b}',
  'colab.varios': '{a} y {n} más',
  'colab.guardasteOtra': 'Guardaste la v{n} desde otra pestaña',
  'colab.guardo': '{autor} guardó la v{n}',
  'colab.tusCambiosSobre': 'Tienes cambios sin guardar sobre la v{n}: si cargas la nueva versión, se perderán.',
  'colab.tusCambios': 'Tienes cambios sin guardar: si cargas la nueva versión, se perderán.',
  'colab.cargarNueva': 'Cargar la nueva versión',
  'colab.seguirMia': 'Seguir con la mía',
  'colab.perderasSobre': 'Si cargas la v{n}, se perderán los cambios que hiciste sobre la v{base}.',
  'colab.perderas': 'Si cargas la v{n}, se perderán los cambios que hiciste.',
  'colab.conservarlos': 'Si prefieres conservarlos, sigue con la tuya y guárdala como una versión nueva: quedará marcada como conflicto y podrás revisar las dos en el proyecto.',
  'colab.cargarYDescartar': 'Cargar la v{n} y descartar mis cambios',
  'colab.tambien': 'También tienen abierto este proceso',
  'colab.editandoEn': '{nombre}: editando {donde}',
  'colab.viendoEn': '{nombre}: viendo {donde}',
  'colab.estaEditando': '{quien} está editando',
  'colab.estanEditando': '{quien} están editando',
  'colab.estaEditandoTambien': '{quien} también está editando',
  'colab.estanEditandoTambien': '{quien} también están editando',
  'colab.sinBloqueo': 'No se bloquea nada: si los dos guardan, la segunda versión quedará marcada como conflicto y se podrán revisar ambas en el proyecto.',
  'iaRemota.sustitucion': 'El servidor de IA no permite {pedido}: esta generación usa {usado}. Los modelos permitidos los decide quien administra ProcessIQ.',
  'iaRemota.reintentando': 'Reintentando en el servidor… ({error})',
  'iaRemota.enCola': 'En cola en el servidor de IA…',
  'iaRemota.interpretando': 'Interpretando con IA en el servidor… (puede tardar unos minutos)',
  'iaRemota.fallida': 'La IA no pudo completar la tarea.',
  'iaRemota.sinConexion': 'Se perdió la conexión con el servidor. La IA sigue trabajando: vuelve a abrir el proceso para recuperar el resultado.',
  'iaRemota.sinConfigurar': 'La IA del servidor no está configurada todavía (falta la clave de Anthropic).',
  'iaRemota.presupuesto': 'Se alcanzó el presupuesto mensual de IA de la organización.',
  'iaRemota.limite': 'Alcanzaste tu límite mensual de IA.',
  'iaRemota.noDisponible': '{motivo} Se usa el modo básico, sin IA.',
  'iaRemota.noDisponibleGenerico': 'La IA del servidor no está disponible.',
  'iaRemota.nota': '{pedido} no está permitido en el servidor: se usa {usado}.',
  'iaRemota.ajustesIntro': 'En los procesos de un proyecto la IA la gestiona el servidor: la clave de Anthropic no pasa por tu navegador y cada ejecución queda registrada con su coste. Si cierras la pestaña mientras genera, el resultado te espera al volver a abrir el proceso.',
  'iaRemota.estado': 'Estado: <b>{estado}</b>',
  'iaRemota.disponible': 'disponible',
  'iaRemota.modelos': 'Modelos para generar: {modelos}',
  'iaRemota.analisis': 'Análisis (pains y copiloto): {modelo}',
  'iaRemota.gastoOrg': 'Gasto de la organización este mes: <b>{gastado}</b> de {total}',
  'iaRemota.gastoTuyo': 'Tu gasto este mes: <b>{gastado}</b> de {total}',
  // ---------------------------------------------------------------- Plataforma: vista del invitado
  'invitado.noDisponible': 'Este enlace ya no está disponible',
  'invitado.noAbierta': 'No se pudo abrir la revisión',
  'invitado.caducado': 'Puede que haya caducado o que lo hayan revocado. Pide un enlace nuevo a quien te lo envió.',
  'invitado.reintentarLuego': 'Inténtalo de nuevo en unos minutos.',
  'invitado.reintentar': 'Reintentar',
  'invitado.barraAria': 'Revisión compartida',
  'invitado.abriendo': 'Abriendo la revisión compartida…',
  'invitado.version': ' · versión {n}',
  'invitado.detalle': 'Solo lectura · compartida con {para} · disponible hasta el {fecha}',
  'invitado.ficha': 'Ficha del proceso',
  'invitado.comentariosN': 'Comentarios ({n})',
  'invitado.comentarios': 'Comentarios',
  'invitado.cerrarComentarios': 'Cerrar los comentarios',
  'invitado.ayuda': 'Escribe lo que quieras que el equipo revise. Para comentar un paso concreto, haz clic en él en el diagrama.',
  'invitado.tusComentarios': 'Tus comentarios',
  'invitado.tuNombre': 'Tu nombre',
  'invitado.comentario': 'Comentario',
  'invitado.enviar': 'Enviar comentario',
  'invitado.sinComentarios': 'Todavía no has dejado comentarios en esta versión.',
  'invitado.sobre': 'Sobre «{elemento}»',
  'invitado.verEnDiagrama': 'Ver en el diagrama',
  'invitado.resuelto': 'El equipo lo marcó como resuelto',
  'invitado.general': 'Comentario sobre el proceso en general',
  'invitado.quitar': 'Quitar',
  'invitado.quitarAria': 'Comentar el proceso en general',
  'invitado.pasoGenerado': 'Ese paso se generó al cambiar el nivel de detalle y no está en la versión compartida: vuelve al nivel inicial para comentarlo.',
  'invitado.noEnVista': 'Ese elemento no está en la vista o el nivel de detalle que tienes abierto.',
  'invitado.faltaNombre': 'tu nombre',
  'invitado.faltaComentario': 'el comentario',
  'invitado.escribe': 'Escribe {que}.',
  'invitado.y': ' y ',
  'invitado.enviando': 'Enviando…',
  'invitado.enviado': 'Comentario enviado. El equipo lo verá junto a esta versión.',
  'invitado.noEnviado': 'No se pudo enviar el comentario.',
  // ---------------------------------------------------------------- Común
  'idioma.grupo': 'Idioma'
};
