// Textos estáticos de index.html: [selector, dónde está el texto, clave de es.js/en.js].
// Dónde: 'texto' (primer nodo de texto propio del elemento, sin contar espacios),
// 'html' (innerHTML: párrafos con <b>, <code>…) o 'attr:<nombre>' (title, placeholder…).
// i18n.js los aplica solo en inglés y al volver restaura el original exacto.
// La E2E (editor-idioma.spec.mjs) comprueba que el texto de cada uno es el de es.js
// y que no queda ningún texto de index.html sin tabla (salvo los de la lista de iguales).
export const ENLACES_HTML = [
  ['#mobileNotice h2', 'texto', 'html.movil.titulo'],
  ['#mobileNotice p', 'texto', 'html.movil.texto'],
  ['#btnMobileContinue', 'texto', 'html.movil.continuar'],
  ['#mobileNotice .mobile-notice-sub', 'texto', 'html.movil.pie'],
  ['.app-header .brand-sub', 'texto', 'html.marca.sub'],
  ['#processName', 'attr:placeholder', 'html.cab.nombre'],
  ['#btnMeta', 'attr:title', 'html.cab.meta'],
  ['#metaPopover label:has(> #processIndustry)', 'texto', 'html.cab.industria'],
  ['#processIndustry option[value=""]', 'texto', 'html.cab.industriaVacia'],
  ['#metaPopover label:has(> #processMacro)', 'texto', 'html.cab.macro'],
  ['#processMacro option[value=""]', 'texto', 'html.cab.macroVacio'],
  ['.app-header .view-toggle', 'attr:title', 'html.cab.vistas'],
  ['#btnCloneToBe', 'attr:title', 'html.cab.clonar'],
  ['#btnCloneToBe', 'attr:aria-label', 'html.cab.clonarAria'],
  ['#btnTransformToBe', 'attr:title', 'html.cab.transformar'],
  ['#btnTransformToBe', 'texto', 'html.cab.transformarBoton'],
  ['#btnNew', 'attr:title', 'html.cab.nuevoTitulo'],
  ['#btnNew', 'texto', 'html.cab.nuevo'],
  ['#btnIngest', 'attr:title', 'html.cab.ingestarTitulo'],
  ['#btnIngest', 'texto', 'html.cab.ingestar'],
  ['#btnImport', 'attr:title', 'html.cab.importar'],
  ['#btnImport', 'attr:aria-label', 'html.cab.importar'],
  ['#btnAiSettings', 'attr:title', 'html.cab.ajustesIa'],
  ['#btnPresent', 'attr:title', 'html.cab.presentarTitulo'],
  ['#btnPresent', 'texto', 'presentar.boton'],
  ['#btnExportMenu', 'attr:title', 'html.cab.exportar'],
  ['#btnExportMenu', 'texto', 'html.cab.exportar'],
  ['#exportDropdown button[data-export="json"]', 'texto', 'html.exp.json'],
  ['#exportDropdown button[data-export="svg"]', 'texto', 'html.exp.svg'],
  ['#exportDropdown button[data-export="png"]', 'texto', 'html.exp.png'],
  ['#exportDropdown .export-group-title:nth-of-type(1)', 'texto', 'html.exp.grupoPptx'],
  ['#exportDropdown button[data-tema="mbc"] .export-hint', 'texto', 'html.exp.mbcPista'],
  ['#exportDropdown button[data-export="pptx"][data-tema="bbva"]', 'texto', 'html.exp.bbva'],
  ['#exportDropdown button[data-tema="bbva"] .export-hint', 'texto', 'html.exp.bbvaPista'],
  ['#exportDropdown .export-group-title:nth-of-type(2)', 'texto', 'html.exp.grupoOtros'],
  ['#exportDropdown button[data-export="word"]', 'texto', 'html.exp.word'],
  ['#exportDropdown button[data-export="ficha"]', 'texto', 'html.exp.ficha'],
  ['.toolbar-left', 'attr:aria-label', 'html.riel.aria'],
  ['#btnShapes', 'attr:title', 'html.riel.formasTitulo'],
  ['#btnShapes > span', 'texto', 'html.riel.formas'],
  ['#shapesFlyout .flyout-title', 'texto', 'html.riel.arrastra'],
  ['#shapesFlyout button[data-shape="start"]', 'attr:title', 'html.forma.inicio'],
  ['#shapesFlyout [data-shape="start"] .shape-label', 'texto', 'html.forma.inicio'],
  ['#shapesFlyout button[data-shape="task"]', 'attr:title', 'html.forma.actividad'],
  ['#shapesFlyout [data-shape="task"] .shape-label', 'texto', 'html.forma.actividad'],
  ['#shapesFlyout button[data-shape="decision"]', 'attr:title', 'html.forma.decisionTitulo'],
  ['#shapesFlyout [data-shape="decision"] .shape-label', 'texto', 'html.forma.decision'],
  ['#shapesFlyout button[data-shape="document"]', 'attr:title', 'html.forma.documento'],
  ['#shapesFlyout [data-shape="document"] .shape-label', 'texto', 'html.forma.documento'],
  ['#shapesFlyout button[data-shape="system"]', 'attr:title', 'html.forma.sistema'],
  ['#shapesFlyout [data-shape="system"] .shape-label', 'texto', 'html.forma.sistema'],
  ['#shapesFlyout button[data-shape="end"]', 'attr:title', 'html.forma.fin'],
  ['#shapesFlyout [data-shape="end"] .shape-label', 'texto', 'html.forma.fin'],
  ['#btnConnect', 'attr:title', 'html.riel.conectarTitulo'],
  ['#btnConnect > span', 'texto', 'html.riel.conectar'],
  ['#btnDelete', 'attr:title', 'html.riel.eliminarTitulo'],
  ['#btnDelete > span', 'texto', 'html.riel.eliminar'],
  ['#btnAutoLayout', 'attr:title', 'html.riel.ordenarTitulo'],
  ['#btnAutoLayout > span', 'texto', 'html.riel.ordenar'],
  ['#canvasHint .onboard-title', 'texto', 'html.inicio.titulo'],
  ['#canvasHint .onboard-sub', 'texto', 'html.inicio.sub'],
  ['#onbIngest .onboard-step-t', 'texto', 'html.inicio.ingestar'],
  ['#onbIngest .onboard-step-d', 'texto', 'html.inicio.ingestarDesc'],
  ['#onbDemo .onboard-step-t', 'texto', 'html.inicio.ejemplo'],
  ['#onbDemo .onboard-step-d', 'texto', 'html.inicio.ejemploDesc'],
  ['#onbDraw .onboard-step-t', 'texto', 'html.inicio.dibujar'],
  ['#onbDraw .onboard-step-d', 'texto', 'html.inicio.dibujarDesc'],
  ['#btnUndo', 'attr:title', 'html.hist.deshacerTitulo'],
  ['#btnUndo', 'attr:aria-label', 'html.hist.deshacerAria'],
  ['#btnRedo', 'attr:title', 'html.hist.rehacerTitulo'],
  ['#btnRedo', 'attr:aria-label', 'html.hist.rehacerAria'],
  ['#btnAutoFit', 'attr:title', 'html.hist.autoajustarTitulo'],
  ['#btnAutoFit', 'attr:aria-label', 'html.hist.autoajustarAria'],
  ['#btnShortcuts', 'attr:title', 'html.hist.atajosTitulo'],
  ['#btnShortcuts', 'attr:aria-label', 'html.hist.atajosAria'],
  ['#shortcutsPanel .shortcuts-head strong', 'texto', 'html.atajos.titulo'],
  ['#btnShortcutsClose', 'attr:title', 'comun.cerrar'],
  ['#btnShortcutsClose', 'attr:aria-label', 'html.atajos.cerrar'],
  ['#shortcutsPanel .sc-row:nth-child(1) > span', 'texto', 'html.atajos.deshacer'],
  ['#shortcutsPanel .sc-row:nth-child(2) > span', 'texto', 'html.atajos.rehacer'],
  ['#shortcutsPanel .sc-row:nth-child(3) > span', 'texto', 'html.atajos.acercar'],
  ['#shortcutsPanel .sc-row:nth-child(4) > span', 'texto', 'html.atajos.alejar'],
  ['#shortcutsPanel .sc-row:nth-child(6) > kbd:nth-child(2)', 'texto', 'html.atajos.rueda'],
  ['#shortcutsPanel .sc-row:nth-child(6) > span', 'texto', 'html.atajos.zoomCursor'],
  ['#shortcutsPanel .sc-row:nth-child(7) > span', 'texto', 'html.atajos.ajustar'],
  ['#shortcutsPanel .sc-row:nth-child(8) > span', 'texto', 'html.atajos.conectar'],
  ['#shortcutsPanel .sc-row:nth-child(9) > kbd:nth-child(1)', 'texto', 'html.atajos.supr'],
  ['#shortcutsPanel .sc-row:nth-child(9) > span', 'texto', 'html.atajos.eliminar'],
  ['#shortcutsPanel .sc-row:nth-child(10) > span', 'texto', 'html.atajos.esc'],
  ['#shortcutsPanel .sc-row:nth-child(11) > span', 'texto', 'html.atajos.mostrar'],
  ['#shortcutsPanel .shortcuts-note', 'texto', 'html.atajos.nota'],
  ['#bpmnLegend .bpmn-legend-head strong', 'texto', 'html.leyenda.titulo'],
  ['#btnLegendClose', 'attr:title', 'comun.cerrar'],
  ['#btnLegendClose', 'attr:aria-label', 'html.leyenda.cerrar'],
  ['#bpmnLegend .legend-col:nth-child(1) > h5', 'texto', 'html.leyenda.formas'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(2)', 'texto', 'html.leyenda.actividad'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(3)', 'texto', 'html.leyenda.tareaSistema'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(4)', 'texto', 'html.forma.decisionTitulo'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(5)', 'texto', 'html.forma.documento'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(6)', 'texto', 'html.leyenda.datos'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(7)', 'texto', 'html.leyenda.secuencia'],
  ['#bpmnLegend .legend-col:nth-child(1) > .legend-row:nth-child(8)', 'texto', 'html.leyenda.mensaje'],
  ['#bpmnLegend .legend-col:nth-child(2) > h5', 'texto', 'html.leyenda.eventos'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-row:nth-child(2)', 'texto', 'html.leyenda.inicioMensaje'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-row:nth-child(3)', 'texto', 'html.leyenda.intermedio'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-row:nth-child(4)', 'texto', 'html.leyenda.finError'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-row:nth-child(5)', 'texto', 'html.leyenda.senal'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-row:nth-child(6)', 'texto', 'html.leyenda.terminacion'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-row:nth-child(7)', 'texto', 'html.leyenda.borde'],
  ['#bpmnLegend .legend-col:nth-child(2) > .legend-note', 'texto', 'html.leyenda.notaEventos'],
  ['#bpmnLegend .legend-col:nth-child(3) > h5', 'texto', 'html.leyenda.gateways'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-row:nth-child(2)', 'texto', 'html.leyenda.xor'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-row:nth-child(3)', 'texto', 'html.leyenda.and'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-row:nth-child(4)', 'texto', 'html.leyenda.or'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-row:nth-child(5)', 'texto', 'html.leyenda.subproceso'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-row:nth-child(6)', 'texto', 'html.leyenda.loop'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-row:nth-child(7)', 'texto', 'html.leyenda.multi'],
  ['#bpmnLegend .legend-col:nth-child(3) > .legend-note', 'texto', 'html.leyenda.notaTareas'],
  ['#statusMode', 'texto', 'html.estado.modo'],
  ['#statusSaved', 'texto', 'estado.guardado'],
  ['#nivelVista', 'attr:title', 'html.nivel.titulo'],
  ['#nivelVista', 'attr:aria-label', 'html.nivel.titulo'],
  ['#nivelVista button[data-nivel="1"]', 'attr:title', 'html.nivel.ejecutivoTitulo'],
  ['#nivelVista button[data-nivel="1"]', 'texto', 'nivel.ejecutivo'],
  ['#nivelVista button[data-nivel="2"]', 'attr:title', 'html.nivel.actividadTitulo'],
  ['#nivelVista button[data-nivel="2"]', 'texto', 'nivel.actividad'],
  ['#nivelVista button[data-nivel="3"]', 'attr:title', 'html.nivel.detalleTitulo'],
  ['#nivelVista button[data-nivel="3"]', 'texto', 'nivel.detalle'],
  ['#zoomControls', 'attr:title', 'html.zoom.titulo'],
  ['#btnZoomOut', 'attr:title', 'html.zoom.alejarTitulo'],
  ['#btnZoomOut', 'attr:aria-label', 'html.atajos.alejar'],
  ['#btnZoomLevel', 'attr:title', 'html.zoom.nivelTitulo'],
  ['#btnZoomLevel', 'attr:aria-label', 'html.zoom.nivelAria'],
  ['#btnZoomIn', 'attr:title', 'html.zoom.acercarTitulo'],
  ['#btnZoomIn', 'attr:aria-label', 'html.atajos.acercar'],
  ['#btnZoomFit', 'attr:title', 'html.zoom.ajustarTitulo'],
  ['#btnZoomFit', 'attr:aria-label', 'html.zoom.ajustarAria'],
  ['#btnZoomFit', 'texto', 'html.zoom.ajustar'],
  ['.panel-right > nav.tabs', 'attr:aria-label', 'html.pest.aria'],
  ['.tab[data-tab="properties"]', 'attr:title', 'html.pest.props'],
  ['.tab[data-tab="properties"]', 'attr:data-title', 'html.pest.props'],
  ['.tab[data-tab="kpis"]', 'attr:title', 'html.pest.kpis'],
  ['.tab[data-tab="kpis"]', 'attr:data-title', 'html.pest.kpis'],
  ['.tab[data-tab="sim"]', 'attr:title', 'html.pest.sim'],
  ['.tab[data-tab="sim"]', 'attr:data-title', 'html.pest.sim'],
  ['.tab[data-tab="validations"]', 'attr:title', 'html.pest.lint'],
  ['.tab[data-tab="validations"]', 'attr:data-title', 'html.pest.lint'],
  ['.tab[data-tab="ficha"]', 'attr:title', 'html.pest.ficha'],
  ['.tab[data-tab="ficha"]', 'attr:data-title', 'html.pest.ficha'],
  ['.tab[data-tab="ficha"] > span', 'texto', 'html.pest.fichaCorta'],
  ['.tab[data-tab="copilot"]', 'attr:title', 'html.pest.copiloto'],
  ['.tab[data-tab="copilot"]', 'attr:data-title', 'html.pest.copiloto'],
  ['.tab[data-tab="copilot"] > span', 'texto', 'html.pest.copilotoCorta'],
  ['#btnLegend', 'attr:title', 'html.pest.leyendaTitulo'],
  ['#btnLegend > span', 'texto', 'html.pest.leyenda'],
  ['#drawerTitle', 'texto', 'html.cajon.titulo'],
  ['#btnDrawerClose', 'attr:title', 'html.cajon.cerrarTitulo'],
  ['#btnDrawerClose', 'attr:aria-label', 'html.cajon.cerrarAria'],
  ['#propsEmpty', 'texto', 'html.props.vacio'],
  ['#propsForm label:has(> #propNodeType)', 'texto', 'html.props.tipo'],
  ['#propNodeType option[value="start"]', 'texto', 'html.props.tipoInicio'],
  ['#propNodeType option[value="intermediate"]', 'texto', 'html.props.tipoIntermedio'],
  ['#propNodeType option[value="task"]', 'texto', 'html.props.tipoActividad'],
  ['#propNodeType option[value="system"]', 'texto', 'html.props.tipoSistema'],
  ['#propNodeType option[value="decision"]', 'texto', 'html.props.tipoDecision'],
  ['#propNodeType option[value="document"]', 'texto', 'html.props.tipoDocumento'],
  ['#propNodeType option[value="end"]', 'texto', 'html.props.tipoFin'],
  ['#propsForm label:has(> #propActivityCode)', 'texto', 'html.props.codigo'],
  ['#propGatewayWrap', 'texto', 'html.props.gateway'],
  ['#propGatewayType option[value="exclusive"]', 'texto', 'html.props.gwExclusivo'],
  ['#propGatewayType option[value="parallel"]', 'texto', 'html.props.gwParalelo'],
  ['#propGatewayType option[value="inclusive"]', 'texto', 'html.props.gwInclusivo'],
  ['#propEventWrap', 'texto', 'html.props.evento'],
  ['#propEventType option[value="none"]', 'texto', 'html.props.evNinguno'],
  ['#propEventType option[value="message"]', 'texto', 'html.props.evMensaje'],
  ['#propEventType option[value="timer"]', 'texto', 'html.props.evTimer'],
  ['#propEventType option[value="signal"]', 'texto', 'html.props.evSenal'],
  ['#propTerminateWrap > span', 'html', 'html.props.terminacion'],
  ['#propsForm label:has(> #propLabel)', 'texto', 'html.props.etiqueta'],
  ['#propsForm label:has(> #propLabel) > span', 'texto', 'html.props.etiquetaPista'],
  ['#propLabel', 'attr:placeholder', 'html.props.etiquetaEjemplo'],
  ['#propsForm label:has(> #propExecType)', 'texto', 'html.props.tipoTarea'],
  ['#propExecType option[value=""]', 'texto', 'html.props.selecciona'],
  ['#propMarkerWrap', 'texto', 'html.props.marcador'],
  ['#propMarker option[value="none"]', 'texto', 'html.props.mkSimple'],
  ['#propMarker option[value="subprocess"]', 'texto', 'html.props.mkSubproceso'],
  ['#propMarker option[value="loop"]', 'texto', 'html.props.mkLoop'],
  ['#propMarker option[value="multiinstance"]', 'texto', 'html.props.mkMulti'],
  ['#propMarker option[value="multiinstance-seq"]', 'texto', 'html.props.mkMultiSeq'],
  ['#propBoundaryWrap', 'texto', 'html.props.borde'],
  ['#propBoundaryWrap > span', 'texto', 'html.props.bordePista'],
  ['#propBoundary option[value="none"]', 'texto', 'html.props.bdNinguno'],
  ['#propBoundary option[value="timer|true"]', 'texto', 'html.props.bdTimerInt'],
  ['#propBoundary option[value="timer|false"]', 'texto', 'html.props.bdTimerNoInt'],
  ['#propBoundary option[value="error|true"]', 'texto', 'html.props.bdErrorInt'],
  ['#propBoundary option[value="message|false"]', 'texto', 'html.props.bdMensajeNoInt'],
  ['#propsForm label:has(> #propOwner)', 'texto', 'html.props.responsable'],
  ['#propOwner', 'attr:placeholder', 'html.props.responsableEjemplo'],
  ['#propsForm label:has(> #propSystem)', 'texto', 'html.props.sistema'],
  ['#propSystem', 'attr:placeholder', 'html.props.sistemaEjemplo'],
  ['#propsForm label:has(> #propTime)', 'texto', 'html.props.tiempo'],
  ['#propsForm label:has(> #propVolume)', 'texto', 'html.props.volumen'],
  ['#propsForm label:has(> #propVA)', 'texto', 'html.props.valor'],
  ['#propVA option[value="VA"]', 'texto', 'html.props.va'],
  ['#propSla', 'attr:placeholder', 'html.props.slaEjemplo'],
  ['#propsForm label:has(> #propDocsIn)', 'texto', 'html.props.docsEntrada'],
  ['#propDocsIn', 'attr:placeholder', 'html.props.docsEntradaEjemplo'],
  ['#propsForm label:has(> #propDocsOut)', 'texto', 'html.props.docsSalida'],
  ['#propDocsOut', 'attr:placeholder', 'html.props.docsSalidaEjemplo'],
  ['#propsForm label:has(> #propRules)', 'texto', 'html.props.reglas'],
  ['#propRules', 'attr:placeholder', 'html.props.reglasEjemplo'],
  ['#propsForm label:has(> #propNotes)', 'texto', 'html.props.notas'],
  ['#painsHeader p', 'texto', 'html.pains.pista'],
  ['#painDescription', 'attr:placeholder', 'html.pains.describe'],
  ['#painsAdd label:has(> #painSeverity)', 'texto', 'html.pains.severidad'],
  ['#painSeverity option[value="1"]', 'texto', 'html.pains.sev1'],
  ['#painSeverity option[value="3"]', 'texto', 'html.pains.sev3'],
  ['#painSeverity option[value="5"]', 'texto', 'html.pains.sev5'],
  ['#painsAdd label:has(> #painFrequency)', 'texto', 'html.pains.frecuencia'],
  ['#painFrequency option[value="1"]', 'texto', 'html.pains.frec1'],
  ['#painFrequency option[value="3"]', 'texto', 'html.pains.sev3'],
  ['#painFrequency option[value="5"]', 'texto', 'html.pains.frec5'],
  ['#btnAddPain', 'texto', 'html.pains.agregar'],
  ['[data-panel="kpis"] h3', 'texto', 'html.pest.kpis'],
  ['#kpiSearch', 'attr:placeholder', 'html.kpis.buscar'],
  ['#kpiFilterIndustry option[value=""]', 'texto', 'html.kpis.todas'],
  ['[data-panel="sim"] h3', 'texto', 'html.sim.titulo'],
  ['[data-panel="sim"] .panel-section > p', 'html', 'html.sim.pista'],
  ['.sim-params label:has(> #simCostFte)', 'texto', 'html.sim.costo'],
  ['.sim-params label:has(> #simHours)', 'texto', 'html.sim.horas'],
  ['.sim-params label:has(> #simReduction)', 'texto', 'html.sim.reduccion'],
  ['#btnSimWizard', 'texto', 'html.sim.wizard'],
  ['#btnSimRun', 'texto', 'html.sim.ejecutar'],
  ['[data-panel="validations"] h3', 'texto', 'html.lint.titulo'],
  ['[data-panel="validations"] .panel-section > p', 'html', 'html.lint.pista'],
  ['[data-panel="ficha"] h3', 'texto', 'html.ficha.titulo'],
  ['[data-panel="ficha"] .panel-section > p', 'html', 'html.ficha.pista'],
  ['.ficha-form label:has(> #fichaCode)', 'texto', 'html.ficha.codigo'],
  ['.ficha-form label:has(> #fichaVersion)', 'texto', 'html.ficha.version'],
  ['.ficha-form label:has(> #fichaObjetivo)', 'texto', 'html.ficha.objetivo'],
  ['#fichaObjetivo', 'attr:placeholder', 'html.ficha.objetivoEjemplo'],
  ['.ficha-form label:has(> #fichaAlcanceAreas)', 'texto', 'html.ficha.areas'],
  ['#fichaAlcanceAreas', 'attr:placeholder', 'html.ficha.areasEjemplo'],
  ['.ficha-form label:has(> #fichaAlcanceDesde)', 'texto', 'html.ficha.desde'],
  ['#fichaAlcanceDesde', 'attr:placeholder', 'html.ficha.desdeEjemplo'],
  ['.ficha-form label:has(> #fichaAlcanceHasta)', 'texto', 'html.ficha.hasta'],
  ['#fichaAlcanceHasta', 'attr:placeholder', 'html.ficha.hastaEjemplo'],
  ['.ficha-form label:has(> #fichaAlcanceIncluye)', 'texto', 'html.ficha.incluye'],
  ['#fichaAlcanceIncluye', 'attr:placeholder', 'html.ficha.incluyeEjemplo'],
  ['.ficha-form label:has(> #fichaDescripcion)', 'texto', 'html.ficha.descripcion'],
  ['#fichaDescripcion', 'attr:placeholder', 'html.ficha.descripcionEjemplo'],
  ['.ficha-form .ficha-list-hint:nth-child(7)', 'html', 'html.ficha.gobernanzaPista'],
  ['.ficha-form label:has(> #fichaGobernanza)', 'texto', 'html.ficha.gobernanza'],
  ['#fichaGobernanza', 'attr:placeholder', 'html.ficha.gobernanzaEjemplo'],
  ['.ficha-form .ficha-list-hint:nth-child(9)', 'html', 'html.ficha.sistemasPista'],
  ['.ficha-form label:has(> #fichaSistemas)', 'texto', 'html.ficha.sistemas'],
  ['#fichaSistemas', 'attr:placeholder', 'html.ficha.sistemasEjemplo'],
  ['.ficha-form .ficha-list-hint:nth-child(11)', 'html', 'html.ficha.terminosPista'],
  ['.ficha-form label:has(> #fichaTerminos)', 'texto', 'html.ficha.terminos'],
  ['#fichaTerminos', 'attr:placeholder', 'html.ficha.terminosEjemplo'],
  ['.ficha-form .ficha-list-hint:nth-child(13)', 'html', 'html.ficha.anexosPista'],
  ['.ficha-form label:has(> #fichaAnexos)', 'texto', 'html.ficha.anexos'],
  ['#fichaAnexos', 'attr:placeholder', 'html.ficha.anexosEjemplo'],
  ['.ficha-form .ficha-list-hint:nth-child(15)', 'html', 'html.ficha.cambiosPista'],
  ['.ficha-form label:has(> #fichaCambios)', 'texto', 'html.ficha.cambios'],
  ['#fichaCambios', 'attr:placeholder', 'html.ficha.cambiosEjemplo'],
  ['#btnFichaPreview', 'attr:title', 'html.ficha.generarTitulo'],
  ['#btnFichaPreview', 'texto', 'html.ficha.generar'],
  ['[data-panel="copilot"] h3', 'texto', 'html.pest.copiloto'],
  ['[data-panel="copilot"] .panel-section > p', 'texto', 'html.copiloto.pista'],
  ['.copilot-action[data-action="generate"]', 'texto', 'html.copiloto.generate'],
  ['.copilot-action[data-action="detect-pains"]', 'texto', 'html.copiloto.detectPains'],
  ['.copilot-action[data-action="suggest-kpis"]', 'texto', 'html.copiloto.suggestKpis'],
  ['.copilot-action[data-action="propose-tobe"]', 'texto', 'html.copiloto.proposeTobe'],
  ['.copilot-action[data-action="raci"]', 'texto', 'html.copiloto.raci'],
  ['.copilot-action[data-action="sipoc"]', 'texto', 'html.copiloto.sipoc'],
  ['.copilot-action[data-action="impact-effort"]', 'texto', 'html.copiloto.impactEffort'],
  ['.copilot-action[data-action="whatif"]', 'texto', 'html.copiloto.whatif'],
  ['.copilot-action[data-action="automation"]', 'texto', 'html.copiloto.automation'],
  ['.copilot-action[data-action="bottleneck"]', 'texto', 'html.copiloto.bottleneck'],
  ['.copilot-action[data-action="variants"]', 'texto', 'html.copiloto.variants'],
  ['.copilot-action[data-action="value-map"]', 'texto', 'html.copiloto.valueMap'],
  ['.copilot-action[data-action="backlog"]', 'texto', 'html.copiloto.backlog'],
  ['.copilot-action[data-action="ai-pains"]', 'texto', 'html.copiloto.aiPains'],
  ['.copilot-action[data-action="autofit"]', 'texto', 'html.copiloto.autofit'],
  ['.copilot-action[data-action="relayout"]', 'texto', 'html.copiloto.relayout'],
  ['.copilot-action[data-action="merge-gateways"]', 'texto', 'html.copiloto.mergeGateways'],
  ['.copilot-action[data-action="exec-summary"]', 'texto', 'html.copiloto.execSummary'],
  ['#copilotPrompt', 'attr:placeholder', 'html.copiloto.comandos'],
  ['#btnCopilotSend', 'texto', 'html.copiloto.enviar'],
  ['#modalCancel', 'texto', 'comun.cancelar'],
  ['#modalOk', 'texto', 'comun.aceptar'],
  ['#ingestModal .modal-head h3', 'texto', 'html.ingesta.titulo'],
  ['#ingestClose', 'attr:title', 'comun.cerrar'],
  ['#ingestModal .modal-sub', 'html', 'html.ingesta.sub'],
  ['.itab[data-itab="notes"]', 'texto', 'html.ingesta.pestNotas'],
  ['.itab[data-itab="audio"]', 'texto', 'html.ingesta.pestAudio'],
  ['.itab[data-itab="eventlog"]', 'texto', 'html.ingesta.pestLog'],
  ['[data-ipanel="audio"] > p.panel-hint', 'texto', 'html.ingesta.audioPista'],
  ['#btnRecStart', 'texto', 'html.ingesta.grabar'],
  ['#btnRecStop', 'texto', 'html.ingesta.detener'],
  ['#recStatus', 'texto', 'grabacion.listo'],
  ['#audioTranscript', 'attr:placeholder', 'html.ingesta.transcripcion'],
  ['#btnIngestAudio', 'texto', 'html.ingesta.generarAudio'],
  ['[data-ipanel="notes"] > p.panel-hint', 'texto', 'html.ingesta.notasPista'],
  ['#dropZone', 'attr:aria-label', 'html.ingesta.soltarAria'],
  ['#dropZone .drop-title', 'texto', 'html.ingesta.soltar'],
  ['#dropZone .drop-sub', 'html', 'html.ingesta.soltarSub'],
  ['#sourcesCount', 'texto', 'html.ingesta.ceroFuentes'],
  ['#btnAddSource', 'attr:title', 'html.ingesta.otraFuenteTitulo'],
  ['#btnAddSource', 'texto', 'html.ingesta.otraFuente'],
  ['#sourcesBox .src-hint', 'texto', 'html.ingesta.combinar'],
  ['#ingestProgressText', 'texto', 'html.ingesta.procesando'],
  ['#btnIngestCancel', 'texto', 'comun.cancelar'],
  ['#ingestModal .ingest-more > summary', 'texto', 'html.ingesta.pegar'],
  ['#notesInput', 'attr:placeholder', 'html.ingesta.notasEjemplo'],
  ['#btnIngestGo', 'attr:title', 'html.ingesta.generarTitulo'],
  ['#btnIngestGo .go-label', 'texto', 'ingesta.generarProceso'],
  ['#btnLoadSample', 'attr:title', 'html.ingesta.ejemplosTitulo'],
  ['#btnLoadSample', 'texto', 'html.ingesta.ejemplos'],
  ['[data-ipanel="eventlog"] > p.panel-hint', 'html', 'html.ingesta.logPista'],
  ['#btnCsvSample', 'texto', 'html.ingesta.muestra'],
  ['#csvMapping label:has(> #mapCase)', 'texto', 'html.ingesta.colCaso'],
  ['#csvMapping label:has(> #mapAct)', 'texto', 'html.ingesta.colActividad'],
  ['#csvMapping label:has(> #mapTs)', 'texto', 'html.ingesta.colFecha'],
  ['#csvMapping label:has(> #mapRes)', 'texto', 'html.ingesta.colRecurso'],
  ['#btnIngestCsv', 'texto', 'html.ingesta.descubrir']
];
