// Textos de Portafolio en español (fuente de verdad) e inglés. El tipo
// `Traduccion` obliga a que el inglés tenga todas las claves, variables y
// etiquetas del español (shell/i18n.ts).
import type { DefinicionTipoEjecucion } from '@processiq/dominio';
import { definirTextos, type Traduccion } from '../../shell/i18n';

const es = {
  'titulo': 'Portafolio',
  'tituloCliente': '{cliente} · Portafolio',
  'introEstado': 'El estado de los procesos de cada cliente según su última revisión.',
  'introAdmin': 'Incluye todos los proyectos de la organización.',
  'introMiembro': 'Incluye los proyectos en los que participas.',
  'vacio': 'Todavía no hay clientes que mostrar. El portafolio agrupa los proyectos por su campo «Cliente».',
  'vacioSinArchivados': 'Todavía no hay clientes que mostrar. El portafolio agrupa los proyectos por su campo «Cliente» (sin contar los archivados).',
  'sinCliente': 'Sin cliente',
  'incluirArchivados': 'Incluir proyectos archivados',
  'ruta': 'Ruta',
  'noEncontrada': 'No encontrada',
  'noEncontradaTexto': 'Esta página no existe. <enlace>Volver al portafolio</enlace>.',

  // Cifras
  'clientes': 'Clientes',
  'procesos': 'Procesos',
  'aprobados': 'Aprobados',
  'enRevision': 'En revisión',
  'nProyectos': { uno: '{n} proyecto', otros: '{n} proyectos' },
  'nProcesos': { uno: '{n} proceso', otros: '{n} procesos' },
  'pctProcesos': '{p} % de los procesos',
  'esperanAprobacion': 'esperan aprobación',

  // Tabla de clientes y avance
  'cliente': 'Cliente',
  'proyectos': 'Proyectos',
  'avance': 'Avance hacia la aprobación',
  'actualizado': 'Actualizado',
  'sinProcesos': 'Sin procesos',
  'aprobadosDe': { uno: '{a} de {n} aprobado', otros: '{a} de {n} aprobados' },
  'tramoAprobados': 'Aprobados',
  'tramoRevision': 'En revisión',
  'tramoBorrador': 'En borrador',
  'tramoSin': 'Sin revisiones',
  'tramo': '{tramo}: {n}',
  'tramoTitulo': '{tramo}: {n} ({p} %)',

  // Un cliente
  'actualizadoEl': 'Actualizado el {fecha}',
  'procesosAprobados': { uno: '{a} de {n} proceso aprobado ({p} %)', otros: '{a} de {n} procesos aprobados ({p} %)' },
  'actividades': 'Actividades',
  'nDecisiones': { uno: '{n} decisión', otros: '{n} decisiones' },
  'nEventos': { uno: '{n} evento', otros: '{n} eventos' },
  'roles': 'Roles',
  'rolesNota': 'responsables distintos (carriles)',
  'pains': 'Pains',
  'painsNota': 'puntuación {p} · máx. {m} de 25',
  'painsNinguno': 'ninguno registrado',
  'kpisConValor': 'KPIs con valor',
  'kpisElegidos': { uno: 'de {n} KPI elegido', otros: 'de {n} KPIs elegidos' },
  'kpisNinguno': 'ningún KPI elegido',
  'hallazgosPlaybook': 'Hallazgos del Playbook',
  'sinObservaciones': 'sin observaciones',
  'nCriticos': { uno: '{n} crítico', otros: '{n} críticos' },
  'nAltos': { uno: '{n} alto', otros: '{n} altos' },
  'notaIndicadores': { uno: 'Indicadores de la última revisión de {n} proceso', otros: 'Indicadores de la última revisión de {n} procesos' },
  'notaSinRevisiones': { uno: '{n} proceso aún no tiene revisiones', otros: '{n} procesos aún no tienen revisiones' },
  'tipoEjecucion': 'Tipo de ejecución de las actividades',
  'painsPrincipales': 'Pains principales',
  'sinPains': 'Ningún proceso tiene pains registrados.',
  'puntuacion': 'Puntuación',
  'puntuacionTitulo': 'Severidad × frecuencia (máximo 25)',
  'pain': 'Pain',
  'donde': 'Dónde',
  'sinDescripcion': 'Sin descripción',
  'procesosPorProyecto': 'Procesos por proyecto',
  'archivado': 'Archivado',
  'proyectoSinProcesos': 'Este proyecto aún no tiene procesos.',
  'sinActividades': 'Los procesos no tienen actividades.',
  'barraTitulo': '{tipo}: {v} de {total} actividades',
  'pct': '{p} %',
  'sinTipo': 'Sin tipo',

  // Tabla de procesos
  'proceso': 'Proceso',
  'ultimaRevision': 'Última revisión',
  'sinRevisiones': 'Sin revisiones',
  'painsTitulo': 'Cantidad y la mayor puntuación (severidad × frecuencia)',
  'hallazgos': 'Hallazgos',
  'acciones': 'Acciones',
  'maximo': 'máx. {m}',
  'xDeY': '{a} de {b}',
  'nGraves': { uno: '{n} grave', otros: '{n} graves' },
  'contenidoInvalido': 'No se pudo leer el contenido de la última revisión.',
  'sinContenido': 'Sin contenido todavía.',
  'abrirEnEditor': 'Abrir en el editor'
} as const;

const en = {
  'titulo': 'Portfolio',
  'tituloCliente': '{cliente} · Portfolio',
  'introEstado': 'The status of each client’s processes, based on their latest revision.',
  'introAdmin': 'Includes every project in your organization.',
  'introMiembro': 'Includes the projects you are a member of.',
  'vacio': 'There are no clients to show yet. The portfolio groups projects by their “Client” field.',
  'vacioSinArchivados': 'There are no clients to show yet. The portfolio groups projects by their “Client” field (archived projects are not included).',
  'sinCliente': 'No client',
  'incluirArchivados': 'Include archived projects',
  'ruta': 'Breadcrumb',
  'noEncontrada': 'Not found',
  'noEncontradaTexto': 'This page does not exist. <enlace>Back to the portfolio</enlace>.',

  'clientes': 'Clients',
  'procesos': 'Processes',
  'aprobados': 'Approved',
  'enRevision': 'In review',
  'nProyectos': { uno: '{n} project', otros: '{n} projects' },
  'nProcesos': { uno: '{n} process', otros: '{n} processes' },
  'pctProcesos': '{p}% of processes',
  'esperanAprobacion': 'awaiting approval',

  'cliente': 'Client',
  'proyectos': 'Projects',
  'avance': 'Progress toward approval',
  'actualizado': 'Updated',
  'sinProcesos': 'No processes',
  'aprobadosDe': { uno: '{a} of {n} approved', otros: '{a} of {n} approved' },
  'tramoAprobados': 'Approved',
  'tramoRevision': 'In review',
  'tramoBorrador': 'Draft',
  'tramoSin': 'No revisions',
  'tramo': '{tramo}: {n}',
  'tramoTitulo': '{tramo}: {n} ({p}%)',

  'actualizadoEl': 'Updated {fecha}',
  'procesosAprobados': { uno: '{a} of {n} process approved ({p}%)', otros: '{a} of {n} processes approved ({p}%)' },
  'actividades': 'Activities',
  'nDecisiones': { uno: '{n} decision', otros: '{n} decisions' },
  'nEventos': { uno: '{n} event', otros: '{n} events' },
  'roles': 'Roles',
  'rolesNota': 'distinct owners (lanes)',
  'pains': 'Pain points',
  'painsNota': 'score {p} · max {m} of 25',
  'painsNinguno': 'none recorded',
  'kpisConValor': 'KPIs with a value',
  'kpisElegidos': { uno: 'of {n} selected KPI', otros: 'of {n} selected KPIs' },
  'kpisNinguno': 'no KPIs selected',
  'hallazgosPlaybook': 'Playbook findings',
  'sinObservaciones': 'no findings',
  'nCriticos': { uno: '{n} critical', otros: '{n} critical' },
  'nAltos': { uno: '{n} high', otros: '{n} high' },
  'notaIndicadores': { uno: 'Indicators from the latest revision of {n} process', otros: 'Indicators from the latest revision of {n} processes' },
  'notaSinRevisiones': { uno: '{n} process has no revisions yet', otros: '{n} processes have no revisions yet' },
  'tipoEjecucion': 'Activity execution type',
  'painsPrincipales': 'Top pain points',
  'sinPains': 'No process has recorded pain points.',
  'puntuacion': 'Score',
  'puntuacionTitulo': 'Severity × frequency (max 25)',
  'pain': 'Pain point',
  'donde': 'Where',
  'sinDescripcion': 'No description',
  'procesosPorProyecto': 'Processes by project',
  'archivado': 'Archived',
  'proyectoSinProcesos': 'This project has no processes yet.',
  'sinActividades': 'The processes have no activities.',
  'barraTitulo': '{tipo}: {v} of {total} activities',
  'pct': '{p}%',
  'sinTipo': 'No type',

  'proceso': 'Process',
  'ultimaRevision': 'Latest revision',
  'sinRevisiones': 'No revisions',
  'painsTitulo': 'Count and highest score (severity × frequency)',
  'hallazgos': 'Findings',
  'acciones': 'Actions',
  'maximo': 'max {m}',
  'xDeY': '{a} of {b}',
  'nGraves': { uno: '{n} severe', otros: '{n} severe' },
  'contenidoInvalido': 'The content of the latest revision could not be read.',
  'sinContenido': 'No content yet.',
  'abrirEnEditor': 'Open in editor'
} as const satisfies Traduccion<typeof es>;

export const useT = definirTextos(es, en);
export type TraductorPortafolio = ReturnType<typeof useT>;

/**
 * Tipos de ejecución y categorías de pains en inglés. En español se usan las
 * etiquetas de @processiq/dominio (EXECUTION_TYPES, PAIN_CATEGORIES), que no cambian.
 */
export const EJECUCION_EN: Record<DefinicionTipoEjecucion['id'], string> = {
  manual: 'Manual',
  system: 'User Task (system)',
  automatic: 'Service Task (automatic)',
  ai: 'Script/AI Task',
  email: 'Receive Task (email)',
  send: 'Send Task',
  phone: 'By phone',
  document: 'Document-based',
  rpa: 'RPA / Bot'
};

export const CATEGORIAS_PAIN_EN: Readonly<Record<string, string>> = {
  handoff: 'Handoff',
  rework: 'Rework',
  wait: 'Waiting / bottleneck',
  control: 'Duplicate control',
  system: 'Systems / technology',
  regulatory: 'Regulatory / compliance',
  manual: 'Manual activity',
  data: 'Data quality'
};
