// Textos de Conocimiento en español (fuente de verdad) e inglés. El tipo
// `Traduccion` obliga a que el inglés tenga todas las claves, variables y
// etiquetas del español (shell/i18n.ts).
import { definirTextos, type Traduccion } from '../../shell/i18n';

const es = {
  'titulo': 'Conocimiento',
  'intro': 'Reutiliza lo que ya se levantó: busca entre los procesos de tus proyectos y compáralos con el marco de referencia.',
  'pestanaBuscar': 'Buscar procesos',
  'pestanaMarco': 'Marco de referencia',
  'ruta': 'Ruta',
  'noEncontrada': 'No encontrada',
  'noEncontradaTexto': 'Esta página no existe. <enlace>Volver al buscador</enlace>.',
  'archivado': 'Archivado',
  'abrirEnEditor': 'Abrir en el editor',
  'proceso': 'Proceso',

  // Campos donde aparece lo buscado
  'campoNombre': 'Nombre',
  'campoActividad': 'Actividad',
  'campoSistema': 'Sistema',
  'campoRol': 'Rol',
  'campoElemento': 'En el diagrama',
  'campoFicha': 'Ficha',

  // Buscar
  'buscarEtiqueta': 'Buscar en actividades, sistemas, roles y ficha',
  'buscarEjemplo': 'Por ejemplo: validar póliza, SAP, Tesorería…',
  'buscar': 'Buscar',
  'buscarAyuda': 'Sin distinguir tildes ni mayúsculas, y con tolerancia a erratas. Se busca en la última revisión de cada proceso.',
  'vacioTitulo': '¿Qué proceso vas a levantar?',
  'vacioTexto': 'Escribe una actividad, un sistema o un rol para ver cómo se resolvió en otros proyectos.',
  'pruebaCon': 'Prueba con',
  'dosLetras': 'Escribe al menos dos letras.',
  'sinResultados': 'Ningún proceso de tus proyectos coincide con «{consulta}». Prueba con menos palabras o con otra forma de decirlo (el buscador exige que estén todas).',
  'resultados': { uno: 'Un proceso para «{consulta}»', otros: '{n} procesos para «{consulta}»' },
  'parecidosYComparativo': 'Parecidos y comparativo',

  // Marco de referencia
  'nivel1': { uno: '{n} categoría', otros: '{n} categorías' },
  'nivel2': { uno: '{n} grupo de procesos', otros: '{n} grupos de procesos' },
  'nivel3': { uno: '{n} proceso', otros: '{n} procesos' },
  'nivel4': { uno: '{n} actividad', otros: '{n} actividades' },
  'nivel5': { uno: '{n} tarea', otros: '{n} tareas' },
  'nivelN': '{n} de nivel {nivel}',
  'marcoAviso': 'El comparativo usa el marco de procesos de la organización, normalmente el <strong>APQC Process Classification Framework (PCF)</strong>. El PCF tiene licencia de APQC y ProcessIQ no lo incluye: lo aporta el administrador, que lo descarga con la licencia de la organización y lo importa aquí. Solo lo ven las personas de la organización.',
  'marcoActual': 'Marco actual',
  'sinMarcoAdmin': 'Todavía no hay un marco importado. Impórtalo abajo desde un CSV.',
  'sinMarco': 'Todavía no hay un marco importado. Pídeselo a un administrador.',
  'resumenMarco': '<strong>{elementos}</strong> elementos en <strong>{categorias}</strong> categorías',
  'importadoEl': 'importado el {fecha}',
  'soloAdmin': 'Solo un administrador puede importar o reemplazar el marco.',
  'codigo': 'Código',
  'categoriaNivel1': 'Categoría (nivel 1)',
  'elementos': 'Elementos',
  'nombre': 'Nombre',
  'nivel': 'Nivel',
  'archivoGrande': 'El archivo pasa de 7 MB. Guarda solo las columnas de código, nombre y descripción.',
  'importarCsv': 'Importar desde un CSV',
  'importarAyuda': 'Una fila por elemento con las columnas <strong>Código</strong> (o <em>Hierarchy ID</em>), <strong>Nombre</strong> (o <em>Name</em>) y, si quieres, <strong>Descripción</strong>. Separado por comas o por punto y coma, como lo guarda Excel. El nivel sale del código: 1.0 es una categoría, 1.1 un grupo, 1.1.1 un proceso…',
  'archivoCsv': 'Archivo CSV',
  'marcoImportado': 'Marco importado: {n} elementos. El comparativo ya lo usa.',
  'vistaPrevia': 'Vista previa de «{nombre}»',
  'previaElementos': '<strong>{n}</strong> elementos:',
  'conErrores': 'El archivo tiene errores y no se puede importar:',
  'primerasFilas': 'Primeras filas',
  'reemplaza': 'Reemplaza el marco actual ({n} elementos).',
  'reemplazar': 'Reemplazar con estos {n} elementos',
  'importar': 'Importar {n} elementos',

  // Un proceso: parecidos y comparativo
  'umbralAmplio': 'Amplio (25%)',
  'umbralNormal': 'Normal (35%)',
  'umbralEstricto': 'Estricto (50%)',
  'umbralMuyEstricto': 'Muy estricto (65%)',
  'ultimaRevision': 'última revisión: v{n}',
  'verRevisiones': 'Ver revisiones',
  'sinRevisiones': 'Este proceso todavía no tiene revisiones: dibújalo y guarda una revisión para compararlo.',
  'parecidos': 'Procesos parecidos',
  'parecidosIntro': 'Entre los proyectos a los que tienes acceso, por lo que describe cada proceso: actividades, sistemas y roles.',
  'comparativo': 'Comparativo con el marco de referencia',
  'muyParecido': 'Muy parecido',
  'parecido': 'Parecido',
  'algoEnComun': 'Algo en común',
  'sinParecidos': 'No hay otros procesos parecidos entre los proyectos a los que tienes acceso.',
  'parecidoEtiqueta': 'Parecido: {p}',
  'nadaEnComun': 'Sin actividades, sistemas ni roles iguales: el parecido viene de palabras sueltas.',
  'actividadesEnComun': 'Actividades en común',
  'sistemasEnComun': 'Sistemas en común',
  'rolesEnComun': 'Roles en común',
  'yMas': 'y {n} más',
  'sinMarcoOrganizacion': 'La organización todavía no tiene un marco de referencia.',
  'importaloEn': 'Impórtalo en <enlace>Marco de referencia</enlace>.',
  'loImportaAdmin': 'Lo importa un administrador en «Marco de referencia».',
  'licenciaApqc': 'El APQC Process Classification Framework tiene licencia y lo aporta el administrador: ProcessIQ no lo incluye.',
  'sinActividades': 'La última revisión no tiene actividades que comparar.',
  'asignadas': '<strong>{a} de {b}</strong> actividades tienen un equivalente en el marco ({elementos} elementos). Cada actividad se asigna al elemento más parecido si supera el umbral.',
  'umbral': 'Umbral de parecido',
  'cobertura': 'Cobertura por categoría',
  'ningunaSupera': 'Ninguna actividad supera el umbral: prueba con uno más amplio.',
  'categoriasSinActividades': 'Categorías sin actividades de este proceso ({n})',
  'actividadPorActividad': 'Actividad por actividad',
  'actividad': 'Actividad',
  'rol': 'Rol',
  'elementoMarco': 'Elemento del marco',
  'parecidoColumna': 'Parecido',
  'sinEquivalente': 'Sin equivalente en el marco',
  'nActividades': { uno: 'Una actividad', otros: '{n} actividades' },
  'sinGrupos': 'La categoría no tiene grupos de nivel 2 en el marco.',
  'coberturaEtiqueta': 'Cobertura: {p}',
  'gruposCubiertos': '<strong>{a} de {b}</strong> grupos cubiertos ({p})',
  'falta': 'falta'
} as const;

const en = {
  'titulo': 'Knowledge',
  'intro': 'Reuse what has already been mapped: search your projects’ processes and compare them with the reference framework.',
  'pestanaBuscar': 'Search processes',
  'pestanaMarco': 'Reference framework',
  'ruta': 'Breadcrumb',
  'noEncontrada': 'Not found',
  'noEncontradaTexto': 'This page does not exist. <enlace>Back to search</enlace>.',
  'archivado': 'Archived',
  'abrirEnEditor': 'Open in editor',
  'proceso': 'Process',

  'campoNombre': 'Name',
  'campoActividad': 'Activity',
  'campoSistema': 'System',
  'campoRol': 'Role',
  'campoElemento': 'In the diagram',
  'campoFicha': 'Process sheet',

  'buscarEtiqueta': 'Search activities, systems, roles and process sheets',
  'buscarEjemplo': 'For example: validar póliza, SAP, Tesorería…',
  'buscar': 'Search',
  'buscarAyuda': 'Ignores accents and capitalization, and tolerates typos. It searches the latest revision of each process; process content is usually in Spanish.',
  'vacioTitulo': 'Which process are you about to map?',
  'vacioTexto': 'Type an activity, a system or a role to see how other projects handled it.',
  'pruebaCon': 'Try',
  'dosLetras': 'Type at least two letters.',
  'sinResultados': 'No process in your projects matches “{consulta}”. Try fewer words or different wording (every word must match).',
  'resultados': { uno: 'One process for “{consulta}”', otros: '{n} processes for “{consulta}”' },
  'parecidosYComparativo': 'Similar processes and comparison',

  'nivel1': { uno: '{n} category', otros: '{n} categories' },
  'nivel2': { uno: '{n} process group', otros: '{n} process groups' },
  'nivel3': { uno: '{n} process', otros: '{n} processes' },
  'nivel4': { uno: '{n} activity', otros: '{n} activities' },
  'nivel5': { uno: '{n} task', otros: '{n} tasks' },
  'nivelN': '{n} at level {nivel}',
  'marcoAviso': 'The comparison uses your organization’s process framework, usually the <strong>APQC Process Classification Framework (PCF)</strong>. The PCF is licensed by APQC and is not included in ProcessIQ: an administrator downloads it under the organization’s license and imports it here. Only people in your organization can see it.',
  'marcoActual': 'Current framework',
  'sinMarcoAdmin': 'No framework has been imported yet. Import one below from a CSV file.',
  'sinMarco': 'No framework has been imported yet. Ask an administrator to import one.',
  'resumenMarco': '<strong>{elementos}</strong> elements in <strong>{categorias}</strong> categories',
  'importadoEl': 'imported {fecha}',
  'soloAdmin': 'Only an administrator can import or replace the framework.',
  'codigo': 'Code',
  'categoriaNivel1': 'Category (level 1)',
  'elementos': 'Elements',
  'nombre': 'Name',
  'nivel': 'Level',
  'archivoGrande': 'The file is larger than 7 MB. Keep only the code, name and description columns.',
  'importarCsv': 'Import from a CSV file',
  'importarAyuda': 'One row per element, with the columns <strong>Code</strong> (or <em>Hierarchy ID</em>), <strong>Name</strong> (or <em>Nombre</em>) and, optionally, <strong>Description</strong>. Comma- or semicolon-separated, as Excel saves it. The level comes from the code: 1.0 is a category, 1.1 a group, 1.1.1 a process…',
  'archivoCsv': 'CSV file',
  'marcoImportado': 'Framework imported: {n} elements. The comparison now uses it.',
  'vistaPrevia': 'Preview of “{nombre}”',
  'previaElementos': '<strong>{n}</strong> elements:',
  'conErrores': 'The file has errors and cannot be imported:',
  'primerasFilas': 'First rows',
  'reemplaza': 'Replaces the current framework ({n} elements).',
  'reemplazar': 'Replace with these {n} elements',
  'importar': 'Import {n} elements',

  'umbralAmplio': 'Broad (25%)',
  'umbralNormal': 'Standard (35%)',
  'umbralEstricto': 'Strict (50%)',
  'umbralMuyEstricto': 'Very strict (65%)',
  'ultimaRevision': 'latest revision: v{n}',
  'verRevisiones': 'View revisions',
  'sinRevisiones': 'This process has no revisions yet: draw it and save a revision to compare it.',
  'parecidos': 'Similar processes',
  'parecidosIntro': 'Across the projects you can access, based on what each process describes: activities, systems and roles.',
  'comparativo': 'Comparison with the reference framework',
  'muyParecido': 'Very similar',
  'parecido': 'Similar',
  'algoEnComun': 'Some overlap',
  'sinParecidos': 'There are no other similar processes in the projects you can access.',
  'parecidoEtiqueta': 'Similarity: {p}',
  'nadaEnComun': 'No shared activities, systems or roles: the similarity comes from individual words.',
  'actividadesEnComun': 'Shared activities',
  'sistemasEnComun': 'Shared systems',
  'rolesEnComun': 'Shared roles',
  'yMas': 'and {n} more',
  'sinMarcoOrganizacion': 'Your organization does not have a reference framework yet.',
  'importaloEn': 'Import it in <enlace>Reference framework</enlace>.',
  'loImportaAdmin': 'An administrator imports it in “Reference framework”.',
  'licenciaApqc': 'The APQC Process Classification Framework is licensed and provided by the administrator: ProcessIQ does not include it.',
  'sinActividades': 'The latest revision has no activities to compare.',
  'asignadas': '<strong>{a} of {b}</strong> activities have an equivalent in the framework ({elementos} elements). Each activity is matched to the most similar element if it clears the threshold.',
  'umbral': 'Similarity threshold',
  'cobertura': 'Coverage by category',
  'ningunaSupera': 'No activity clears the threshold: try a broader one.',
  'categoriasSinActividades': 'Categories with no activities from this process ({n})',
  'actividadPorActividad': 'Activity by activity',
  'actividad': 'Activity',
  'rol': 'Role',
  'elementoMarco': 'Framework element',
  'parecidoColumna': 'Similarity',
  'sinEquivalente': 'No equivalent in the framework',
  'nActividades': { uno: 'One activity', otros: '{n} activities' },
  'sinGrupos': 'This category has no level-2 groups in the framework.',
  'coberturaEtiqueta': 'Coverage: {p}',
  'gruposCubiertos': '<strong>{a} of {b}</strong> groups covered ({p})',
  'falta': 'missing'
} as const satisfies Traduccion<typeof es>;

export const useT = definirTextos(es, en);
export type TraductorConocimiento = ReturnType<typeof useT>;
