// Textos de Invitados en la página del proceso (shell), en español (fuente de
// verdad) e inglés. La vista del invitado (/?invitado=…) es parte del editor y
// sigue en español. El tipo `Traduccion` obliga a traducirlo todo (shell/i18n.ts).
import { definirTextos, type Traduccion } from '../../shell/i18n';

const es = {
  'estadoActivo': 'Activo',
  'estadoCaducado': 'Caducado',
  'estadoRevocado': 'Revocado',
  'titulo': 'Revisión con el cliente',
  'sinResolver': { uno: '{n} comentario sin resolver', otros: '{n} comentarios sin resolver' },
  'compartir': 'Compartir con el cliente',
  'intro': 'Comparte una versión con un enlace de solo lectura: quien lo recibe ve el diagrama y la ficha sin necesitar cuenta y puede dejar comentarios. El enlace caduca solo y se puede revocar en cualquier momento.',
  'sinRevisiones': 'Cuando haya una revisión guardada, podrás compartirla con el cliente.',
  'sinCompartir': 'Todavía no se ha compartido ninguna versión de este proceso.',
  'guardadaEl': 'guardada el {fecha}',
  'comentarios': 'Comentarios',
  'nadieComento': 'Nadie ha comentado esta versión todavía.',
  'enlacesVersion': 'Enlaces de esta versión',
  'enlacePara': 'Enlace para',
  'estado': 'Estado',
  'caduca': 'Caduca',
  'ultimoAcceso': 'Último acceso',
  'acciones': 'Acciones',
  'creadoPor': 'Creado por {autor} el {fecha}',
  'sinComentarios': ' · sin comentarios',
  'revocadoEl': 'Revocado el {fecha}',
  'sinAbrir': 'Sin abrir',
  'revocar': 'Revocar',
  'revocarTitulo': 'Revocar el enlace',
  'revocarTexto': 'El enlace para <strong>{destinatario}</strong> dejará de funcionar en el acto. Los comentarios que ya dejaron se conservan.',
  'cancelar': 'Cancelar',
  'revocarEnlace': 'Revocar enlace',
  'sobre': 'Sobre «{elemento}»',
  'resuelto': 'Resuelto',
  'resueltoPor': 'por {quien} el {fecha}',
  'version': 'Versión que verá',
  'opcionVersion': 'v{n} · {estado} · {fecha}',
  'paraQuien': 'Para quién es',
  'paraQuienEjemplo': 'Gerencia de Operaciones del cliente',
  'paraQuienAyuda': 'Solo para que el equipo sepa a quién se lo enviaste: ProcessIQ no envía nada.',
  'dias': 'Días hasta que caduque',
  'diasAyuda': 'Entre 1 y 90. Después el enlace deja de funcionar.',
  'puedeComentar': 'Puede dejar comentarios',
  'queVera': 'Quien tenga el enlace verá esta versión completa (diagrama, ficha y notas de las actividades), pero no el proyecto, otras versiones ni al equipo.',
  'crearEnlace': 'Crear enlace',
  'enlaceA': 'Enlace a la <strong>v{n}</strong> para <strong>{destinatario}</strong>.',
  'hasta': 'Funciona hasta el {fecha}',
  'soloAhora': 'Solo se muestra ahora. Cópialo y envíalo por el canal habitual: después no se puede recuperar (sí revocar).',
  'enlaceCliente': 'Enlace para el cliente',
  'copiado': 'Copiado',
  'copiar': 'Copiar',
  'verComoCliente': 'Ver como el cliente',
  /** `title` de «Ver como el cliente»: vacío en español (la vista del invitado está en español). */
  'vistaEnEspanol': '',
  'hecho': 'Hecho'
} as const;

const en = {
  'estadoActivo': 'Active',
  'estadoCaducado': 'Expired',
  'estadoRevocado': 'Revoked',
  'titulo': 'Client review',
  'sinResolver': { uno: '{n} unresolved comment', otros: '{n} unresolved comments' },
  'compartir': 'Share with the client',
  'intro': 'Share a version through a read-only link: recipients see the diagram and the process sheet without an account, and can leave comments. The link expires automatically and can be revoked at any time.',
  'sinRevisiones': 'Once a revision has been saved, you can share it with the client.',
  'sinCompartir': 'No version of this process has been shared yet.',
  'guardadaEl': 'saved {fecha}',
  'comentarios': 'Comments',
  'nadieComento': 'No one has commented on this version yet.',
  'enlacesVersion': 'Links for this version',
  'enlacePara': 'Link for',
  'estado': 'Status',
  'caduca': 'Expires',
  'ultimoAcceso': 'Last opened',
  'acciones': 'Actions',
  'creadoPor': 'Created by {autor} on {fecha}',
  'sinComentarios': ' · comments off',
  'revocadoEl': 'Revoked {fecha}',
  'sinAbrir': 'Not opened yet',
  'revocar': 'Revoke',
  'revocarTitulo': 'Revoke link',
  'revocarTexto': 'The link for <strong>{destinatario}</strong> will stop working immediately. Comments already left are kept.',
  'cancelar': 'Cancel',
  'revocarEnlace': 'Revoke link',
  'sobre': 'On “{elemento}”',
  'resuelto': 'Resolved',
  'resueltoPor': 'by {quien} on {fecha}',
  'version': 'Version to share',
  'opcionVersion': 'v{n} · {estado} · {fecha}',
  'paraQuien': 'Who it is for',
  'paraQuienEjemplo': 'Client’s Operations department',
  'paraQuienAyuda': 'Only so the team knows who you sent it to: ProcessIQ does not send anything.',
  'dias': 'Days until it expires',
  'diasAyuda': 'Between 1 and 90. After that, the link stops working.',
  'puedeComentar': 'Can leave comments',
  'queVera': 'Anyone with the link will see this entire version (diagram, process sheet and activity notes), but not the project, other versions or the team. The shared view is in Spanish.',
  'crearEnlace': 'Create link',
  'enlaceA': 'Link to <strong>v{n}</strong> for <strong>{destinatario}</strong>.',
  'hasta': 'Valid until {fecha}',
  'soloAhora': 'This link is shown only once. Copy it and send it through your usual channel: it cannot be retrieved later (only revoked).',
  'enlaceCliente': 'Link for the client',
  'copiado': 'Copied',
  'copiar': 'Copy',
  'verComoCliente': 'View as the client',
  'vistaEnEspanol': 'The client’s view is in Spanish.',
  'hecho': 'Done'
} as const satisfies Traduccion<typeof es>;

export const useT = definirTextos(es, en);
