// Textos del shell en inglés. El tipo obliga a tener todas las claves de es.ts,
// con sus variables {x} y etiquetas <x>: si falta algo, no compila.
// Inglés de EE. UU., con el vocabulario de consultoría de procesos (BPMN,
// As-Is/To-Be, pain points, KPI). Los nombres de menús del editor, que sigue en
// español, se citan en español con la traducción entre paréntesis.
import type { Traduccion } from '../i18n';
import type { TextosShell } from './es';

export const en = {
  // ---------------------------------------------------------------- Common
  'comun.unMomento': 'One moment…',
  'comun.cargando': 'Loading…',
  'comun.algoSalioMal': 'Something went wrong.',
  'comun.cancelar': 'Cancel',
  'comun.guardar': 'Save',
  'comun.cerrar': 'Close',
  'comun.hecho': 'Done',
  'comun.quitar': 'Remove',
  'comun.editar': 'Edit',
  'comun.eliminar': 'Delete',
  'comun.anadir': 'Add',
  'comun.abrir': 'Open',
  'comun.nombre': 'Name',
  'comun.correo': 'Email',
  'comun.rol': 'Role',
  'comun.rolDe': 'Role of {nombre}',
  'comun.cliente': 'Client',
  'comun.descripcion': 'Description',
  'comun.industria': 'Industry',
  'comun.fecha': 'Date',
  'comun.estado': 'Status',
  'comun.acciones': 'Actions',
  'comun.archivado': 'Archived',
  'comun.proyectos': 'Projects',
  'comun.proyecto': 'Project',
  'comun.proceso': 'Process',
  'comun.tu': '(you)',
  'comun.ruta': 'Breadcrumb',
  'comun.xDeY': '{a} of {b}',
  'comun.elementos': { uno: '{n} element', otros: '{n} elements' },
  'comun.importadoDe': 'Imported from {archivo}',
  'comun.abrirEnEditor': 'Open in editor',
  'comun.editorEnEspanol': 'The editor opens in Spanish: it has not been translated yet.',
  'comun.copiar': 'Copy',
  'comun.copiada': 'Copied',
  'comun.partirDe': 'Start from',

  // ---------------------------------------------------------------- Language and error screen
  'idioma.grupo': 'Language',
  'fallo.titulo': 'Something went wrong',
  'fallo.texto': 'This screen failed to load. The error has been logged so we can look into it.',
  'fallo.recargar': 'Reload',

  // ---------------------------------------------------------------- Header and menu
  'menu.marca': 'ProcessIQ · Projects',
  'menu.secciones': 'Sections',
  'menu.proyectos': 'Projects',
  'menu.portafolio': 'Portfolio',
  'menu.conocimiento': 'Knowledge',
  'menu.administracion': 'Admin',
  'menu.usuarios': 'Users',
  'menu.catalogos': 'Catalogs',
  'menu.auditoria': 'Audit log',
  'menu.ia': 'AI',
  'menu.sistema': 'System',
  'menu.editorLibre': 'Standalone editor',
  'menu.editorLibreTitulo': 'The editor without a project (work is saved in this browser). The editor is in Spanish.',
  'menu.cambiarClave': 'Change password',
  'menu.salir': 'Sign out',
  'menu.problemasSistema': 'There are issues: check “System”',
  'menu.problemasPantalla': 'There are issues: check this screen',
  'sesion.soloAdmin': 'This section is for administrators only.',

  // ---------------------------------------------------------------- Sign in
  'entrar.titulo': 'Sign in',
  'entrar.intro': 'Sign in with your account to work on your team’s projects.',
  'entrar.correo': 'Email',
  'entrar.clave': 'Password',
  'entrar.boton': 'Sign in',
  'entrar.sinCuenta': 'No account, or forgot your password? Ask an administrator.',
  'entrar.editorSinCuenta': 'You can also <enlace>use the editor without an account</enlace> (your work stays in this browser; the editor is in Spanish).',
  'clave.titulo': 'Change password',
  'clave.avisoTemporal': 'You are using a temporary password. Choose your own to continue.',
  'clave.temporal': 'Temporary password',
  'clave.actual': 'Current password',
  'clave.nueva': 'New password',
  'clave.nuevaAyuda': 'At least 10 characters, not only digits, and not containing your email username.',
  'clave.repetir': 'Confirm new password',
  'clave.noCoinciden': 'The two new passwords do not match.',
  'clave.guardar': 'Save password',
  'claveTemporal.texto': 'Temporary password for <strong>{para}</strong>. It is shown only this once: share it through a secure channel. They will be asked to change it the first time they sign in.',

  // ---------------------------------------------------------------- Projects
  'proyectos.titulo': 'Projects',
  'proyectos.introAdmin': 'All projects in your organization.',
  'proyectos.introMiembro': 'The projects you are a member of.',
  'proyectos.importar': 'Import processes',
  'proyectos.nuevo': 'New project',
  'proyectos.oferta': {
    uno: 'This browser’s standalone editor has “{nombre}” ({n} element).',
    otros: 'This browser’s standalone editor has “{nombre}” ({n} elements).'
  },
  'proyectos.sinNombre': 'an unnamed process',
  'proyectos.llevar': 'Import it into a project',
  'proyectos.noGracias': 'No, thanks',
  'proyectos.vacioLector': 'You are not a member of any project yet. Ask a project owner to add you.',
  'proyectos.vacio': 'There are no projects yet. Create the first one with “New project”.',
  'proyectos.todosArchivados': 'All your projects are archived.',
  'proyectos.creadoEl': 'Created {fecha}',
  'proyectos.mostrarArchivados': 'Show archived ({n})',
  'proyectos.seraPropietario': 'You will be the owner: you can add members and approve revisions.',
  'proyectos.crear': 'Create project',

  // ---------------------------------------------------------------- A project
  'proyecto.archivadoAviso': 'Archived project: you can view it, but it cannot be changed.',
  'proyecto.tuRol': 'Your role: <strong>{rol}</strong>',
  'proyecto.ajustes': 'Settings',
  'proyecto.ajustesTitulo': 'Project settings',
  'proyecto.nuevoProceso': 'New process',
  'proyecto.procesos': 'Processes',
  'proyecto.sinProcesosEscribe': 'No processes yet. Create an empty one or import a JSON file exported from the editor.',
  'proyecto.sinProcesos': 'No processes yet.',
  'proyecto.ultimaRevision': 'Latest revision',
  'proyecto.actualizado': 'Updated',
  'proyecto.sinRevisiones': 'No revisions',
  'proyecto.miembros': 'Members',
  'proyecto.anadirMiembro': 'Add member',
  'proyecto.quitarConfirmar': 'Remove {nombre} from the project?',
  'proyecto.adminNoMiembro': 'As an administrator, you can see and manage every project, even those you are not a member of.',
  'proyecto.todosMiembros': 'All active accounts are already members. An administrator can create new accounts.',
  'proyecto.persona': 'Person',
  'proyecto.rolEnProyecto': 'Project role',
  'proyecto.explicacionRoles': 'Editor: saves revisions. Reviewer: approves or sends back. Viewer: read-only. Owner: everything, including members.',
  'proyecto.jsonInvalido': 'The file is not valid JSON. Use “Exportar → JSON” (Export → JSON) in the editor.',
  'proyecto.origenVacio': 'An empty process',
  'proyecto.origenPlantilla': 'An organization template',
  'proyecto.origenArchivo': 'A JSON file exported from the editor',
  'proyecto.naceVacio': 'The process starts empty and you draw it in the editor.',
  'proyecto.plantilla': 'Template',
  'proyecto.copiaPlantilla': 'The process is created with version 1 copied from the template and with this project’s client.',
  'proyecto.archivoJson': 'JSON file (“Exportar → JSON” in the editor)',
  'proyecto.nombreProceso': 'Process name',
  'proyecto.crearProceso': 'Create process',
  'proyecto.archivarConfirmar': 'Once archived, the project becomes read-only. Continue?',
  'proyecto.reactivar': 'Reactivate project',
  'proyecto.archivar': 'Archive project',

  // ---------------------------------------------------------------- A process
  'proceso.tuRolActualizado': 'Your role: <strong>{rol}</strong> · Updated {fecha}',
  'proceso.renombrar': 'Rename',
  'proceso.renombrarTitulo': 'Rename process',
  'proceso.abrirUltima': 'Open the latest version in the editor',
  'proceso.empezar': 'Start drawing it in the editor',
  'proceso.archivadoAviso': 'The project is archived: revisions can be viewed but not changed.',
  'proceso.revisiones': 'Revisions',
  'proceso.explicacion': 'Every “Guardar revisión” (Save revision) in the editor creates a new version. A draft revision is submitted for review; the approver approves it or sends it back. Approved revisions no longer change.',
  'proceso.plantillaCreada': 'Template “{nombre}” created. It can now be chosen when creating a process; manage it in Catalogs.',
  'proceso.sinRevisiones': 'No revisions yet. Open the editor and use “Guardar revisión” (Save revision).',
  'proceso.version': 'Version',
  'proceso.autor': 'Author',
  'proceso.mensaje': 'Message',
  'proceso.comoPlantillaTitulo': 'Save v{n} as a template',
  'proceso.abiertoPor': { uno: 'Currently open by:', otros: 'Currently open by:' },
  'proceso.presenciaEditando': '{nombre}: editing {donde}',
  'proceso.presenciaViendo': '{nombre}: viewing {donde}',
  'proceso.dondeAmbos': 'in the editor and on the process page',
  'proceso.dondeEditor': 'in the editor',
  'proceso.dondeShell': 'on the process page',
  'proceso.presente': '{iniciales} · {nombre}',
  'proceso.presenteEditando': '{iniciales} · {nombre}, editing',
  'proceso.ramificadaTitulo': 'Saved from a version that was no longer the latest',
  'proceso.aPartirDe': 'based on v{n}',
  'proceso.enviarRevision': 'Submit for review',
  'proceso.aprobar': 'Approve',
  'proceso.devolver': 'Send back',
  'proceso.comoPlantilla': 'Save as template',
  'proceso.plantillaExplicacion': 'The template copies this version’s diagram, process sheet and views, but not the client, the governance people, the change history or the measured values. Check that no text mentions the client.',
  'proceso.nombrePlantilla': 'Template name',
  'proceso.industriaAyuda': 'If left blank, the process’s industry is used.',
  'proceso.guardarPlantilla': 'Save template',

  // ---------------------------------------------------------------- Import
  'importar.titulo': 'Import processes',
  'importar.procesoEditorLibre': 'Process from the standalone editor',
  'importar.procesoImportado': 'Imported process',
  'importar.mensajeNavegador': 'Imported from the standalone editor of a browser',
  'importar.intro': 'Bring into a project the work saved in <strong>this browser’s standalone editor</strong> or in JSON files exported from the editor (on another computer, export them with “Exportar → JSON” (Export → JSON) and upload them here). Nothing is removed from this browser unless you ask.',
  'importar.resultado': 'Result',
  'importar.importado': '“{nombre}” imported.',
  'importar.verRevisiones': 'View its revisions',
  'importar.noSePudo': 'Could not import: {error}',
  'importar.sigueEnNavegador': 'The process is also still in this browser’s standalone editor.',
  'importar.vaciar': 'Clear the standalone editor',
  'importar.vaciado': 'This browser’s standalone editor is now empty.',
  'importar.queImportar': 'What to import',
  'importar.nadaEnNavegador': 'There is nothing in this browser’s standalone editor. You can upload JSON files exported from the editor.',
  'importar.deDonde': 'Source',
  'importar.elementos': 'Elements',
  'importar.ultimoCambio': 'Last change',
  'importar.nombreDe': 'Process name {nombre}',
  'importar.origenNavegador': 'This browser’s standalone editor',
  'importar.anadirArchivos': 'Add JSON files exported from the editor',
  'importar.errorArchivo': '{archivo}: {error}',
  'importar.errorJson': 'The file is not valid JSON.',
  'importar.errorNoEsProceso': 'It does not look like a process exported from the editor (the list of elements is missing).',
  'importar.aQueProyecto': 'Target project',
  'importar.sinDestinos': 'You have no projects where you can create processes. Create one in <enlace>Projects</enlace> or ask to be added as an editor.',
  'importar.destino': 'Target project',
  'importar.boton': { uno: 'Import the process', otros: 'Import {n} processes' },

  // ---------------------------------------------------------------- Users and audit log
  'usuarios.titulo': 'Users',
  'usuarios.intro': 'Your organization’s local accounts. Creating an account or resetting its password generates a temporary password.',
  'usuarios.nuevo': 'New user',
  'usuarios.ultimoAcceso': 'Last sign-in',
  'usuarios.desactivada': 'Deactivated',
  'usuarios.claveTemporal': 'Temporary password',
  'usuarios.activa': 'Active',
  'usuarios.restablecerConfirmar': 'Reset {nombre}’s password? Their open sessions will be closed.',
  'usuarios.restablecer': 'Reset password',
  'usuarios.desactivar': 'Deactivate',
  'usuarios.reactivar': 'Reactivate',
  'usuarios.nombreApellido': 'Full name',
  'usuarios.explicacionRoles': 'Consultant: creates projects. Viewer: only takes part where invited. Administrator: also manages users and sees every project.',
  'usuarios.crear': 'Create account',
  'auditoria.titulo': 'Audit log',
  'auditoria.intro': 'Who did what, and when. The 200 most recent events are shown.',
  'auditoria.mostrar': 'Show',
  'auditoria.todo': 'Everything',
  'auditoria.usuarios': 'Users and sessions',
  'auditoria.proyectos': 'Projects',
  'auditoria.procesos': 'Processes',
  'auditoria.revisiones': 'Revisions',
  'auditoria.sinEventos': 'No events.',
  'auditoria.usuario': 'User',
  'auditoria.accion': 'Action',
  'auditoria.detalle': 'Details',
  'auditoria.ip': 'IP',
  'noEncontrada.titulo': 'Not found',
  'noEncontrada.texto': 'This page does not exist. <enlace>Back to projects</enlace>.',

  // ---------------------------------------------------------------- AI usage
  'ia.titulo': 'AI usage',
  'ia.intro': 'What the server-side AI cost this month, at Anthropic list prices. Limits are set on the server (.env).',
  'ia.sinConfigurar': 'Server-side AI is not configured: <code>ANTHROPIC_API_KEY</code> is missing from the server’s <code>.env</code> file.',
  'ia.presupuesto': 'This month’s budget',
  'ia.deEsteMes': 'of {presupuesto} this month · per-person limit {tope}',
  'ia.porPersona': 'By person',
  'ia.nadie': 'No one has used the server-side AI this month.',
  'ia.persona': 'Person',
  'ia.ejecuciones': 'Runs',
  'ia.gastoMes': 'Spend this month',
  'ia.enElTope': 'at limit',
  'ia.ultimas': 'Recent runs',
  'ia.sinEjecuciones': 'No runs yet.',
  'ia.que': 'Task',
  'ia.modelo': 'Model',
  'ia.tokens': 'Tokens (input / output)',
  'ia.coste': 'Cost',
  'ia.intentos': '({n} attempts)',
  'ia.estadoEnCola': 'Queued',
  'ia.estadoEjecutando': 'Running',
  'ia.estadoCompletada': 'Completed',
  'ia.estadoFallida': 'Failed',
  'ia.estadoCancelada': 'Canceled',
  'ia.generar': 'Generate process',
  'ia.pains': 'Pain point analysis',
  'ia.analisis': 'Analysis ({tarea})',

  // ---------------------------------------------------------------- System
  'sistema.titulo': 'System',
  'sistema.version': 'Version <code>{version}</code> · refreshes every 15 s · {fecha}',
  'sistema.todoEnOrden': 'All systems normal.',
  'sistema.bien': 'OK',
  'sistema.revisar': 'Check',
  'sistema.problema': 'Problem',
  'sistema.nunca': 'never',
  'sistema.haceSegundos': '{n} s ago',
  'sistema.haceMinutos': '{n} min ago',
  'sistema.haceHoras': '{n} h ago',
  'sistema.haceDias': '{n} days ago',
  'sistema.api': 'API',
  'sistema.activaDesde': 'Up since',
  'sistema.node': 'Node',
  'sistema.baseDeDatos': 'Database',
  'sistema.respuesta': 'Response time',
  'sistema.tamano': 'Size',
  'sistema.migraciones': 'Migrations',
  'sistema.worker': 'AI worker',
  'sistema.ultimoLatido': 'Last heartbeat',
  'sistema.trabajandoEn': 'Working on',
  'sistema.ia': 'AI',
  'sistema.clave': 'API key',
  'sistema.configurada': 'configured',
  'sistema.sinConfigurar': 'not configured',
  'sistema.enCola': 'Queued / running',
  'sistema.ultimas24': 'Last 24 h',
  'sistema.completadasFallidas': '{completadas} completed · {fallidas} failed',
  'sistema.copias': 'Backups',
  'sistema.carpeta': 'Folder',
  'sistema.noVisible': 'not visible to the API',
  'sistema.ultima': 'Latest',
  'sistema.ninguna': 'none',
  'sistema.guardadas': 'Stored',
  'sistema.discoLibre': 'Free disk space',
  'sistema.errores': 'Errors in the last 7 days',
  'sistema.erroresIntro': '{n} in the last 24 h. Repeated errors are grouped; click one to see the details.',
  'sistema.sinErrores': 'No errors recorded.',
  'sistema.ultimaVez': 'Last seen',
  'sistema.origen': 'Source',
  'sistema.error': 'Error',
  'sistema.veces': 'Count',
  'sistema.donde': 'Where',
  'sistema.detalle': 'Error details',
  'sistema.sinSesion': 'not signed in',
  'sistema.referencia': 'reference {referencia}',

  // ---------------------------------------------------------------- Catalogs
  'catalogos.titulo': 'Catalogs',
  'catalogos.intro': 'What the editor uses in project processes. The standalone editor keeps the built-in catalogs.',
  'catalogos.pestanaKpis': 'KPIs',
  'catalogos.pestanaVerbos': 'Playbook verbs',
  'catalogos.pestanaTemas': 'PPTX themes',
  'catalogos.pestanaPlantillas': 'Process templates',
  'catalogos.todasIndustrias': 'All industries',
  'catalogos.buscarKpi': 'Search KPIs',
  'catalogos.buscarKpiEjemplo': 'Search KPIs…',
  'catalogos.nuevoKpi': 'New KPI',
  'catalogos.editarKpi': 'Edit KPI',
  'catalogos.ningunKpi': 'No KPIs match.',
  'catalogos.kpi': 'KPI',
  'catalogos.macroproceso': 'Macroprocess',
  'catalogos.unidad': 'Unit',
  'catalogos.unidadEjemplo': '%, days, hours…',
  'catalogos.referencia': 'Benchmark',
  'catalogos.referenciaBenchmark': 'Benchmark',
  'catalogos.activo': 'Active',
  'catalogos.desactivado': 'Deactivated',
  'catalogos.activar': 'Activate',
  'catalogos.desactivar': 'Deactivate',
  'catalogos.codigoKpi': 'Code <code>{codigo}</code>: processes store their values under it, so it never changes.',
  'catalogos.crearKpi': 'Create KPI',
  'catalogos.verbosIntro': 'The editor’s linter requires every activity to start with an infinitive verb (activities are written in Spanish). <strong>Banned</strong> verbs are flagged as errors with the reason you enter; <strong>allowed</strong> verbs raise no warning.',
  'catalogos.prohibidos': 'Banned ({n})',
  'catalogos.permitidos': 'Allowed ({n})',
  'catalogos.verbo': 'Verb',
  'catalogos.motivoConsultor': 'Reason shown to the consultant',
  'catalogos.permitir': 'Allow',
  'catalogos.verboProhibido': 'Banned verb',
  'catalogos.verboEjemplo': 'verb',
  'catalogos.motivo': 'Reason',
  'catalogos.motivoEjemplo': 'Why it should not be used and what to use instead',
  'catalogos.prohibir': 'Ban',
  'catalogos.quitarVerbo': 'Remove {verbo}',
  'catalogos.verboPermitido': 'Allowed verb',
  'catalogos.verboPermitidoEjemplo': 'infinitive verb (Spanish)',
  'catalogos.colorDk1': 'Primary (titles and bars)',
  'catalogos.colorAcento': 'Accent',
  'catalogos.colorLt2': 'Slide background',
  'catalogos.colorArena': 'Card background',
  'catalogos.colorGris': 'Secondary text',
  'catalogos.colorAntetitulo': 'Eyebrow text',
  'catalogos.colorSep': 'Dividers',
  'catalogos.colorChipRol': 'Role tag',
  'catalogos.colorTeal': 'Secondary',
  'catalogos.colorRosa': 'Status: alert',
  'catalogos.colorVerde': 'Status: good',
  'catalogos.colorCirculo': 'Numbering circles',
  'catalogos.colorPortadaFondo': 'Cover: background',
  'catalogos.colorPortadaTexto': 'Cover: text',
  'catalogos.colorPortadaSub': 'Cover: subtitle',
  'catalogos.temasIntro': 'Besides MBC and BBVA (built in), every active theme appears in the editor’s <strong>Exportar → PPTX</strong> (Export → PPTX) menu.',
  'catalogos.nuevoTema': 'New theme',
  'catalogos.nuevoTemaTitulo': 'New PPTX theme',
  'catalogos.sinTemas': 'There are no client themes yet. Create one based on the MBC or BBVA theme.',
  'catalogos.oculto': 'Hidden',
  'catalogos.oculta': 'Hidden',
  'catalogos.ocultar': 'Hide',
  'catalogos.mostrar': 'Show',
  'catalogos.eliminarTema': 'Delete the {nombre} theme?',
  'catalogos.temaTitulo': 'Theme: {nombre}',
  'catalogos.nombreCliente': 'Client name',
  'catalogos.clave': 'Key',
  'catalogos.claveAyuda': 'Lowercase letters, digits and hyphens. It identifies the theme and cannot be changed.',
  'catalogos.baseMbc': 'MBC (cover with photo)',
  'catalogos.baseBbva': 'BBVA (solid-color cover and closing slide)',
  'catalogos.despues': 'You can change colors, fonts and logos afterwards.',
  'catalogos.crearYEditar': 'Create and edit',
  'catalogos.imagenTipo': 'The image must be PNG or JPEG.',
  'catalogos.imagenPesada': 'The image is too large (1.4 MB max).',
  'catalogos.imagenIlegible': 'The image could not be read.',
  'catalogos.pie': 'Slide footer',
  'catalogos.autor': 'Author (file properties)',
  'catalogos.colores': 'Colors',
  'catalogos.tipografias': 'Fonts',
  'catalogos.texto': 'Body text',
  'catalogos.textoAyuda': 'The font must be installed on every computer that opens the PPTX.',
  'catalogos.titulos': 'Titles',
  'catalogos.logotipos': 'Logos and cover',
  'catalogos.logo': 'Logo on light background',
  'catalogos.logoInv': 'Logo on dark background',
  'catalogos.foto': 'Cover photo (optional)',
  'catalogos.sinImagen': 'No image',
  'catalogos.quitarFoto': 'Remove photo',
  'catalogos.anchoLogo': 'Logo width (inches)',
  'catalogos.altoLogo': 'Logo height (inches)',
  'catalogos.estiloCaratula': 'Cover style',
  'catalogos.caratulaFoto': 'With photo (like MBC)',
  'catalogos.caratulaColor': 'Solid color (like BBVA)',
  'catalogos.laminaCierre': 'Closing slide',
  'catalogos.guardarTema': 'Save theme',
  'catalogos.plantillasIntro': 'When you create a process in a project, you can start from an active template. Templates are created from a revision: on the process page, use <strong>Save as template</strong>. The client, the governance people, the process sheet change history and the measured values are removed; check that no text mentions the client.',
  'catalogos.sinPlantillas': 'There are no templates yet. Open a process and use “Save as template” on one of its revisions.',
  'catalogos.plantilla': 'Template',
  'catalogos.elementos': 'Elements',
  'catalogos.creadaPor': 'Created by',
  'catalogos.actualizada': 'Updated',
  'catalogos.eliminarPlantilla': 'Delete the {nombre} template? Processes created from it are not affected.',
  'catalogos.plantillaTitulo': 'Template: {nombre}'
} as const satisfies Traduccion<TextosShell>;

/**
 * Tareas de IA del copiloto (TAREAS_IA de @processiq/ia, por su clave). En español se
 * usa la etiqueta del paquete; aquí solo va el inglés. Una tarea nueva sin traducir
 * se muestra con la etiqueta del paquete.
 */
export const TAREAS_IA_EN: Readonly<Record<string, string>> = {
  'suggest-kpis': 'Suggest applicable KPIs',
  'propose-tobe': 'Propose To-Be redesign',
  'raci': 'RACI matrix',
  'impact-effort': 'Impact–effort matrix',
  'automation': 'Automation opportunities',
  'backlog': 'Initiative backlog',
  'exec-summary': 'Executive summary',
  'sipoc': 'SIPOC',
  'bottleneck': 'Bottleneck and critical path'
};
