// Textos del shell en español: la fuente de verdad. El inglés (en.ts) tiene que
// tener las mismas claves, con las mismas variables {x} y etiquetas <x> (i18n.ts).
// Los módulos de iniciativa tienen su propio diccionario (modulos/<clave>/textos.ts).
export const es = {
  // ---------------------------------------------------------------- Común
  'comun.unMomento': 'Un momento…',
  'comun.cargando': 'Cargando…',
  'comun.algoSalioMal': 'Algo salió mal.',
  'comun.cancelar': 'Cancelar',
  'comun.guardar': 'Guardar',
  'comun.cerrar': 'Cerrar',
  'comun.hecho': 'Hecho',
  'comun.quitar': 'Quitar',
  'comun.editar': 'Editar',
  'comun.eliminar': 'Eliminar',
  'comun.anadir': 'Añadir',
  'comun.abrir': 'Abrir',
  'comun.nombre': 'Nombre',
  'comun.correo': 'Correo',
  'comun.rol': 'Rol',
  'comun.rolDe': 'Rol de {nombre}',
  'comun.cliente': 'Cliente',
  'comun.descripcion': 'Descripción',
  'comun.industria': 'Industria',
  'comun.fecha': 'Fecha',
  'comun.estado': 'Estado',
  'comun.acciones': 'Acciones',
  'comun.archivado': 'Archivado',
  'comun.proyectos': 'Proyectos',
  'comun.proyecto': 'Proyecto',
  'comun.proceso': 'Proceso',
  'comun.tu': '(tú)',
  'comun.ruta': 'Ruta',
  'comun.xDeY': '{a} de {b}',
  'comun.elementos': { uno: '{n} elemento', otros: '{n} elementos' },
  'comun.importadoDe': 'Importado de {archivo}',
  'comun.abrirEnEditor': 'Abrir en el editor',
  /** `title` de los enlaces al editor: vacío en español (el editor está en español). */
  'comun.editorEnEspanol': '',
  'comun.copiar': 'Copiar',
  'comun.copiada': 'Copiada',
  'comun.partirDe': 'Partir de',

  // ---------------------------------------------------------------- Idioma y pantalla de error
  'idioma.grupo': 'Idioma',
  'fallo.titulo': 'Algo salió mal',
  'fallo.texto': 'La pantalla falló al mostrarse. Ya quedó registrado para que lo revisemos.',
  'fallo.recargar': 'Recargar',

  // ---------------------------------------------------------------- Cabecera y menú
  'menu.marca': 'ProcessIQ · Proyectos',
  'menu.secciones': 'Secciones',
  'menu.proyectos': 'Proyectos',
  'menu.portafolio': 'Portafolio',
  'menu.conocimiento': 'Conocimiento',
  'menu.administracion': 'Administración',
  'menu.usuarios': 'Usuarios',
  'menu.catalogos': 'Catálogos',
  'menu.auditoria': 'Auditoría',
  'menu.ia': 'IA',
  'menu.sistema': 'Sistema',
  'menu.editorLibre': 'Editor libre',
  'menu.editorLibreTitulo': 'El editor, sin proyecto (trabajo guardado en este navegador)',
  'menu.cambiarClave': 'Cambiar contraseña',
  'menu.sesiones': 'Sesiones',
  'menu.salir': 'Salir',
  'menu.problemasSistema': 'Hay problemas: revisa «Sistema»',
  'menu.problemasPantalla': 'Hay problemas: revisa la pantalla',
  'sesion.soloAdmin': 'Esta sección es solo para administradores.',

  // ---------------------------------------------------------------- Acceso
  'entrar.titulo': 'Entrar',
  'entrar.intro': 'Entra con tu cuenta para trabajar en los proyectos del equipo.',
  'entrar.correo': 'Correo',
  'entrar.clave': 'Contraseña',
  'entrar.boton': 'Entrar',
  'entrar.sinCuenta': '¿No tienes cuenta o no recuerdas la contraseña? Pídesela a un administrador.',
  'entrar.editorSinCuenta': 'También puedes <enlace>usar el editor sin cuenta</enlace> (el trabajo queda en este navegador).',
  'clave.titulo': 'Cambiar contraseña',
  'clave.avisoTemporal': 'Estás usando una contraseña temporal. Elige una propia para continuar.',
  'clave.temporal': 'Contraseña temporal',
  'clave.actual': 'Contraseña actual',
  'clave.nueva': 'Contraseña nueva',
  'clave.nuevaAyuda': 'Al menos 10 caracteres, no solo números y sin tu usuario de correo.',
  'clave.repetir': 'Repite la contraseña nueva',
  'clave.noCoinciden': 'Las dos contraseñas nuevas no coinciden.',
  'clave.guardar': 'Guardar contraseña',
  'claveTemporal.texto': 'Contraseña temporal de <strong>{para}</strong>. Solo se muestra ahora: entrégasela por un canal seguro. Deberá cambiarla al entrar.',

  // ---------------------------------------------------------------- Sesiones abiertas
  'sesiones.titulo': 'Sesiones',
  'sesiones.intro': 'Los navegadores donde tu cuenta está abierta ahora. Si no reconoces alguno, cierra esa sesión y cambia tu contraseña.',
  'sesiones.navegador': 'Navegador',
  'sesiones.ip': 'IP',
  'sesiones.inicio': 'Inicio',
  'sesiones.caduca': 'Caduca',
  'sesiones.navegadorEn': '{navegador} en {sistema}',
  'sesiones.desconocido': 'Navegador desconocido',
  'sesiones.estaSesion': 'Esta sesión',
  'sesiones.cerrar': 'Cerrar',
  'sesiones.cerrarDe': 'Cerrar la sesión de {navegador}',
  'sesiones.cerrarOtras': 'Cerrar las demás sesiones',
  'sesiones.soloEsta': 'No tienes otras sesiones abiertas.',
  'sesiones.cerrada': 'Sesión cerrada: ese navegador tendrá que volver a entrar.',
  'sesiones.cerradas': {
    cero: 'No había otras sesiones abiertas.',
    uno: 'Se cerró {n} sesión: ese navegador tendrá que volver a entrar.',
    otros: 'Se cerraron {n} sesiones: esos navegadores tendrán que volver a entrar.'
  },
  'sesiones.nota': 'Cada sesión caduca sola a las pocas horas. Al cambiar la contraseña se cierran todas las demás.',

  // ---------------------------------------------------------------- Proyectos
  'proyectos.titulo': 'Proyectos',
  'proyectos.introAdmin': 'Todos los proyectos de la organización.',
  'proyectos.introMiembro': 'Los proyectos en los que participas.',
  'proyectos.importar': 'Importar procesos',
  'proyectos.nuevo': 'Nuevo proyecto',
  'proyectos.oferta': {
    uno: 'En el editor libre de este navegador tienes «{nombre}» ({n} elemento).',
    otros: 'En el editor libre de este navegador tienes «{nombre}» ({n} elementos).'
  },
  'proyectos.sinNombre': 'un proceso sin nombre',
  'proyectos.llevar': 'Llevarlo a un proyecto',
  'proyectos.noGracias': 'No, gracias',
  'proyectos.vacioLector': 'Todavía no participas en ningún proyecto. Pide a su propietario que te añada.',
  'proyectos.vacio': 'Todavía no hay proyectos. Crea el primero con «Nuevo proyecto».',
  'proyectos.todosArchivados': 'Todos tus proyectos están archivados.',
  'proyectos.creadoEl': 'Creado el {fecha}',
  'proyectos.mostrarArchivados': 'Mostrar archivados ({n})',
  'proyectos.seraPropietario': 'Serás su propietario: podrás añadir miembros y aprobar revisiones.',
  'proyectos.crear': 'Crear proyecto',

  // ---------------------------------------------------------------- Un proyecto
  'proyecto.archivadoAviso': 'Proyecto archivado: se puede consultar, pero no admite cambios.',
  'proyecto.tuRol': 'Tu rol: <strong>{rol}</strong>',
  'proyecto.ajustes': 'Ajustes',
  'proyecto.ajustesTitulo': 'Ajustes del proyecto',
  'proyecto.nuevoProceso': 'Nuevo proceso',
  'proyecto.procesos': 'Procesos',
  'proyecto.sinProcesosEscribe': 'Sin procesos todavía. Crea uno vacío o importa el JSON exportado desde el editor.',
  'proyecto.sinProcesos': 'Sin procesos todavía.',
  'proyecto.ultimaRevision': 'Última revisión',
  'proyecto.actualizado': 'Actualizado',
  'proyecto.sinRevisiones': 'Sin revisiones',
  'proyecto.miembros': 'Miembros',
  'proyecto.anadirMiembro': 'Añadir miembro',
  'proyecto.quitarConfirmar': '¿Quitar a {nombre} del proyecto?',
  'proyecto.adminNoMiembro': 'Como administrador ves y gestionas todos los proyectos aunque no seas miembro.',
  'proyecto.todosMiembros': 'Todas las cuentas activas ya son miembros. Un administrador puede crear cuentas nuevas.',
  'proyecto.persona': 'Persona',
  'proyecto.rolEnProyecto': 'Rol en el proyecto',
  'proyecto.explicacionRoles': 'Editor: guarda revisiones. Revisor: aprueba o devuelve. Lector: solo consulta. Propietario: todo, incluidos los miembros.',
  'proyecto.jsonInvalido': 'El archivo no es un JSON válido. Usa «Exportar → JSON» del editor.',
  'proyecto.origenVacio': 'Un proceso vacío',
  'proyecto.origenPlantilla': 'Una plantilla de la organización',
  'proyecto.origenArchivo': 'Un JSON exportado del editor',
  'proyecto.naceVacio': 'El proceso nace vacío y lo dibujas en el editor.',
  'proyecto.plantilla': 'Plantilla',
  'proyecto.copiaPlantilla': 'Se crea con la versión 1 copiada de la plantilla y el cliente de este proyecto.',
  'proyecto.archivoJson': 'Archivo JSON («Exportar → JSON» del editor)',
  'proyecto.nombreProceso': 'Nombre del proceso',
  'proyecto.crearProceso': 'Crear proceso',
  'proyecto.archivarConfirmar': 'Al archivarlo, el proyecto queda en solo lectura. ¿Continuar?',
  'proyecto.reactivar': 'Reactivar proyecto',
  'proyecto.archivar': 'Archivar proyecto',

  // ---------------------------------------------------------------- Un proceso
  'proceso.tuRolActualizado': 'Tu rol: <strong>{rol}</strong> · Actualizado el {fecha}',
  'proceso.renombrar': 'Renombrar',
  'proceso.renombrarTitulo': 'Renombrar proceso',
  'proceso.abrirUltima': 'Abrir la última versión en el editor',
  'proceso.empezar': 'Empezar a dibujarlo en el editor',
  'proceso.archivadoAviso': 'El proyecto está archivado: las revisiones se pueden consultar, pero no cambiar.',
  'proceso.revisiones': 'Revisiones',
  'proceso.explicacion': 'Cada «Guardar revisión» del editor crea una versión nueva. Una revisión en borrador se envía a revisión; quien aprueba la aprueba o la devuelve. Las aprobadas ya no cambian.',
  'proceso.plantillaCreada': 'Plantilla «{nombre}» creada. Ya se puede elegir al crear un proceso; se gestiona en Catálogos.',
  'proceso.sinRevisiones': 'Todavía no hay revisiones. Abre el editor y usa «Guardar revisión».',
  'proceso.version': 'Versión',
  'proceso.autor': 'Autor',
  'proceso.mensaje': 'Mensaje',
  'proceso.comoPlantillaTitulo': 'Guardar v{n} como plantilla',
  'proceso.abiertoPor': { uno: 'Ahora lo tiene abierto:', otros: 'Ahora lo tienen abierto:' },
  'proceso.presenciaEditando': '{nombre}: editando {donde}',
  'proceso.presenciaViendo': '{nombre}: viendo {donde}',
  'proceso.dondeAmbos': 'en el editor y en la página del proceso',
  'proceso.dondeEditor': 'en el editor',
  'proceso.dondeShell': 'en la página del proceso',
  'proceso.presente': '{iniciales} · {nombre}',
  'proceso.presenteEditando': '{iniciales} · {nombre}, editando',
  'proceso.enVersion': '({versiones})',
  'proceso.versionAbierta': 'v{n}',
  'proceso.versionAbiertaAnterior': 'v{n}, versión anterior',
  'proceso.ramificadaTitulo': 'Se guardó a partir de una versión que ya no era la última',
  'proceso.aPartirDe': 'a partir de v{n}',
  'proceso.enviarRevision': 'Enviar a revisión',
  'proceso.aprobar': 'Aprobar',
  'proceso.devolver': 'Devolver',
  'proceso.comoPlantilla': 'Guardar como plantilla',
  'proceso.plantillaExplicacion': 'La plantilla copia el diagrama, la ficha y las vistas de esta versión, sin el cliente, las personas de la gobernanza, el historial de cambios ni los valores medidos. Revisa que los textos no nombren al cliente.',
  'proceso.nombrePlantilla': 'Nombre de la plantilla',
  'proceso.industriaAyuda': 'Si la dejas vacía, se toma la del proceso.',
  'proceso.guardarPlantilla': 'Guardar plantilla',

  // ---------------------------------------------------------------- Importar
  'importar.titulo': 'Importar procesos',
  'importar.procesoEditorLibre': 'Proceso del editor libre',
  'importar.procesoImportado': 'Proceso importado',
  'importar.mensajeNavegador': 'Importado del editor libre de un navegador',
  'importar.intro': 'Lleva a un proyecto lo que tienes en el <strong>editor libre de este navegador</strong> o en archivos JSON exportados desde el editor (en otro equipo: «Exportar → JSON» y súbelos aquí). Nada se borra del navegador salvo que lo pidas.',
  'importar.resultado': 'Resultado',
  'importar.importado': '«{nombre}» importado.',
  'importar.verRevisiones': 'Ver sus revisiones',
  'importar.noSePudo': 'No se pudo importar: {error}',
  'importar.sigueEnNavegador': 'El proceso sigue también en el editor libre de este navegador.',
  'importar.vaciar': 'Vaciar el editor libre',
  'importar.vaciado': 'El editor libre de este navegador quedó vacío.',
  'importar.queImportar': 'Qué importar',
  'importar.nadaEnNavegador': 'No hay nada en el editor libre de este navegador. Puedes subir archivos JSON exportados desde el editor.',
  'importar.deDonde': 'De dónde',
  'importar.elementos': 'Elementos',
  'importar.ultimoCambio': 'Último cambio',
  'importar.nombreDe': 'Nombre del proceso {nombre}',
  'importar.origenNavegador': 'Editor libre de este navegador',
  'importar.anadirArchivos': 'Añadir archivos JSON exportados del editor',
  'importar.errorArchivo': '{archivo}: {error}',
  'importar.errorJson': 'No es un JSON válido.',
  'importar.errorNoEsProceso': 'No parece un proceso exportado desde el editor (falta la lista de elementos).',
  'importar.aQueProyecto': 'A qué proyecto',
  'importar.sinDestinos': 'No tienes proyectos donde puedas crear procesos. Crea uno en <enlace>Proyectos</enlace> o pide que te añadan como editor.',
  'importar.destino': 'Proyecto de destino',
  'importar.boton': { uno: 'Importar el proceso', otros: 'Importar {n} procesos' },

  // ---------------------------------------------------------------- Usuarios y auditoría
  'usuarios.titulo': 'Usuarios',
  'usuarios.intro': 'Cuentas locales de la organización. Al crear una cuenta o restablecer su contraseña se genera una contraseña temporal.',
  'usuarios.nuevo': 'Nuevo usuario',
  'usuarios.ultimoAcceso': 'Último acceso',
  'usuarios.desactivada': 'Desactivada',
  'usuarios.claveTemporal': 'Contraseña temporal',
  'usuarios.activa': 'Activa',
  'usuarios.restablecerConfirmar': '¿Restablecer la contraseña de {nombre}? Se cerrarán sus sesiones.',
  'usuarios.restablecer': 'Restablecer contraseña',
  'usuarios.desactivar': 'Desactivar',
  'usuarios.reactivar': 'Reactivar',
  'usuarios.cerrarSesiones': 'Cerrar sesiones',
  'usuarios.cerrarSesionesConfirmar': '¿Cerrar todas las sesiones de {nombre}? Tendrá que volver a entrar en cada navegador. La cuenta sigue activa.',
  'usuarios.sesionesCerradas': {
    cero: '{nombre} no tenía sesiones abiertas.',
    uno: 'Se cerró {n} sesión de {nombre}.',
    otros: 'Se cerraron {n} sesiones de {nombre}.'
  },
  'usuarios.nombreApellido': 'Nombre y apellido',
  'usuarios.explicacionRoles': 'Consultor: crea proyectos. Lector: solo participa donde lo invitan. Administrador: además gestiona usuarios y ve todos los proyectos.',
  'usuarios.crear': 'Crear cuenta',
  'auditoria.titulo': 'Auditoría',
  'auditoria.intro': 'Quién hizo qué y cuándo. Se muestran los 200 eventos más recientes.',
  'auditoria.mostrar': 'Mostrar',
  'auditoria.todo': 'Todo',
  'auditoria.usuarios': 'Usuarios y sesiones',
  'auditoria.proyectos': 'Proyectos',
  'auditoria.procesos': 'Procesos',
  'auditoria.revisiones': 'Revisiones',
  'auditoria.sinEventos': 'Sin eventos.',
  'auditoria.usuario': 'Usuario',
  'auditoria.accion': 'Acción',
  'auditoria.detalle': 'Detalle',
  'auditoria.ip': 'IP',
  'noEncontrada.titulo': 'No encontrada',
  'noEncontrada.texto': 'Esta página no existe. <enlace>Volver a los proyectos</enlace>.',

  // ---------------------------------------------------------------- Consumo de IA
  'ia.titulo': 'Consumo de IA',
  'ia.intro': 'Lo que costó la IA del servidor este mes, a precio de lista de Anthropic. Los topes se configuran en el servidor (.env).',
  'ia.sinConfigurar': 'La IA del servidor no está configurada: falta <code>ANTHROPIC_API_KEY</code> en el archivo <code>.env</code> del servidor.',
  'ia.presupuesto': 'Presupuesto del mes',
  'ia.deEsteMes': 'de {presupuesto} este mes · tope por persona {tope}',
  'ia.porPersona': 'Por persona',
  'ia.nadie': 'Nadie ha usado la IA del servidor este mes.',
  'ia.persona': 'Persona',
  'ia.ejecuciones': 'Ejecuciones',
  'ia.gastoMes': 'Gasto del mes',
  'ia.enElTope': 'en el tope',
  'ia.ultimas': 'Últimas ejecuciones',
  'ia.sinEjecuciones': 'Sin ejecuciones todavía.',
  'ia.que': 'Qué',
  'ia.modelo': 'Modelo',
  'ia.tokens': 'Tokens (entrada / salida)',
  'ia.coste': 'Coste',
  'ia.intentos': '({n} intentos)',
  'ia.estadoEnCola': 'En cola',
  'ia.estadoEjecutando': 'Ejecutando',
  'ia.estadoCompletada': 'Completada',
  'ia.estadoFallida': 'Fallida',
  'ia.estadoCancelada': 'Cancelada',
  'ia.generar': 'Generar proceso',
  'ia.pains': 'Análisis de dolores',
  'ia.analisis': 'Análisis ({tarea})',

  // ---------------------------------------------------------------- Sistema
  'sistema.titulo': 'Sistema',
  'sistema.version': 'Versión <code>{version}</code> · se actualiza cada 15 s · {fecha}',
  'sistema.todoEnOrden': 'Todo en orden.',
  'sistema.bien': 'Bien',
  'sistema.revisar': 'Revisar',
  'sistema.problema': 'Problema',
  'sistema.nunca': 'nunca',
  'sistema.haceSegundos': 'hace {n} s',
  'sistema.haceMinutos': 'hace {n} min',
  'sistema.haceHoras': 'hace {n} h',
  'sistema.haceDias': 'hace {n} días',
  'sistema.api': 'API',
  'sistema.activaDesde': 'Activa desde',
  'sistema.node': 'Node',
  'sistema.baseDeDatos': 'Base de datos',
  'sistema.respuesta': 'Respuesta',
  'sistema.tamano': 'Tamaño',
  'sistema.migraciones': 'Migraciones',
  'sistema.worker': 'Worker de IA',
  'sistema.ultimoLatido': 'Último latido',
  'sistema.trabajandoEn': 'Trabajando en',
  'sistema.ia': 'IA',
  'sistema.clave': 'Clave',
  'sistema.configurada': 'configurada',
  'sistema.sinConfigurar': 'sin configurar',
  'sistema.enCola': 'En cola / en curso',
  'sistema.ultimas24': 'Últimas 24 h',
  'sistema.completadasFallidas': '{completadas} completadas · {fallidas} fallidas',
  'sistema.copias': 'Copias de seguridad',
  'sistema.carpeta': 'Carpeta',
  'sistema.noVisible': 'no visible para la API',
  'sistema.ultima': 'Última',
  'sistema.ninguna': 'ninguna',
  'sistema.guardadas': 'Guardadas',
  'sistema.discoLibre': 'Disco libre',
  'sistema.errores': 'Errores de los últimos 7 días',
  'sistema.erroresIntro': '{n} en las últimas 24 h. Se agrupan los repetidos; pulsa uno para ver el detalle.',
  'sistema.sinErrores': 'Sin errores registrados.',
  'sistema.ultimaVez': 'Última vez',
  'sistema.origen': 'Origen',
  'sistema.error': 'Error',
  'sistema.veces': 'Veces',
  'sistema.donde': 'Dónde',
  'sistema.detalle': 'Detalle del error',
  'sistema.sinSesion': 'sin sesión',
  'sistema.referencia': 'referencia {referencia}',

  // ---------------------------------------------------------------- Catálogos
  'catalogos.titulo': 'Catálogos',
  'catalogos.intro': 'Lo que usa el editor en los procesos de los proyectos. El editor libre sigue con los catálogos de fábrica.',
  'catalogos.pestanaKpis': 'KPIs',
  'catalogos.pestanaVerbos': 'Verbos del Playbook',
  'catalogos.pestanaTemas': 'Temas PPTX',
  'catalogos.pestanaPlantillas': 'Plantillas de proceso',
  'catalogos.todasIndustrias': 'Todas las industrias',
  'catalogos.buscarKpi': 'Buscar KPI',
  'catalogos.buscarKpiEjemplo': 'Buscar KPI…',
  'catalogos.nuevoKpi': 'Nuevo KPI',
  'catalogos.editarKpi': 'Editar KPI',
  'catalogos.ningunKpi': 'Ningún KPI coincide.',
  'catalogos.kpi': 'KPI',
  'catalogos.macroproceso': 'Macroproceso',
  'catalogos.unidad': 'Unidad',
  'catalogos.unidadEjemplo': '%, días, horas…',
  'catalogos.referencia': 'Referencia',
  'catalogos.referenciaBenchmark': 'Referencia (benchmark)',
  'catalogos.activo': 'Activo',
  'catalogos.desactivado': 'Desactivado',
  'catalogos.activar': 'Activar',
  'catalogos.desactivar': 'Desactivar',
  'catalogos.codigoKpi': 'Código <code>{codigo}</code>: los procesos guardan los valores con él, por eso no cambia.',
  'catalogos.crearKpi': 'Crear KPI',
  'catalogos.verbosIntro': 'El linter del editor exige que cada actividad empiece por un verbo en infinitivo. Los <strong>prohibidos</strong> se marcan como error con el motivo que escribas; los <strong>permitidos</strong> son los que no generan aviso.',
  'catalogos.prohibidos': 'Prohibidos ({n})',
  'catalogos.permitidos': 'Permitidos ({n})',
  'catalogos.verbo': 'Verbo',
  'catalogos.motivoConsultor': 'Motivo que ve el consultor',
  'catalogos.permitir': 'Permitir',
  'catalogos.verboProhibido': 'Verbo prohibido',
  'catalogos.verboEjemplo': 'verbo',
  'catalogos.motivo': 'Motivo',
  'catalogos.motivoEjemplo': 'Por qué no se usa y qué poner en su lugar',
  'catalogos.prohibir': 'Prohibir',
  'catalogos.quitarVerbo': 'Quitar {verbo}',
  'catalogos.verboPermitido': 'Verbo permitido',
  'catalogos.verboPermitidoEjemplo': 'verbo en infinitivo',
  'catalogos.colorDk1': 'Principal (títulos y barras)',
  'catalogos.colorAcento': 'Acento',
  'catalogos.colorLt2': 'Fondo de las láminas',
  'catalogos.colorArena': 'Fondo de tarjetas',
  'catalogos.colorGris': 'Texto secundario',
  'catalogos.colorAntetitulo': 'Antetítulo',
  'catalogos.colorSep': 'Separadores',
  'catalogos.colorChipRol': 'Etiqueta de rol',
  'catalogos.colorTeal': 'Secundario',
  'catalogos.colorRosa': 'Estado: alerta',
  'catalogos.colorVerde': 'Estado: bien',
  'catalogos.colorCirculo': 'Círculos de numeración',
  'catalogos.colorPortadaFondo': 'Carátula: fondo',
  'catalogos.colorPortadaTexto': 'Carátula: texto',
  'catalogos.colorPortadaSub': 'Carátula: subtítulo',
  'catalogos.temasIntro': 'Además de MBC y BBVA (del sistema), cada tema activo aparece en el menú <strong>Exportar → PPTX</strong> del editor.',
  'catalogos.nuevoTema': 'Nuevo tema',
  'catalogos.nuevoTemaTitulo': 'Nuevo tema PPTX',
  'catalogos.sinTemas': 'Todavía no hay temas de cliente. Crea uno a partir del de MBC o del de BBVA.',
  'catalogos.oculto': 'Oculto',
  'catalogos.oculta': 'Oculta',
  'catalogos.ocultar': 'Ocultar',
  'catalogos.mostrar': 'Mostrar',
  'catalogos.eliminarTema': '¿Eliminar el tema {nombre}?',
  'catalogos.temaTitulo': 'Tema {nombre}',
  'catalogos.nombreCliente': 'Nombre del cliente',
  'catalogos.clave': 'Clave',
  'catalogos.claveAyuda': 'Minúsculas, números y guiones. Identifica el tema; no se puede cambiar.',
  'catalogos.baseMbc': 'MBC (carátula con foto)',
  'catalogos.baseBbva': 'BBVA (carátula de color y lámina de cierre)',
  'catalogos.despues': 'Después podrás cambiar colores, tipografías y logotipos.',
  'catalogos.crearYEditar': 'Crear y editar',
  'catalogos.imagenTipo': 'La imagen debe ser PNG o JPEG.',
  'catalogos.imagenPesada': 'La imagen pesa demasiado (máximo 1,4 MB).',
  'catalogos.imagenIlegible': 'No se pudo leer la imagen.',
  'catalogos.pie': 'Pie de lámina',
  'catalogos.autor': 'Autor (propiedades del archivo)',
  'catalogos.colores': 'Colores',
  'catalogos.tipografias': 'Tipografías',
  'catalogos.texto': 'Texto',
  'catalogos.textoAyuda': 'Debe estar instalada donde se abra el PPTX.',
  'catalogos.titulos': 'Títulos',
  'catalogos.logotipos': 'Logotipos y carátula',
  'catalogos.logo': 'Logo sobre fondo claro',
  'catalogos.logoInv': 'Logo sobre fondo oscuro',
  'catalogos.foto': 'Foto de carátula (opcional)',
  'catalogos.sinImagen': 'Sin imagen',
  'catalogos.quitarFoto': 'Quitar foto',
  'catalogos.anchoLogo': 'Ancho del logo (pulgadas)',
  'catalogos.altoLogo': 'Alto del logo (pulgadas)',
  'catalogos.estiloCaratula': 'Estilo de carátula',
  'catalogos.caratulaFoto': 'Con foto (como MBC)',
  'catalogos.caratulaColor': 'De color (como BBVA)',
  'catalogos.laminaCierre': 'Lámina de cierre',
  'catalogos.guardarTema': 'Guardar tema',
  'catalogos.plantillasIntro': 'Al crear un proceso en un proyecto se puede partir de una plantilla activa. Se crean desde una revisión: en el proceso, botón <strong>Guardar como plantilla</strong>. Se quitan el cliente, las personas de la gobernanza, el historial de cambios de la ficha y los valores medidos; revisa que los textos no nombren al cliente.',
  'catalogos.sinPlantillas': 'Todavía no hay plantillas. Abre un proceso y usa «Guardar como plantilla» en una de sus revisiones.',
  'catalogos.plantilla': 'Plantilla',
  'catalogos.elementos': 'Elementos',
  'catalogos.creadaPor': 'Creada por',
  'catalogos.actualizada': 'Actualizada',
  'catalogos.eliminarPlantilla': '¿Eliminar la plantilla {nombre}? Los procesos creados con ella no cambian.',
  'catalogos.plantillaTitulo': 'Plantilla {nombre}'
} as const;

export type TextosShell = typeof es;
